### ISSUE TITLE
Graphql playground trying to get schema from host url instead of whole application url.

### ISSUE THREAD

**Issue by subithal** [graphql-dotnet/server#1011]
## Description

Here is my application url - https://abc.com/def
graphql endpoint - /demo
playground path - ui/playground

now graphql playground trying to get the schema from https://abc.com/demo.
I tried to change the graphql endpoint like this and Getting 404 error.
graphql endpoint - def/demo (Surprisingly it is working fine in localhost but not in my hosted server)

**Comment by sungam3r** [comment]
@Shane32 IIRC you have fixed that.

**Comment by Shane32** [comment]
Fixed in:
- https://github.com/graphql-dotnet/server/pull/853

You may need to ensure that the urls used when configuring the endpoints are relative urls, but then it should work properly with an application url like described above.
