### ISSUE TITLE
UserContext or authorization for WebSockets?

### ISSUE THREAD

**Issue by joshkel** [graphql-dotnet/server#102]
I saw in [this comment](https://github.com/graphql-dotnet/server/issues/70#issuecomment-373757518) how to implement authentication. That's more or less working, but how do I implement authorization (determining whether a user is actually authorized for a particular subscription)?

For my HTTP requests, my controller code sets the GraphQL UserContext with user information that my Query and Mutation objects can then use. (I'm using my own controller code instead of GraphQL .NET Server's HTTP middleware.) However, for WebSockets, I don't see any way for a IOperationMessageListener to access or set a context for the Query/Mutation/Subscription objects to use.

Ideas or suggestions?

Thanks!

**Comment by pekkah** [comment]
You can set your usercontext in execution options

**Comment by joshkel** [comment]
Thank you. I had overlooked that.

What if I need to set it for individual requests, though? I'm passing in a user token when the GraphlQL-over-WebSockets connection is initialized, as recommended by [Apoll](https://www.apollographql.com/docs/graphql-subscriptions/authentication.html), and I've implemented an IOperationMessageListener to receive and process the user, but I don't see any way that the IOperationMessageListener can set the user in a per-WebSockets-connection or per-subscription ExecutionOptions.

**Comment by pekkah** [comment]
I'll look into this more. In the message listener it's possible already to add custom properties to the context but that context is not available in the execution context. It would be nice if the UserContext of the execution context would be a property bag so could pass more data into it without overriding the whole context.

**Comment by joshkel** [comment]
Our project has shifted priorities, so we no longer have an immediate need for this. I'll leave the issue open in case it's something that you or others are interested in.

Thanks for your work on GraphQL .NET Server. Having a sample implementation, complete with WebSockets support, was a huge help for us.

**Comment by wiktor-golonka** [comment]
@pekkah : would be great to have UserContext per Subscription and listener that could perform an action when OnNext method is executed.
Our team main goal is to have a resource based authorization and the best (or even only) place to do that currently is inside Subscription class in 'OnNext' method.

**Comment by pekkah** [comment]
Merged the changes. The sample now has an example.
