### ISSUE TITLE
How to use plugins in Altair?

### ISSUE THREAD

**Issue by Sonic198** [graphql-dotnet/server#1042]
Hi,

Is it possible to enable some plugins in Altaris by default? I would like to enable `altair-graphql-plugin-graphql-explorer`. If it's possible then how I can do that?

Thanks!

**Comment by sungam3r** [comment]
Agree. PR is welcome to facilitate more options.

**Comment by Sonic198** [comment]
PR added. 
https://github.com/graphql-dotnet/server/pull/1044

**Comment by Sonic198** [comment]
@Shane32 when new package release with this change is planned?

**Comment by Shane32** [comment]
As there are no other changes currently planned, I'll release it now.

**Comment by Sonic198** [comment]
Great! Thank you!
