### ISSUE TITLE
Issue with Websockets and Firefox

### ISSUE THREAD

**Issue by satish860** [graphql-dotnet/server#106]
I was getting the following error in most of the browser .
![image](https://user-images.githubusercontent.com/817360/39111767-efb19d56-46f3-11e8-9a35-6e4945102fef.png)

 Chrome and opera allows to ignore but not in IE and Firefox .  There is a possible fix given in the following [URL](https://stackoverflow.com/questions/11768221/firefox-websocket-security-issue) .
Can I Provide a pull request for the same.

**Comment by pekkah** [comment]
@satish860 if you could provide a PR

**Comment by pekkah** [comment]
As no one else has reported this and no PR provided, closing..
