### ISSUE TITLE
Schema will always be a singleton

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/server#107]
Currently, the Schema used will always effectively be a singleton even if it's not registered as such. I have requirements for scoped dependencies in my Schema. 

If the GraphQLMiddleware implemented IMiddleware, then the injected Schema could have the intended lifetime. 
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/extensibility?view=aspnetcore-2.0

**Comment by pekkah** [comment]
That would solve it for normal HTTP requests but for websockets it would still be a singleton.

**Comment by KreativJos** [comment]
The guess on my side is that it isn't possible or wise to have the schema in the current way with another lifetime than 'singleton'. It is quite expensive to build.
Furthermore, if you'd use a Factory pattern for the Schema (which would return a singleton instance each time the 'create'-function is called), the dependent objects still can not be resolved correctly (a database context for instance).

The best way in my view to resolve this issue is by optimizing the build of the schema, or by caching some internal parts so they have to be built only once.

**Comment by johnrutherford** [comment]
It looks like it wouldn't be too difficult to do something similar for the web socket middleware.

@KreativJos, if Schema creation is expensive, then it should be encouraged (though not required) to register it as singleton. Currently if you register it as transient or scoped, understanding that the creation is expensive, it will still effectively be a singleton. This is not obvious and could cause bugs. So I think it would be best for the middleware to be able to respect whatever lifetime the Schema is registered with.

**Comment by Rikarin** [comment]
Is there any workaround for this? My persistence layer is based upon scoped lifetime and this is blocking me.

**Comment by sebastienros** [comment]
You don't need to enforce a singleton is used by keeping a hard reference on it. Just ask for a service that returns a Schema and it's up to the user to define the lifetime of the schema. It's fine to expect the schema instance to be reused, but in many cases the schema can change overtime (for instance a CMS) and using a service would allow the application to return a brand new schema every time it needs to change. Yet it won't prevent the application to always return the same schema if nothing has changed (keeping your 'singleton' optimization effective).

For instance:

```csharp
public interface ISchemaProvider
{
  public Task<Schema> GetSchemaAsync(HttpContext context);
}
```

And in the middleware:

```
public async Task Invoke(HttpContext context)
{
  if (!IsGraphQLRequest(context))
  {
    await _next(context);
    return;
  }
  var schema = await _schemaProvider.GetSchemaAsync(context);
  await ExecuteAsync(context, schema);
}
```

I can even decide to return different schema instances in a multi-tenant scenario.

**Comment by johnrutherford** [comment]
#128 addresses this issue and has been merged. 

The schema is resolved on each request so the registered lifetime will be respected. 

I think the only caveat is that with web sockets, a transient lifetime isn't currently possible. The schema would be created once per connection, not per execution. I have some thoughts on how to make truly transient lifetimes available for web sockets if there is a need for it.
