### ISSUE TITLE
Add support for DataLoader configuration

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/server#108]
I'd like to add support for the DataLoader configuration to these libraries. 

Here's what I was thinking: 

1. Change `AddGraphQL()` to return `IGraphQLBuilder`, which can be used to add other GraphQL-related services.
2. Add an `AddDataLoader()` method to `IGraphQLBuilder`. This would register the necessary services.
3. Create an `IExecutionOptionsProvider` interface. This would have a `GetOptions()` method to create `ExecutionOptions`. It would add all registered instances of `IDocumentExecutionListener` and `IValidationRule`.
4. Anywhere that uses `IDocumentExecuter` would inject `IExecutionOptionsProvider` and use it to help create the options.

**Comment by pekkah** [comment]
Hmm I think number 3 and 4 are already there when using websockets but not for the HTTP.

**Comment by acronoah** [comment]
I hacked it into the http code:
https://github.com/Conning/graphql-dotnet-server/commit/56398c9e1e2693652e056d9adf867c1a961d34d4

**Comment by johnrutherford** [comment]
@pekkah, yeah, I was just looking at that. I think it would be good to unify the setup for HTTP and WebSockets. Maybe create a "GraphQL.Server.Core" library that is referenced by both. That would make it possible to register all of the components just once.

**Comment by johnrutherford** [comment]
#128 has been merged.
