### ISSUE TITLE
Content Security Policy and CDN Scripts

### ISSUE THREAD

**Issue by ferdaarikan** [graphql-dotnet/server#1110]
We are using the Server.All package to allow our users to be able to pick their GraphQL UI from Altair, Playground and GraphiQL. We have an asp .net core application serving those UI's in relevant routes. 

However, we started to get failures recently when loading/running CDN scripts. Mainly due to CSP and browser behavior changes.

I know this is not directly Server.All related but if these were standalone javascript apps I could have replaced cdn scripts with same-origin (hosted) ones such that I don't need to adjust and CSP setting. 

To an extent I can adjust ```Content-Security-Policy``` on my server such that most issues are solved but I still get errors for some of the CDN scripts. 

I wonder if there is a better fix to this or is anything planned or are there others experiencing these issues?

![image](https://github.com/graphql-dotnet/server/assets/13984102/c9523c55-2ca3-49f8-bd9f-fc2d8ed4a038)

**Comment by ferdaarikan** [comment]
Thanks @Shane32 for quick reply

There isn't a public example as far as I am aware. I think this happens with all UI's in some ways as they depend on different scripts. I created a very simple reproducer with a fake schema using altair but easy to extend to others. You can run introspection queries in the example.

> GraphQL.NET Server provides these packages to allow users to quickly configure a user interface for their GraphQL endpoint. It uses the CDN links as we do not intend to redistribute these packages directly within the GraphQL.NET Server package. I also believe that the UI packages use 'floating' versions of the UI (all except GraphiQL). As such, if/as the UI package changes, it could break an application, and we may need to release an update to fix the issue.

We are very happy with this approach and Server.All provides a neat way to include those into our applications.

We can already use authentication via Server.All, our server authenticates every request such that anything served needs to have the appropriate permissions, this applies to UI's as well.

If you run the app and browse to ./ui/altair you can see the loading error in console. There are many errors in the screenshot but they are Visual Studio hot reload related I think. 

The last one in the screenshot is the concerning one.
![image](https://github.com/graphql-dotnet/server/assets/13984102/03fed09a-c6ea-4348-9864-412ecf6ba446)

By the way the error doesn't break the UI's core functionality, such that still docs and queries work but some functionality is not available such as Plugins and post request scripts don't work.

[GraphQLServerExample.zip](https://github.com/graphql-dotnet/server/files/13941061/GraphQLServerExample.zip)

**Comment by Shane32** [comment]
I see what you mean.  It's not that the site won't load the javascript from the CDN, but some of the code inside it won't run properly because it's sandboxed or something like that.

**Comment by ferdaarikan** [comment]
The issue I created in Altair https://github.com/altair-graphql/altair/issues/2403 seems to be fixed via https://github.com/altair-graphql/altair/pull/2416 though I didn't have a chance to try it yet. Since server all pulls the latest of the ui dist's would it be fair to assume that we don't need to do any updates in graphql dotnet server.

**Comment by Shane32** [comment]
Thanks for the update.  Perhaps when you test it, then just close this issue?

**Comment by ferdaarikan** [comment]
This seems to be fixed this time via altair-graphql/altair/pull/2492 though not released yet. I will close this issue anyway as this issue is not needed anymore. I understand that once altair is released we will be able to pick that up via cdn.
