### ISSUE TITLE
Invalid HTML

### ISSUE THREAD

**Issue by Kowjako** [graphql-dotnet/server#1129]
I have a problem, when i use
`app.UseGraphQLGraphiQL("/ui/graphiql", new () { ExplorerExtensionEnabled = false });`

Then i have a weird double lupe on Docs section, if i will not specify this then i dont have access to modify headers.
Please solve it, its looking terrible

**Comment by Kowjako** [comment]
![image](https://github.com/graphql-dotnet/server/assets/19534189/44f3c920-49f5-4bb0-af89-04381c601601)

**Comment by Shane32** [comment]
The page is generated from this:

https://github.com/graphql-dotnet/server/blob/master/src/Ui.GraphiQL/Internal/graphiql.cshtml

Can you write a PR that includes the necessary changes to fix the page?  Please note that the version provided by this middleware is GraphiQL 1.5.1, and the current version is GraphiQL 3.2.0.  Perhaps updating the page to pull the latest version of GraphiQL would fix the issue.

Here is the link to the GraphiQL repository:

https://github.com/graphql/graphiql
