### ISSUE TITLE
GraphiQL Explorer is no longer there in version 8.x?

### ISSUE THREAD

**Issue by jasonlaw** [graphql-dotnet/server#1151]
I am using GraphQL.Server.Ui.GraphiQL.

**Comment by Shane32** [comment]
The only change was done within https://github.com/graphql-dotnet/server/pull/1131 - perhaps you can take a look and see if any further changes are needed.

Note that you can use an old version if you wish.  The UI packages don't depend on any other part of GraphQL.NET / GraphQL.NET Server - you can use whatever version you want.

**Comment by Shane32** [comment]
Please post if you have any further comments, or post a PR if you see changes that should be made.  Thanks!
