### ISSUE TITLE
GraphQL.Server.Ui.Playground autoComplete or Type Box doesn't disappear

### ISSUE THREAD

**Issue by CDMikeThomas** [graphql-dotnet/server#1158]
We are using the package 'GraphQL.Server.Ui.Playground' in version 8.0.2 for having the GraphQL playground UI.
In Chromium based browsers (version latest public available, e.g. Google Chrome, Edge) the autoComplete and type boxes are not disappearing in the editor area of the playground UI. 
The issue seems to be browser specific as in Firefox (version latest public available) the issue does not exist.
Issue is equivalent to what I found here:
https://github.com/graphql/graphql-playground/issues/1429

Below are the images the bug in our software.
Here it is shown that the boxes are not disappearing:
![image](https://github.com/user-attachments/assets/07f25128-a982-43e2-ae69-7c56752245c9)
This error message keeps stacking up in the browser console:
![image (1)](https://github.com/user-attachments/assets/eae9f1bd-aaf4-42a5-a269-f8f2c71e0e11)

**Comment by Shane32** [comment]
Will be released in v8.1.0
