### ISSUE TITLE
GraphQL .Net with .Net Framework 4.8

### ISSUE THREAD

**Issue by fschricker** [graphql-dotnet/server#1163]
Hi,
I am feeling brave (project requirement is .Net Framework 4.8) as I try to have a GraphQL prototype thing running with Visual Studio 2022 as simple as possible, preferably in a "console driven web app": The simplest form would help.

The code I have so far, which builds and runs:

```
using System;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

using GraphQL;
using GraphQL.Types;
using System.Threading;


namespace GraphQLConsoleApp
{
    internal class Program
    {
        static async Task Main(string[] args)
        {


            var host = 
                new WebHostBuilder()
                .UseKestrel(options =>
                {
                    options.ListenLocalhost(5000); // Configure the port here
                })
                .ConfigureServices(services =>
                {
                    services.AddSingleton<GraphQL.Server.Transports.AspNetCore.IHostApplicationLifetime, ApplicationLifetime>();
                    services.AddSingleton<ISchema, MySchema>();
                    services.AddGraphQL(builder =>
                    {
                        builder
                            .AddSystemTextJson()
                            .AddErrorInfoProvider(opt => opt.ExposeExceptionDetails = true)
                            .AddSchema<MySchema>()
                            .AddGraphTypes(typeof(MySchema).Assembly);
                    });
                })
                .Configure(app =>
                {
                    app.UseWebSockets();
                    app.UseGraphQL<ISchema>();
                })
                .Build();

            await host.RunAsync();
        }
    }

    public class MySchema : Schema
    {
        public MySchema(IServiceProvider provider) : base(provider)
        {
            Query = provider.GetRequiredService<MyQuery>();
        }
    }

    public class MyQuery : ObjectGraphType
    {
        public MyQuery()
        {
            Field<StringGraphType>("hello", resolve: context => "Hello, world!");
        }
    }

    public class ApplicationLifetime : GraphQL.Server.Transports.AspNetCore.IHostApplicationLifetime
    {
        public CancellationToken ApplicationStopping => new CancellationTokenSource().Token;

    }
}

```

Console windows says:
![image](https://github.com/user-attachments/assets/98fa03a7-c120-4179-8057-3f583785c52a)

But for the life of me I get nothing using postamn from http://localhost:5000/graphql

Anybody? I am stuck...

kindest regards,
Florian

**Comment by Shane32** [comment]
I'm sure we can get it working, but I can't review just now.  In the meantime, have you read the readme regarding .NET Framework:

https://github.com/graphql-dotnet/server?tab=readme-ov-file#aspnet-core-21--net-framework-48

Or checked out the sample application:

https://github.com/graphql-dotnet/server/tree/master/samples/Samples.Net48

The sample project above is tested against .NET Framework 4.8 for each pull request, so the sample project is "guaranteed" to work.

**Comment by Shane32** [comment]
Offhand looking at your code I don't see any glaring issues.  I would use the provided `services.AddHostApplicationLifetime();` extension method rather than defining your own implementation.  You won't need `services.AddSingleton<ISchema, MySchema>();` because you already have `.AddSchema<MySchema>()`.  I've not tried using Kestrel for .NET Framework 4.8 but I don't know why it wouldn't work.  (The sample application (link supplied above) uses the ASP.NET template from that era, rather than a console app.)  Does postman give you an error code or anything?

**Comment by Shane32** [comment]
I tried your code and it worked with no changes 🤷‍♂️ 

![image](https://github.com/user-attachments/assets/c427f492-0688-4bf3-b70e-f38fa43fd901)

**Comment by Shane32** [comment]
I created a .NET Framework console application and then added two dependencies:
- GraphQL.Server.Transports.AspNetCore
- GraphQL.SystemTextJson

All of the other dependencies were automatically installed.  Please see attachment for complete list (renamed to txt so that it can be uploaded here).

[packages.config.txt](https://github.com/user-attachments/files/17737942/packages.config.txt)

**Comment by Shane32** [comment]
Please note that ASP.NET Core version 2.2 is NOT supported by MS.  You want to use the latest 2.1 versions.  ASP.NET Core 2.1 is still fully supported by MS when used with .NET Framework.

**Comment by Shane32** [comment]
If you convert your project to a SDK-style project, the project works correctly with this csproj:

```csproj
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="8.1.0" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="8.2.1" />
  </ItemGroup>
</Project>
```

**Comment by fschricker** [comment]
Thank you for your effort and help getting stuff to work: Using the SDK-style project, after removing all locally downloaded packages I can finally report success. 😀

The previous setup still seems to have some dependency issues as the error "get_Features missing in Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.Internal.SocketConnection" indicates. But Google was letting me down completely here on what may be the culprit. 
But I won't further investigate as the project uses SDK-style projects anyways and the setup you provided works!

So thanks again, wishing you all the best
regards,
Florian

**Comment by fschricker** [comment]
For anybody looking for help, this is the minimal setup which "works for me":

Project file:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="8.1.0" />
    <PackageReference Include="GraphQL.SystemTextJson" Version="8.2.1" />
  </ItemGroup>
</Project>
```

Program.cs:

```
using System;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

using GraphQL;
using GraphQL.Types;
using GraphQL.Server;

namespace GraphQLConsoleApp
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            var host = 
                new WebHostBuilder()
                .UseKestrel(options =>
                {
                    options.ListenLocalhost(5000);
                })
                .ConfigureServices(services =>
                {
                    services.AddHostApplicationLifetime();
                    services.AddGraphQL(builder =>
                    {
                        builder
                            .AddSystemTextJson()
                            .AddErrorInfoProvider(opt => opt.ExposeExceptionDetails = true)
                            .AddSchema<MySchema>()
                            .AddGraphTypes(typeof(MySchema).Assembly);
                    });
                })
                .Configure(app =>
                {
                    app.UseGraphQL<ISchema>();
                })
                .Build();

            await host.RunAsync();
        }
    }

    public class MySchema : Schema
    {
        public MySchema(IServiceProvider provider) : base(provider)
        {
            Query = provider.GetRequiredService<MyQuery>();
        }
    }

    public class MyQuery : ObjectGraphType
    {
        public MyQuery()
        {
            Field<StringGraphType>("hello", resolve: context => "Hello, world!");
        }
    }
}
```

It is not much but it might help somebody else...

regards,
Florian
