### ISSUE TITLE
subscriptionsClient.subscribe is not a function

### ISSUE THREAD

**Issue by Jonatthu** [graphql-dotnet/server#125]
I am getting this error using the example of this repo.

I am using IIS

subscription MessageAdded {
  messageAdded {
    from { id displayName }
    content
  }
}

{
  "message": {
    "content": "Message",
    "fromId": "1"
  }
}

but for query and mutation is fine :/

I am using https://localhost:44351/ui/graphiql to execute this

**Comment by jonbudd** [comment]
I'm also having this problem, any tips?

**Comment by jonbudd** [comment]
Figured it out; I wasn't integrating with this project specifically, but was using the npm package `apollo-server-express`, so I'm not sure how relevant this solution will be to people in this project. Turns out that `apollo-server-express` stopped supporting graphiQL in version `1.4.0`, release a few days ago. You can use an earlier version, but you also may need to manually specify that the graphiql package, `apollo-server-module-graphiql`, also is version `1.3.4`. So using these versions in my package.json helped:

    "apollo-server-express": "1.3.4",
    "apollo-server-module-graphiql": "1.3.4"

**Comment by SazalRa** [comment]
Any update ? facing the same problem " subscriptionsClient.subscribe is not a function" 
packages are-
{
"apollo-cache-inmemory": "^1.2.5",
    "apollo-client": "^2.3.5",
    "apollo-link-http": "^1.5.4",
    "apollo-server-hapi": "^1.4.0",
    "graphql": "^0.13.2",
    "graphql-subscriptions": "^0.5.8",
    "graphql-tools": "^3.0.5",
    "hapi": "^17.5.2",
    "merge-graphql-schemas": "^1.5.2",
    "mongoose": "^5.2.3",
    "subscriptions-transport-ws": "^0.9.12"
}
`import { graphqlHapi, graphiqlHapi } from 'apollo-server-hapi';
import { makeExecutableSchema } from 'graphql-tools';
import { server } from './startServer';
import { HapiConfig } from '../../config';
import path from 'path';
import { fileLoader, mergeResolvers, mergeTypes } from 'merge-graphql-schemas';
import ws from 'ws';
import { execute, subscribe } from 'graphql';
import { SubscriptionServer, SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws';
import { PubSub, SubscriptionManager } from 'graphql-subscriptions';
import ApolloClient, { createNetworkInterface } from 'apollo-client';
import { HttpLink } from 'apollo-link-http';
import { InMemoryCache } from 'apollo-cache-inmemory'
import fetch from 'node-fetch';
import { createServer } from 'http';

const ResolvesArray = fileLoader(path.join(__dirname, '../api/**/graphQL/resolver.js'));
const CreateResolvers = mergeResolvers(ResolvesArray);

// Merge all schemas file
const TypesArray = fileLoader(path.join(__dirname, '../api/**/graphQL/schema.graphql'));
const GraphqlSchemas = mergeTypes(TypesArray, { all: true });
// const schema = GraphqlSchemas;

const ExecuteableSchema = makeExecutableSchema({
    typeDefs: [GraphqlSchemas],
    resolvers: CreateResolvers
});
const GRAPHQL_ENDPOINT = `http://${ HapiConfig.hostname }:${ HapiConfig.port }/graphql`;
const InitApolloServer = async () => {
    try {
        await server.register({
            plugin: graphqlHapi,
            options: {
                path: '/graphql',
                graphqlOptions: {
                    schema: ExecuteableSchema
                },
                route: {
                    cors: true
                }
            }
        });
        
        await server.register({
            plugin: graphiqlHapi,
            options: {
                path: '/graphiql',
                graphiqlOptions: {
                    endpointURL: '/graphql',
                    subscriptionsEndpoint: `ws://${HapiConfig.hostname}:${ HapiConfig.port }/subscriptions`
                },
            }
        });

        const SubscriptionS = new SubscriptionServer({
            execute,
            subscribe,
            schema: GraphqlSchemas
        },{
            server: server.listener,
            path: '/subscriptions'
        });
    }
    catch (error) {
        console.log('Error on apollo server!',error);
    }
};

export default InitApolloServer;`

**Comment by joemcbride** [comment]
@SazalRa You are using a completely different project than this one.  This one is a .NET Core Server.  I would suggest to post your question on the apollo-server project since that is what you are using.  https://github.com/apollographql/apollo-server/issues

**Comment by Jonatthu** [comment]
Sorry for not answering, I just downloaded the repo from here and noticed that this one does not have the same issues, so I match everything on my own project, I will try the same fixes as you guys.
