### ISSUE TITLE
Add Automatic Persisted Query Support

### ISSUE THREAD

**Issue by RehanSaeed** [graphql-dotnet/server#132]
[Automatic Persisted Queries](https://blog.apollographql.com/automatic-persisted-queries-and-cdn-caching-with-apollo-server-2-0-bf42b3a313de) is something implemented by the Appollo GraphQL Server. The server caches queries with their hash and the client can send a hash of the query instead of the full multi-kilobyte payload. To illustrate:

![1 mmsphtd3-9p7dqcb5b1d7g](https://user-images.githubusercontent.com/2270364/42558379-f0e44dbc-84e8-11e8-99ef-6d051102f7da.png)

If no hash of the query is found on the server:

![1 1qc1q6atkn1k7x8zduc9ja](https://user-images.githubusercontent.com/2270364/42558497-5538e516-84e9-11e8-84f2-07ed16aca13c.png)

I think this can be implemented by using the built in `IDistributedCache` in ASP.NET Core.

**Comment by RehanSaeed** [comment]
Forgot to mention that there is a `cacheControl` directive that can be used alongside this. For example, this schema indicates that all fields that return an Author should be cached for 60 seconds, and that the posts field should itself be cached for 180 seconds:

```
type Author @cacheControl(maxAge: 60) {
  id: Int
  firstName: String
  lastName: String
  posts: [Post] @cacheControl(maxAge: 180)
}
```

More info in the [docs](https://www.apollographql.com/docs/guides/performance.html#automatic-persisted-queries).

**Comment by aleGuardiola** [comment]
I am working in a project that already support this two features maybe you can check it out. I did it based on the apollo server. https://github.com/aleGuardiola/Graphql-Controller

**Comment by miladkakouli** [comment]
you can use this package for graphql persisted queries 

https://www.nuget.org/packages/GraphQL.PersistedQueries/
https://github.com/miladkakouli/graphql-dotnet-persistedqueries

**Comment by sungam3r** [comment]
Regarding `cacheControl` directives - it is another task to do compared to APQ iitself.

**Comment by sungam3r** [comment]
Done in https://github.com/graphql-dotnet/graphql-dotnet/pull/3134.
