### ISSUE TITLE
WebSocket handshake error.

### ISSUE THREAD

**Issue by ximbor** [graphql-dotnet/server#138]
When I start the project, I get this error in browser console (Chrome):
"WebSocket connection to 'ws://localhost:60340/graphql' failed: Error during WebSocket handshake: Unexpected response code: 404".

**Comment by vlatk0o** [comment]
Why is this closed?

**Comment by BenjaBobs** [comment]
![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)
