### ISSUE TITLE
Can't use both Websockets + Http Middleware

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/server#144]
It appears that with the merging of #128 it broke the middleware.  I'm guessing it is the use of `builder.Map` since the middleware points to the same endpoint.  So registering both overrides the other.  If you try using GraphiQL you'll get a 404 for either the http or websocket endpoint, depending on the order in which you add the middleware.

https://github.com/graphql-dotnet/server/blob/c8d2587d0106136fb09879d3b84a7143ddf282f7/src/Transports.AspNetCore/ApplicationBuilderExtensions.cs#L21

https://github.com/graphql-dotnet/server/blob/c8d2587d0106136fb09879d3b84a7143ddf282f7/src/Transports.Subscriptions.WebSockets/ApplicationBuilderExtensions.cs#L21

**Comment by johnrutherford** [comment]
Ah yeah, that makes sense. Good catch.
