### ISSUE TITLE
Meta All Package

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/server#148]
Since there are several packages, I think it would be helpful to create an "All" package.  I think I would lean toward combining all of them into a single package (excluding the GraphiQL bits) in the future.

**Comment by sungam3r** [comment]
In fact, this idea seems all the more good the less you think about it. In principle, there will be some benefit from such a package. Another thing is that he will act as a "greedy seller", imposing unnecessary services.

**Comment by sungam3r** [comment]
I think that the structure of projects needs refactoring first. A project with abstractions layer contains code that is not anstractions.

**Comment by sungam3r** [comment]
> Another thing is that he will act as a "greedy seller", imposing unnecessary services.

This is no longer so important especially with the `PublishTrimmed` option.

**Comment by sungam3r** [comment]
Done in #439
