### ISSUE TITLE
400 Bad Request and Errors

### ISSUE THREAD

**Issue by johnrutherford** [graphql-dotnet/server#149]
Currently the HTTP middleware sets the response code to "400 Bad Request" if there are any errors from the GraphQL execution. 

``` csharp
context.Response.StatusCode = result.Errors?.Any() == true ? (int)HttpStatusCode.BadRequest : (int)HttpStatusCode.OK;
```

An HTTP 400 status code is meant to indicate that the client made an invalid/malformed request that the server will not process. I think 400 Bad Request should only be used for an issue with the transport protocol, like an unsupported `Content-Type` header. 

Treating a transport error the same as an execution error makes it hard for clients to distinguish between the two. 

I think as long as there are no issues with the transport protocol, the middleware should return a 200 OK and the client must check for Errors in the GraphQL response.

I looked at several other implementations of an HTTP transport including Apollo Server and from what I can tell, they all return 200 OK for this situation. 

Obviously changing this behavior could cause problems, so I wanted to see what other people thought.

**Comment by pekkah** [comment]
This has sneaked in. Execution errors shouldn't result in an BadRequest.

**Comment by joemcbride** [comment]
Added in #151
