### ISSUE TITLE
Subscription authorization

### ISSUE THREAD

**Issue by coding4food** [graphql-dotnet/server#156]
Subscriptions implementation passes `MessageHandlingContext` instance as `userContext` argument down the processing pipeline, so `graphql-dotnet/authorization` does not work with subscriptions.

**Comment by joemcbride** [comment]
Known issue at this time. This is dependent on https://github.com/graphql-dotnet/graphql-dotnet/issues/637 getting implemented.

**Comment by corstian** [comment]
Why is https://github.com/graphql-dotnet/server/blob/develop/samples/Samples.Server/AddAuthenticator.cs being commented out? While we're waiting this would be an excellent intermediate solution I think.

**Comment by johnrutherford** [comment]
PR #158 adds support for endpoint authorization that integrates with ASP.NET Core authentication and authorization policies. 

If the "AddAuthenticator" approach works for you, then there's no reason not to use it for now.

**Comment by klowdo** [comment]
I made this to work with websockets https://github.com/graphql-dotnet/authorization/pull/19

**Comment by rose-a** [comment]
IMO it's important to not only think about authorizing *subscriptions*, but any GraphQL request which is passed via websocket (https://www.apollographql.com/docs/link/links/ws.html).

I built a working solution in the "AddAuthenticator" style using the pre-release from #208 which is  meant to be authorization schema independent in that the whole content of the authorization header is passed in an *authorization* field and which then is run through the whole `AuthenticationMiddleware`:

```c#
/// <summary>
/// allows to pass the content of the HTTP Authorization header in a payload field 'authorization'
/// </summary>
public class AuthorizationListener: IOperationMessageListener
{
    private readonly IServiceProvider _serviceProvider;

    public AuthorizationListener(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider;
    }

    /// <summary>
    /// allows to pass the content of the HTTP Authorization header in a payload field 'authorization'
    /// </summary>
    /// <param name="context"></param>
    /// <returns></returns>
    public async Task BeforeHandleAsync(MessageHandlingContext context)
    {
        // try to parse token from payload and quit if none is present
        var authorization = (context.Message.Payload as JObject)?.Value<string>("authorization");
        if (string.IsNullOrEmpty(authorization))
            return;

        // create new scope to be able to run the authorization handler again which is otherwise prevented
        // by AuthenticationHandler.HandleAuthenticateOnceAsync()
        using (var serviceScope = _serviceProvider.CreateScope())
        {
            // create temporary context
            var httpContext = new DefaultHttpContext {RequestServices = serviceScope.ServiceProvider};

            // set the Authorization header of the context
            httpContext.Request.Headers["Authorization"] = authorization;

            // create and run AuthenticationMiddleware
            var authenticationMiddleware = new AuthenticationMiddleware(ctx =>
                {
                    context.Properties[MessageHandlingContextClaimsPrincipalAccessor.ClaimsPrincipalKey] =
                        ctx.User;
                    return Task.CompletedTask;
                },
                httpContext.RequestServices.GetService<IAuthenticationSchemeProvider>());
            await authenticationMiddleware.Invoke(httpContext).ConfigureAwait(false);
        }
    }

    public Task HandleAsync(MessageHandlingContext context)
    {
        return Task.CompletedTask;
    }

    public Task AfterHandleAsync(MessageHandlingContext context)
    {
        return Task.CompletedTask;
    }
}
```

**Comment by jonmill** [comment]
@rose-a - I'm attempting to use your above solution to authenticate WebSocket subscriptions and JWT tokens, but the GraphQL `AuthorizeWith` call doesn't seem to pick up on the authenticated client...any idea if your solution works with Subscriptions and JWTs?

**Comment by STRATZ-Ken** [comment]
Any word on if this still works?  I get the user on `context.Properties[MessageHandlingContextClaimsPrincipalAccessor.ClaimsPrincipalKey] = ctx.User;`
But once I check inside the Subscribe Method, I dont see any properties or the user object.

**Comment by jonmill** [comment]
@STRATZ-Ken - I ended up rolling my own authentication for subscriptions and abandoning the approach taken here

**Comment by STRATZ-Ken** [comment]
I am about 10 hours, any desire to share? :) @jonmill

**Comment by jonmill** [comment]
Sure thing :). It took a bit of work on both the client and server side to get it to work nicely and only work with authenticated clients. 

1) Setup JWT authentication as normal 
2) Enable Websockets using the ASP Core Configure function (we use a different URL for subscriptions for other reasons, but you can remove `/subscriptions` to not override this.
```
app..UseWebSockets(new WebSocketOptions()
{
     KeepAliveInterval = TimeSpan.FromSeconds(20),
})
.UseGraphQLWebSockets<PlatformSchema>("/subscriptions")
```
3) In the Subscription implementation, we have an endpoint that the frontend calls to setup notifications from the server:
```
AddField(new EventStreamFieldType()
            {
                Name = "notifications",
                Type = typeof(NotificationBaseOutputType),
                Arguments = new QueryArguments() { new QueryArgument<NonNullGraphType<StringGraphType>>() { Name = "authToken" } },
                Resolver = new FuncFieldResolver<NotificationBase?>(ResolveNotificationForUser),
                Subscriber = new EventStreamResolver<NotificationBase>(SubscribeToNotificationsForUser),
            });
```

When callers use this endpoint, they pass the JWT as a normal GraphgQL argument in order for us to manually verify the JWT. Once the JWT is verified, we can create an Observable for notifications and add it to a runtime cache on the server. We create wrappers around the Observable to allow us to cleanup nicely when the Observable fires a Cancellation (ie when the TCP connection is closed).

Now we have the Websocket connection established, we verified the user auth, and we have the observable cached with the user credentials so we can push data down to them through the Observable.


The difficult part about Websocket Subscriptions is the lack of control the web side has; we found a way to not require passing the JWT manually and using cookie auth, but hit snags there. If you rely on Cookie JWT auth for Websocket Subscriptions, it appears that the javascript side cannot specify which cookie to use in the websocket and the browser takes whatever cookie is "first", so that led to issues in corporate environments where we can't control all the cookies. Instead of trying to find a way around that, we're just sticking to passing the JWT as an argument and having the frontend establish the connection that way

**Comment by STRATZ-Ken** [comment]
I saw an example of someone saying its just easier to require a user to send Bearer token as a param.  Pretty much what you did as well.

Just got it working, though, I hope this isn't given up on in this project. Some extra JWT Handler code will bug me. :)


`private async Task<IObservable<Object>> Subscribe(ResolveEventStreamContext context)
        {
            var bearer = context.GetArgument<string>("bearer");

            var user = ValidateBearer(bearer);
            var identity = user?.Identity?.GetUserGuid();
            if (!identity.HasValue)
            {
                context.Errors.Add(new GraphQL.ExecutionError($"Missing Bearer Token"));
                return new List<Object>().ToObservable();
            }

            return stuff....
        }


        // This Authentication below is only used for Subscriptions with GraphQL as its not yet supported. It mimics Startup.cs file in API.
        private ClaimsPrincipal ValidateBearer(string bearer)
        {
            return handler.ValidateToken(bearer, tokenParams, out SecurityToken token);
        }

        JwtSecurityTokenHandler handler = new JwtSecurityTokenHandler();
        private static byte[] key = System.Text.Encoding.ASCII.GetBytes(ConfigurationRepository.Configuration["APIJWTSecurityKey"]);
        private TokenValidationParameters tokenParams = new TokenValidationParameters
        {
            ValidIssuer = ConfigurationRepository.Configuration["TokenIssuer"], 
            ValidateAudience = false,
            IssuerSigningKey = new SymmetricSecurityKey(key) 
        };
`

**Comment by KreativJos** [comment]
Personally, I think there should not only be a MessageHandlingContext, but also something like a SubscriptionContext, which can handle things like the user context. The MessageHandlingContext is specific to the current message (which is kind of obvious).

Currently we have solved this issue by using a simple workaround based on the code from [AddAuthenticator](https://github.com/graphql-dotnet/server/blob/develop/samples/Samples.Server/AddAuthenticator.cs)

Basically, just create something like this:

```
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Http;

using GraphQL.Server.Transports.Subscriptions.Abstractions;

using Newtonsoft.Json.Linq;

namespace Authentication
{
    public class AuthenticationListener : IOperationMessageListener
    {
        public static readonly string PRINCIPAL_KEY = "User";

        private readonly IHttpContextAccessor _httpContextAccessor;

        public AuthenticationListener(IHttpContextAccessor contextAccessor)
        {
            this._httpContextAccessor = contextAccessor;
        }

        private ClaimsPrincipal BuildClaimsPrincipal(string token)
        {
            // Your code here
            // A user context builder can be included via constructor injection,
            //  and possibly the Authorization payload can be set (hacked)
            //  to the Authorization header on the http context
            return null;
        }

        public Task BeforeHandleAsync(MessageHandlingContext context)
        {
            if (context.Message.Type == MessageType.GQL_CONNECTION_INIT)
            {
                var payload = context.Message.Payload as JObject;

                if (payload != null && payload.ContainsKey("Authorization"))
                {
                    var auth = payload.Value<string>("Authorization");

                    // Save the user to the http context
                    _httpContextAccessor.HttpContext.User = BuildClaimsPrincipal(auth);
                }
            }

            // Always insert the http context user into the message handling context properties
            // Note: any IDisposable item inside the properties bag will be disposed after this message is handled!
            //  So do not insert such items here, but use something like 'context[PRINCIPAL_KEY] = [...]'
            context.Properties[PRINCIPAL_KEY] = _httpContextAccessor.HttpContext.User;

            return Task.CompletedTask;
        }

        public Task HandleAsync(MessageHandlingContext context) => Task.CompletedTask;
        public Task AfterHandleAsync(MessageHandlingContext context) => Task.CompletedTask;
    }
}
```

And lastly, make sure these lines are in your startup.ConfigureServices:
```
services.AddHttpContextAccessor();
services.AddTransient<IOperationMessageListener, AuthenticationListener>();
```

**Comment by AndyEdmonds** [comment]
@KreativJos Thanks, this solved the problem of authorising subscriptions on my tenanted SaaS site.

**Comment by Shane32** [comment]
For requests with an `Authorization` HTTP header, ASP.NET Core will handle authentication and no special code is needed.  However, browsers do not support sending the header with a WebSocket connection, so an authorization token must be passed in the query string or within the payload of the "Connection Init" initial WebSocket message (which is the purpose of that message), as shown above with the custom `IOperationMessageListener` implementation.

Within version 7, GraphQL.NET Server has embedded support for this type of authorization via the new `IWebSocketAuthenticationService` interface, replacing the `IOperationMessageListener` approach shown above.  This interface's `AuthenticateAsync` method is passed the "Connection Init" payload as well as the `HttpContext`.  Simply set `HttpContext.User` to an instance of `ClaimsPrincipal` and any other authorization code based on `HttpContext.User` (such as the included authorization validation rule) will work properly.  Note that it is unfortunate that there is no easy way to tie into the ASP.NET `IAuthorizationService` interface; the methods there operate directly on the `HttpContext`.

In addition to the above, the user context builder in v7 is compatible with subscriptions, and for WebSocket connections the builder delegate is passed both the HttpContext and the Connection Init payload.  So you can use the user context to hold authentication information if desired.

There is now documentation within the readme file (for v7) covering these topics including sample code.  I plan to add a sample project with JWT bearer authentication and subscription support, but have not done so yet.
