### ISSUE TITLE
AddGraphQLHttp()

### ISSUE THREAD

**Issue by IT786** [graphql-dotnet/server#160]
In version 3.0 I can find AddGraphQLHttp()

After installing 
Install-Package GraphQL.Server.Transports.AspNetCore -Version 3.1.0

AddGraphQLHttp() not available

**Comment by ntaranov** [comment]
They have refactored code to abstract transport layer. 

Please refer to this link to figure out what has changed in setup code. 
https://github.com/graphql-dotnet/server/blob/f28a93fec4c8fcfe0b6c51c20a3eaace1c2040ca/samples/Samples.Server/Startup.cs

**Comment by IT786** [comment]
Thank you ntaranov
