### ISSUE TITLE
Weird `Â` characters everywhere

### ISSUE THREAD

**Issue by kenrim626** [graphql-dotnet/server#163]
Currently we are using your GraphQL.Server.Ui.GraphiQL package in a prototype for a graphql server application, but the GUI is filled by the character `Â`:

![image](https://user-images.githubusercontent.com/8868179/44909969-b52dbe00-ad21-11e8-9b01-0292001707e7.png)

The same symbol is blinking at the position of the cursor.

While trying to find a way to fix this issue I tried to download your repository myself and added the following line to the header of `server/src/Ui.GraphiQL/Internal/graphiql.cshtml`:

`<meta charset="UTF-8">`

With the encoding set to the UTF-8 charset, the `Â` characters disappeared. To do this manually is no really great solution as we have to change this on any update. 

NPM package versions:
GraphQL v2.0.0
GraphQL.Server v1.1.0.1
GraphQL.Server.Ui.GraphiQL v3.2.0

**Comment by kenrim626** [comment]
Closed: Should be fixed in the develop branch now.

**Comment by minawalphonce** [comment]
when shall we expect this fix to be pushed to nuget ?
