### ISSUE TITLE
Start a GraphQL Server from an ASP.NET 4.6.1 Framework Application?

### ISSUE THREAD

**Issue by klacol** [graphql-dotnet/server#167]
We have an ASP.NET Application based on .NET Framework 4.6.1 (not Core) hosted on IIS.

We want to embed a GraphQL Endpoint (a GQL server) in this application to use the same processes for the endpoint and the web application. This would allow us, to share the events from the web application also for the GQL subscriptions . This is the idea.

We have seen the issue #664 and it seems to be possible, to install the GQL server, as a sub application in IIS, but then we run on seprate processes. This is not what we want.

So my question are:

Can we start the GQL server from within a ASP.NET Application based on .NET Framework 4.6.1 (not Core) hosted on IIS?

**Comment by joemcbride** [comment]
You can use 4.6.1 to host a GraphQL server, though this particular project only supports .NET Core.

This examples uses a webapi:  https://github.com/graphql-dotnet/examples/tree/master/src/AspNetWebApi

The core GraphQL library supports subscriptions, though you would need to write the transport layer handling (such as websockets).

**Comment by pekkah** [comment]
For subscriptions we currently support websockets built on top of Core libraries so you would need to implement https://github.com/graphql-dotnet/server/blob/develop/src/Transports.Subscriptions.Abstractions/IMessageTransport.cs using some other websocket library.
