### ISSUE TITLE
[Subscriptions] - Unable to cast

### ISSUE THREAD

**Issue by deinok** [graphql-dotnet/server#168]
ref: https://github.com/graphql-dotnet/graphql-client/tree/samples/samples/GraphQL.Server.Sample

Running:
```graphql
subscription{
  dateTime
}
```

Returns:
```json
{
  "data": null,
  "error": [
    {
      "message": "GraphQL.ExecutionError: Error trying to resolve dateTime. ---> System.InvalidCastException: Unable to cast object of type 'System.Reactive.Linq.ObservableImpl.AsObservable`1[System.DateTime]' to type 'System.IObservable`1[System.Object]'.\r\n   at GraphQL.Resolvers.EventStreamResolver`1.GraphQL.Resolvers.IEventStreamResolver.Subscribe(ResolveEventStreamContext context)\r\n   at GraphQL.Execution.SubscriptionExecutionStrategy.ResolveEventStreamAsync(ExecutionContext context, ExecutionNode node)\r\n   --- End of inner exception stack trace ---",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "dateTime"
      ],
      "extensions": {
        "code": "INVALID_CAST"
      }
    }
  ]
}
```

Seems like there is some kind of incompatibility between System.IObservable and System.Reactive, or there are some kind of programing error, @pekkah could you take a look at the link i have linked. Should be pretty simple, just to tests subscription support. Notify every second sending the DateTime.UtcNow

**Comment by rose-a** [comment]
This is https://github.com/graphql-dotnet/graphql-dotnet/issues/770, graphql-dotnet is currently unable to return anything but object types from subscriptions.

I provided a fix in https://github.com/graphql-dotnet/graphql-dotnet/pull/989...

**Comment by deinok** [comment]
Ty @rose-a
