### ISSUE TITLE
How to add some custom validation rules ?

### ISSUE THREAD

**Issue by rajmondburgaj** [graphql-dotnet/server#169]
I am using this library in my project and wanted to know how could I add some validation rules if there is an option to do this ? I am asking because DocumentExecuter is used internally and can not pass those rules to Execute method.

Thanks

**Comment by joemcbride** [comment]
Create a rule and add it as a service.  It will get passed to the executor.

```
services.AddTransient<IValidationRule, MyRule>();
```

**Comment by rajmondburgaj** [comment]
Oki great, thanks for your answer 👍
