### ISSUE TITLE
Repo rename

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/server#17]
@joemcbride maybe rename this repo to graphql-dotnet-server as it closer matches the functionality. It already contains a middlware for both normal json queries and subscription transport. I'll separate the middleware for running normal queries to it's own project and nuget package. That should help with some of the requests for "builtin" middlware on main repo.

**Comment by pekkah** [comment]
There's already a nuget with name GraphQL.Server so need to think of better name.

**Comment by joemcbride** [comment]
Did you still want the repo renamed or wait until nuget name is determined?  I would suggest just `server`, since the repo is already under the `graphql-dotnet` org.  `graphql-dotnet/graphql-dotnet-server` seems redundant.

**Comment by pekkah** [comment]
Yep. Just "server" sounds good.

**Comment by joemcbride** [comment]
Repo renamed, here's the new AppVeyor stuff.

```
[![Build status](https://ci.appveyor.com/api/projects/status/x0nf67vfao60wf7e/branch/master?svg=true)](https://ci.appveyor.com/project/graphql-dotnet-ci/server/branch/master)
```

[![Build status](https://ci.appveyor.com/api/projects/status/x0nf67vfao60wf7e/branch/master?svg=true)](https://ci.appveyor.com/project/graphql-dotnet-ci/server/branch/master)

**Comment by pekkah** [comment]
Thanks :)
