### ISSUE TITLE
Is it possible to add a custom warning section in graphql response ?

### ISSUE THREAD

**Issue by rajmondburgaj** [graphql-dotnet/server#170]
I have a case where I expect a languageCodeId from the user and if this is invalid there is a fallback method executed which provides a default languageCodeId in order to return some data to the user even though the used does not know if the params passed are correct or something is smelling. So, what I wanted to do is to return some data because we can not throw exceptions at this point that easily because it might have a big impact in many services. What would be good is to have three sections in the response like this:

    {
         "data": {
           "countries": //somelist
         },
         "errors": [
          {  
          }],
         "warnings": [
          {  
              "message":"Please provide a valid languageCodeId because currently we are using default one."
          }]
    }

In this case the client does not stop his workflow but he is aware something is smelling in his side.

Is there a way to achieve this ?

Thanks

**Comment by BenjaBobs** [comment]
According to the [spec](https://facebook.github.io/graphql/June2018/#sec-Response-Format) that would be an illegal response, but it does however state the you can specify an `extensions` entry in the top-level response like this:
```json
{
	"data": {
		"countries": null
	},
	"extensions": {
		"warnings": [
			{
				"message":"Please provide a valid languageCodeId because currently we are using default one."
			}
		]
	}
}
```

IIRC there is currently no easy way to do this from graphql dotnet, someone correct me if I'm wrong.

**Comment by sungam3r** [comment]
@BenjaBobs You're right. Extensions can be used for any additional information. Another way is to add warning information to the returned data type itself, thereby legitimizing it at the api level. This may require extensive api (schema) changes if warnings can be received from anywhere.

**Comment by ianchanning** [comment]
@BenjaBobs Thankyou very useful link to the spec - although it's broken now. This is the most recent: https://spec.graphql.org/October2021/#sec-Response-Format

**Comment by Shane32** [comment]
FYI the `extensions` entry in the result has been supported since GraphQL.NET 3.0.0 ( https://github.com/graphql-dotnet/graphql-dotnet/pull/531 ).  Also, input extensions have been supported since 5.0.0 ( https://github.com/graphql-dotnet/graphql-dotnet/pull/2766 ).
