### ISSUE TITLE
Add Headers to Playground and Voyager middleware

### ISSUE THREAD

**Issue by lemonadey** [graphql-dotnet/server#176]
GraphQL Playground as well as Voyager both allow Headers to be set when Registering them middleware.

If the Backend requires a auth header the Voyager middleware does not work since you can't set it manually.
For Playground you can set the Auth header manually but it would be convenient if this got set from code.

I suggest extending the GraphQLPlaygroundOptions and GraphQLVoyagerOptions to allow adding headers.

**Comment by michaelolo24** [comment]
+1

**Comment by raphaelvp** [comment]
+1

**Comment by seanzi86** [comment]
+1

**Comment by sungam3r** [comment]
Done for GraphQL Playground in #326

**Comment by sungam3r** [comment]
Done for Voyager in #328

**Comment by sungam3r** [comment]
@lemonadey you can try the latest preview versions.
