### ISSUE TITLE
How to set or configure FieldNameConverter in graphql-dotnet server

### ISSUE THREAD

**Issue by hasibul2363** [graphql-dotnet/server#180]
By default, the response is camelCase. I want to get the response in Pascale case or without any case conversion. How I can achieve this?
Expecting your help.

**Comment by BenjaBobs** [comment]
You can create an `IFieldNameConverter` and set it in your `Schema` iirc.

**Comment by hasibul2363** [comment]
Thank you very much for your kind response and help.
I made the following code 
```public class PdsGraphQlSchema: Schema
    {
        public PdsGraphQlSchema()
        {
            FieldNameConverter = new PascalCaseFieldNameConverter();
            Query = CommonServiceLocator.ServiceLocator.Current.GetInstance<GraphQlQueries>();
            Mutation = CommonServiceLocator.ServiceLocator.Current.GetInstance<GraphQlMutations>();
        }
    }```
here I have added `     FieldNameConverter = new PascalCaseFieldNameConverter();` but i am not getting the changes.

For `ConfigureServices` I have used following
```
services.AddGraphQL(_ =>
                {
                    _.EnableMetrics = true;
                    _.ExposeExceptions = true;
                });
services.AddSingleton<PdsGraphQlSchema>();
```
and inside `Configure` I have used following
```
app.UseGraphQL<PdsGraphQlSchema>();
app.UseGraphQLPlayground(new GraphQLPlaygroundOptions
{
	Path = "/ui/playground"
});
```
Expecting your help.

**Comment by Marsellus47** [comment]
Probably this is the reason why it doesn't work #181

**Comment by sungam3r** [comment]
@Marsellus47 Yep, indeed.
