### ISSUE TITLE
Published example template IIS 10 subscriptions listening but not showing in production env.

### ISSUE THREAD

**Issue by RaySheikh** [graphql-dotnet/server#183]
Hi, 

I have recently cloned the example template and it works great on IIS express dev environment. I published it on a win 2012 iis 10 server and everything loads. The subscriptions activate playground shows listening but when i create a mutation, nothing shows up in the subscriptions window. The only thing I changed in the template was enable SSL using HTTPS it works fine on IIS express Dev env.
Has anyone else tried publishing and run into this issue?

Thanks in advance

**Comment by Shane32** [comment]
I have had no issues publishing server applications.  Closing issue as outdated.  Please reopen if desired.
