### ISSUE TITLE
playground is loading schema directly from the baseurl, not considering the string path after first slash

### ISSUE THREAD

**Issue by pobisw** [graphql-dotnet/server#184]
playground.cshtml has the below code which sets the url for fetching the schema  in playground
```
  window.addEventListener('load', function (event) {
      GraphQLPlayground.init(document.getElementById('root'),
        {
          setTitle: true,
          endpoint: window.location.protocol + "//" + window.location.host + "@Model.GraphQLEndPoint",
          subscriptionEndpoint: (window.location.protocol === "http:" ? "ws://" : "wss://") + window.location.host + "@Model.GraphQLEndPoint",
          settings: {
            'tracing.hideTracingResponse': false
          }
        });
    })
```
This only consider the localtion.host  part, but not the url path after that 

for example if I load https://basepath/path1/path2/playground 

it will try to load schema from https://basepath/graphql 

because that is the value that comes in window.location.host

Expected Behavior :  It should load schema from 

https://basepath/path1/path2/graphql

**Comment by joemcbride** [comment]
Can you describe why you can’t just set the url of your GraphQL Endpoint to the path that you need?  It appears the changes you are making to this would make it impossible to have different root urls for those two endpoints, which is a valid scenario.

**Comment by pobisw** [comment]
@joemcbride  because we have multiple dev and int endpoints for graphql, and we have can set the graphql endpoint to only one value

**Comment by pobisw** [comment]
> Can you describe why you can’t just set the url of your GraphQL Endpoint to the path that you need? It appears the changes you are making to this would make it impossible to have different root urls for those two endpoints, which is a valid scenario.

@joemcbride  can you please reply, if the explanation answers your concern. If not please suggest what would be the better way to support multiple dev and int environment for graphql ?

**Comment by subithal** [comment]
I'm also facing the same issue.  was it resolved??

**Comment by subithal** [comment]
@sungam3r is this issue resolved?

**Comment by sungam3r** [comment]
I think no. I have no time to work on each project in GraphQL org. Now in my free time I'm busy preparing the GraphQL.NET v4. Then we will publish server v5. It is possible that some of these errors will be fixed in v5 release.

**Comment by pobisw** [comment]
I raised a PR, but nobody approved it, if someone approves it the issue
will get resolved

**Comment by sungam3r** [comment]
Every PR needs time to review.

**Comment by pobisw** [comment]
It's been a year 🙂

**Comment by sungam3r** [comment]
I know. I myself have such PRs that have not being merged for more than a year.

**Comment by pobisw** [comment]
Can we help each other in reviewing the prs 🙂

**Comment by sungam3r** [comment]
Anyone can comment in PRs. You do not need special rights for this.

**Comment by subithal** [comment]
> Anyone can comment in PRs. You do not need special rights for this.


Can you please suggest a workaround for this ?.
