### ISSUE TITLE
Is it possible to support FieldMiddleware?

### ISSUE THREAD

**Issue by diouxis** [graphql-dotnet/server#186]
I check the source code, the SetFieldMiddleware option actually doesn't do any thing.
Currently I have to do something in the Schema like below to work around it.
``` csharp
            FieldMiddlewareBuilder middware = new FieldMiddlewareBuilder();
            middware.Use(next => ctx =>
            {
                // any code here
                return next(ctx);
            });
            middware.ApplyTo(this);
```

**Comment by sungam3r** [comment]
I think `SetFieldMiddleware` will be removed soon. See graphql-dotnet/graphql-dotnet#1268
