### ISSUE TITLE
When is the next release planned?

### ISSUE THREAD

**Issue by queil** [graphql-dotnet/server#187]
Hi,

Is there any road map or at least an ETA on the next release? I can see the develop branch has a few interesting features (Authorization.AspNetCore). Thanks

**Comment by chyyran** [comment]
I'm waiting for #164 to be fixed on NuGet... It's nearly been half a year.

**Comment by pekkah** [comment]
You can use the preview releases from myget...

**Comment by pekkah** [comment]
@deefco just add the preview feed to your nuget.config file. For example see https://github.com/graphql-dotnet/server/blob/develop/nuget.config

**Comment by queil** [comment]
@pekkah much appreciated.

**Comment by deefco** [comment]
Am I missing something or do the 3.3 preview releases not contain GraphQL.Server.Authorization.AspNetCore?t

**Comment by pekkah** [comment]
@deefco it was missing from the build script. Added now.

**Comment by queil** [comment]
@deefco Did you manage to get it working by any chance?

**Comment by deefco** [comment]
> @deefco Did you manage to get it working by any chance?

We ended up building the package ourselves and hosting it on our nuget instance till the new release is out.

**Comment by pekkah** [comment]
New packages has been pushed to NuGet

**Comment by queil** [comment]
Thanks @pekkah. I managed to get Authorisation working although not without [issues](https://github.com/graphql-dotnet/server/issues/191).

**Comment by sungam3r** [comment]
All current releases are released as previews and are available on myget.org - [example](https://github.com/graphql-dotnet/server/blob/develop/nuget.config). From time to time, packages are manually transferred to nuget.org (last time it was just yesterday).
