### ISSUE TITLE
Ambiguous type GraphQLBuilderExtensions

### ISSUE THREAD

**Issue by queil** [graphql-dotnet/server#191]
Hi,

I am trying to get authorisation to work in the AspNetCore transport. (GraphQL.Server.Authorization.AspNetCore 3.3.0). 

 When trying to use the `AddGraphQLAuthorization` extension method I am getting the following error message:
```
The type 'GraphQLBuilderExtensions' exists in both 'GraphQL.Server.Core, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null' and 'GraphQL.Server.Transports.AspNetCore, Version=3.3.0.0, Culture=neutral, PublicKeyToken=null'
```

I can work that around with `extern alias` magic but that's annoying in the long term.

**Comment by sungam3r** [comment]
@queil I can not reproduce the error on develop branch. There are 3 classes named `GraphQLBuilderExtensions` (Core/Transports.AspNetCore/Authorization.AspNetCore) but they all contain methods with different names.

**Comment by queil** [comment]
@sungam3r: Hi, thanks for looking into it. I've already switched to another GraphQL implementation. If you cannot replicate the issue I think it can be closed.
