### ISSUE TITLE
Subscription transport protocol has wrong casing

### ISSUE THREAD

**Issue by cotillion** [graphql-dotnet/server#192]
It appears 3.3 broke the serialization of the transport protocol.
Even the sample project is giving:  Error: Invalid message type! 

This appears to happen because 'type' is now 'Type'
```json
{"Id":null,"Type":"connection_ack","Payload":null}
```

The structure is supposed to be:
```typescript
export interface OperationMessage {
  payload?: any;
  id?: string;
  type: string;
} 
```

I belive this was broken by #174 
The DocumentWriter appears to use the MVC JSON serialization settings.  These could perhaps be used for the Payload but not for the OperationMessage itself.

**Comment by benidi** [comment]
I have the same problem. In subscriptions-transport-ws i get errors when receiving messages.

![11-01-_2019_10-26-05](https://user-images.githubusercontent.com/16839129/51036522-a697c300-15ad-11e9-894d-a3e30259a4cd.jpg)

**Comment by Patrick-Spiegel** [comment]
@DSilence FYI

**Comment by DSilence** [comment]
Yeah, it looks like my changes broke it. Given that graphql client libraries (at least for now) are so strict about case, the case should be fixed for those messages, either via custom serializer (same as for ExecutionResult) or via serialization attributes. If the contributors don't mind, I'll be happy to provide the PR with a fix.

**Comment by pekkah** [comment]
Could you test the latest preview package?
