### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by pekkah** [graphql-dotnet/server#193]
Due to not having enough time and focusing my own efforts into [tanka-graphql](https://github.com/pekkah/tanka-graphql) I'm looking for active maintainers for this project.

So if anyone (preferably those who have committed previously to this project) is interested please reply here.

fyi @joemcbride

**Comment by benmccallum** [comment]
Hey @pekkah , I can probably help out to some extent. 

I'm currently blocked with something that's been merged into develop but not released to master/nuget.

**Comment by sungam3r** [comment]
@pekkah I have been using this library stack for quite some time in production. Now I am constantly engaged in its support and will be involved in this for the foreseeable future.

**Comment by sungam3r** [comment]
In fact, I am already supporting this project, so I am closing the issue.
