### ISSUE TITLE
app.UseWebSockets()

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/server#20]
From when I last used websockets, I believe the `app.UseWebSockets()` adds it using the "feature" collection.  So I believe `app.UseWebSockets()` can be called multiple times and it will only be added once.  So you should be able to add that to your endpoint extension so users don't have to do it themselves.

**Comment by pekkah** [comment]
That would make the `app.UseGraphQLEndPoint<ChatSchema>("/graphql")` depend on the WebSockets. Currently it does not require it if you just want to use it for HTTP requests (`services.AddGraphQLHttpTransport<ChatSchema>()`).

**Comment by joemcbride** [comment]
Gotcha, I see how you have that setup now.

Not related to this, though was there a reason you went with `Schema` vs. `ISchema`?

**Comment by pekkah** [comment]
Nope. Probably just missed the whole interface.
