### ISSUE TITLE
Implement Keep-Alive

### ISSUE THREAD

**Issue by Clarksons-FortApp-TeamMember** [graphql-dotnet/server#200]
Implementation to send Keep-Alive Messages appears to be missing despite there being a suitable [MessageType](https://github.com/graphql-dotnet/server/blob/2bc76b4/src/Transports.Subscriptions.Abstractions/MessageType.cs#L44).

The `GQL_CONNECTION_KEEP_ALIVE` is unhandled in https://github.com/graphql-dotnet/server/blob/ec85aab/src/Transports.Subscriptions.Abstractions/ProtocolMessageListener.cs#L29-

A reference implementation can be found here: https://github.com/apollographql/subscriptions-transport-ws/blob/7482425bb27139d99f45c88ac46c7223c210fbf9/src/server.ts#L273

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Ditto this.
The features that this would provide:

* Allow application authors to put in-place measures to ensure that connections don't get dropped by the routers in network setups with automatic NAT
* in applications where it is important to inform the user of potential lack connection with live data, it allow app authors detect a severed connection quicker than the notoriously long OS defaults ([1](https://bugs.chromium.org/p/chromium/issues/detail?id=76358), [2](https://bugs.chromium.org/p/chromium/issues/detail?id=197841)).

**Comment by kamnyborg** [comment]
I'm surprised this isn't brought up more often? The only work-around is to have the client reestablish the connection at the same frequency as the keep-alive would have?
