### ISSUE TITLE
graphql-dotnet/server PlaygroundUI always spamming IntrospectionQuery to controller

### ISSUE THREAD

**Issue by Mysq** [graphql-dotnet/server#201]
As the title says the Playground UI is constantly spamming requests to graphql controller, like one every second or so and it just clutter the logs, making it hard to understand where is the actual problem also if you execute query and it errors, the output is overwritten because of these requests, for some reason.  
It started happening in 3.3 release. 
Could we have some option to disable the constant spamming and make the schema retrieval a one time thing? Or maybe do the calls on some actual onChange event? I couldn't figure out where the call starts.

**Comment by marticrespi** [comment]
The same here, using 3.4.0. It's annoying because you can't see the results when it throws an error, when the query was ok it still requesting the introspection but it doesn't remove the results.

**Comment by pekkah** [comment]
I suspect the execution to fail and playground by default tries again

**Comment by Mysq** [comment]
The execution is successful, it's the "schema.polling" , the interval is insane, way too spammy, the 2000ms. 
You can change it in the playground setting in the web browser, but it would be really awesome, to have some setting solution in code, so it's for all clients, not just yourself.

**Comment by Mysq** [comment]
https://github.com/graphql-dotnet/server/pull/198 this would solve this issue.

**Comment by sungam3r** [comment]
As @Mysq said now you can set playground settings when configuring middleware pipeline.
