### ISSUE TITLE
.NET 4.7.1 & 4.7.2 Support

### ISSUE THREAD

**Issue by kenrim626** [graphql-dotnet/server#202]
Hi, im currently developing a template for our graphql services. It is working perfectly fine with .NET 4.7, but as soon as I switch to 4.7.1 or 4.7.2 im getting only **ERR_CONNECTION_RESET**.

Anyone else got this issue?

**Comment by sungam3r** [comment]
Can you provide some logs?

**Comment by kenrim626** [comment]
I no longer work on that particular project - so no, I can not. It seems that nobody else got this issue or it is fixed already, so I guess I will close this issue as well.
