### ISSUE TITLE
Is "EnableMetrics = true" work?

### ISSUE THREAD

**Issue by kefengwei** [graphql-dotnet/server#207]
I had set the `EnableMetrics = true`, but the there have warning in playground:
![image](https://user-images.githubusercontent.com/4326865/53713539-2e9b9a00-3e86-11e9-9edb-6236afb1ac78.png)
  Is there any something i missed?

**Comment by joemcbride** [comment]
See the docs on using Apollo tracing.  
https://graphql-dotnet.github.io/docs/getting-started/metrics

**Comment by kefengwei** [comment]
I read this document.  I mean  although there have  EnableMetrics in config, but why not implement in middleware?  it' confused! Also the FiledMiddleware!

**Comment by RehanSaeed** [comment]
Take a look at the [ASP.NET GraphQL Boxed](https://github.com/Dotnet-Boxed/Templates/blob/master/Docs/GraphQL.md) project template, for an example of how to implement this.

**Comment by kefengwei** [comment]
@RehanSaeed  Thanks.It's work! 
  But I still curious why not implement these function in the default Middleware.
