### ISSUE TITLE
Need new prerelease packages for 3.0.0 prerelease version of GraphQL

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#217]
See [#1058](https://github.com/graphql-dotnet/graphql-dotnet/pull/1058)

**Comment by rose-a** [comment]
Im running into this issue too! Any news on when that pre-release package will be available?

**Comment by pekkah** [comment]
Latest previews have been always available from myget

**Comment by sungam3r** [comment]
In order for the package to appear on myget, we do not need to merge the code into the master? Will it be enough to make PR with prerelease versions of dependencies?

**Comment by sungam3r** [comment]
The problem is solved.
