### ISSUE TITLE
GraphQL Playground autocomplete/intelliSense issue.

### ISSUE THREAD

**Issue by Askar938** [graphql-dotnet/server#225]
Hi!

I am using GraphQLPlayground as middleware in my ASP.NET core application.
```app.UseGraphQLPlayground(new GraphQLPlaygroundOptions());```

The browsers I am using are the newest Google Chrome and Firefox.

When I initially try to press `Ctrl + Space` in the "Variables" section, GraphQLPlayground does not give me any autocomplete suggestions.

![No autocomplete in the variables section initially](https://i.imgur.com/YNMZbz9.jpg)

If I go to the GraphQL query (section on top left) first and then try `Ctrl + Space` to autocomplete, it will suggest a list of possible types. And if I then go back to the "Variables" section, I am able to use `Ctrl + Space` to autocomplete there as well.

The functionality is there, but it does not trigger in the "Variables" section unless I first go to the GraphQL query and try autocompletion in there.

Can this be fixed?

**Comment by sungam3r** [comment]
I think it will be better to ask this question in [GraphQL Playground repo](https://github.com/prisma-labs/graphql-playground). I see some issues regarding autocomplete features:

https://github.com/prisma-labs/graphql-playground/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+autocomplete

This project actually uses a minimal [sample file](https://github.com/graphql-dotnet/server/blob/develop/src/Ui.Playground/Internal/playground.cshtml) to integrate with GraphQL Playground. All the rest work is not here.
