### ISSUE TITLE
IDataLoaderContextAccessor.Context is null

### ISSUE THREAD

**Issue by jamiewinder** [graphql-dotnet/server#226]
I'm trying to use the data loader functionality, and while my `IDataLoaderContextAccessor` is successfully injected into my query class, the `Context` property of it is `null`.

Before I started using `graphql-dotnet/server`, there were two steps needed to get the data loader to work; the ones described here:
https://graphql-dotnet.github.io/docs/guides/dataloader#setup

I'm calling `.UseDataLoader()` which [I can see](https://github.com/graphql-dotnet/server/blob/develop/src/Core/GraphQLBuilderExtensions.cs#L19) adds the services for IDataLoaderContextAccessor and IDocumentExecutionListener).

However, what I don't see happening is step # 3 of the setup; adding the listener:

```c#
var listener = Services.GetRequiredService<DataLoaderDocumentListener>();
var executer = new DocumentExecuter();
var result = executer.ExecuteAsync(opts => {
	...
	opts.Listeners.Add(listener);
});
```
I assume this is the issue (correct me if I'm wrong!). If so, how I add this?

If I'm barking up the wrong tree, please let me know.

**Comment by joemcbride** [comment]
The listener _should_ be getting added in the `DefaultGraphQLExecuter`:

https://github.com/graphql-dotnet/server/blob/b85af10782637be9569e7ed63d1ee9fff71e4f76/src/Core/Internal/DefaultGraphQLExecuter.cs#L59-L62

You could inherit from that class and override the `GetOptions` method to confirm.

**Comment by jamiewinder** [comment]
Thanks for your reply. I see that's probably where it ought to get added, but that collection of listeners appears to be passed into the constructor and as far as I can see the `AddGraphQl` method that specifies it doesn't add any. 

I think I'm missing something somewhere. Should I be creating and registering my own `DefaultGraphQLExecuter`?

**Comment by johnrutherford** [comment]
This minimal configuration will register everything you need:

``` csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddSingleton<YourSchema>();

    // Add necessary GraphQL services
    services.AddGraphQL()
        .AddDataLoader(); // Add required services for DataLoader support
}

public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseGraphQL<YourSchema>("/graphql");
}
```

Where are you trying to access the `Context` property on the `IDataLoaderContextAccessor`? You must get the context within a resolver delegate. The context is created per execution so if you're trying to access it outside of the scope of an execution, it will be null.

**Comment by jamiewinder** [comment]
I'm injecting it into my Type classes' constructor, and then accessing `.Context` within the `Field().Resolve()` callbacks. For example:

```c#
    public class MyObjectType : ObjectGraphType<MyObjectModel>
    {
        // Constructors
        public MyObjectType (
            IDataLoaderContextAccessor accessor)
        {
            this.Field<MyOtherObjectType>>()
                .Name("other")
                .Resolve(context =>
                {
                    // accessor.Context is null on the following line
                    var loader = accessor.Context.GetOrAddBatchLoader(/* ... */);
                });
        }
    }
```

**Comment by jamiewinder** [comment]
I'm none the wiser, but I started from scratch and now it appears to work!

The only thing I can think that may have done it was reverting the GraphQL package from the prerelease back to 2.4.0 (which I was doing to get around the bug of the GuidGraphType not being recognized).

Anyway, thanks for your help.
