### ISSUE TITLE
Set-Cookie not set

### ISSUE THREAD

**Issue by shoe-diamente** [graphql-dotnet/server#228]
I have a mutation which accesses the `HttpContext` from `IHttpContextAccessor` and sets the cookies in the response via:

```c#
 _httpContext.HttpContext.Response.Cookies.Append("access_token", "abc", new CookieOptions()
{
    Domain = "example.com",
    Secure = false,
    HttpOnly = false,
    IsEssential = true,
});
```
 This same exact code, put in a .NET Core controller works.
When put in a GraphQL mutation it doesn't seem to expose the `Set-Cookie` header in the response.

My setup code is the following:

```c#
services.AddGraphQL(options =>
{
    options.ExposeExceptions = false;
})
.AddDataLoader()
.AddUserContextBuilder(httpContext => 
    httpContext.RequestServices.GetService<IMediator>());
```

What could be the cause of this?

**Comment by sungam3r** [comment]
@shoe-diamente I conducted an experiment. I copied your code to one of my resolvers (.net core 2.2). In the posponse I found the required header `Set-Cookie`. Is this problem still actual?

**Comment by shoe-diamente** [comment]
I started using `graphql-dotnet/conventions` and moved away from `graphl-dotnet/server`. In hindsight I don't think it was due to `graphql-dotnet`, but it's just a feeling. I'll close it.
