### ISSUE TITLE
Filter subscription response

### ISSUE THREAD

**Issue by wojcikiewiczm** [graphql-dotnet/server#230]
Is it possible to respond via subscription only to a specific user or users? In apollo there is withFilter function. Is it possible to do something like that in here? Thanks :)

**Comment by nodsod** [comment]
This sample filters on user id as an example

https://github.com/graphql-dotnet/server/tree/develop/samples/Samples.Schemas.Chat

**Comment by Shane32** [comment]
Closing as answered
