### ISSUE TITLE
Azure Functions Support

### ISSUE THREAD

**Issue by StefanSchoof** [graphql-dotnet/server#232]
## Summary

Have a easy and documented way how to use graphql-dotnet in a Azure Function.

### Basic example

There is a blog post at https://www.tpeczek.com/2019/05/serverless-graphql-with-azure-functions.html with code at https://github.com/tpeczek/Demo.Azure.Functions.GraphQL/blob/master/Demo.Azure.Functions.GraphQL/Infrastructure/GraphQLExecuterExtensions.cs how to wire a azure function with graphql-dotnet. 

Having a documentation on official place and maybe the glue code in a nuget package would be great.

### Motivation

Azure Functions are a cheap way to set up a scalable service, with a growing developer base. Having a single source of the wrapping code from the project itself would make it easier to use and put it to single place to optimize and add features to the code.

**Comment by sungam3r** [comment]
You can make PR to add:
1.  A new sample about azure functions to https://github.com/graphql-dotnet/server/tree/develop/samples
2. A new section in README with aforementioned links.

**Comment by StefanSchoof** [comment]
@tpeczek Is it fine for you if I create a PR to add your https://github.com/tpeczek/Demo.Azure.Functions.GraphQL sample to the official sample projects?

**Comment by tpeczek** [comment]
@StefanSchoof I don't see any issue with this.
