### ISSUE TITLE
Working with replaced request body stream

### ISSUE THREAD

**Issue by Donnatello** [graphql-dotnet/server#236]
In Asp Net Core `HttpRequest.Body` has public setter and it makes it possible to replace original stream to another. The standard way to do this is to use the extension methods for `HttpRequest` `EnableBuffering` or `EnableRewind`.
Except for #234, in this situation the position in the stream may be different from 0 and reading the content is not correct now.
In this case should:
1. Leave opened stream after reading (for another middleware)
2. Set stream position to 0 (if it possible)

**Comment by sungam3r** [comment]
Resolved
