### ISSUE TITLE
Subscriptions doesn't work as expected with Apollo client

### ISSUE THREAD

**Issue by trailblazer2006** [graphql-dotnet/server#242]
Hi. I tried to use GraphQL.NET Server with Apollo client and have discovered a bug in the subscriptions. When the subscription is activated, it returns last message, even if the operation was long time ago. This ruins the idea of the Apollo Query component method "subscribeToMore", because the component starts adding the same row endlessly. Of course, I can change a parameter of the ReplaySubject from buffer size to window in a hope that all server processes are completed before this time and the  message will be delivered to a client and the client won't have enough to time to obtain the results of the subscription twice, but it looks like a trick, not a solution.

**Comment by joemcbride** [comment]
That is expected behavior when your using a `ReplaySubject<T>` (it is purposefully built that way if you read Microsoft's documentation on it).  You should be able to just use `Subject<T>` instead.

**Comment by trailblazer2006** [comment]
Unfortunately this didn't help. I changed `ReplaySubject<Message>(1)` to `Subject<Messsage>()` in the Chart class and messages stopped being added endlessly. But on first message added after subscription has been activated the Apollo client recieves two messages. On second message it recieves four and so on.

**Comment by trailblazer2006** [comment]
Sorry, it's my bad. Subscription with `Subject<Messsage>()` works fine, there was a bug in my client application.
