### ISSUE TITLE
Why do subscriptions work as Singletons but not as Scoped?

### ISSUE THREAD

**Issue by calebsmithdev** [graphql-dotnet/server#245]
It took a long time to figure out what the answer was.. but I needed to make an interface and class that were marked as a singleton, versus using the scoped repositories that I have now.

My question is - why does a singleton work with the subscriptions but not a scoped interface? I need to use scoped for my DBContext. I've decided its probably best to have the subscription related stuff in it's own class anyway, but I'd like a little bit more education around this just for the future.

**Comment by denis-troller** [comment]
I had the same question.

As far as I understand it, there is no propagation of RequestServices on subscription, which precludes using scoped services. The code actually has a comment stating ```find a better way to handle services```.

Now, if you think about it, there is probably no good way of handling subscriptions in a scoped context. Subscriptions are long-lived objects, that will continue posting data long after the current request (the subscription creation) is finished.

I understand that you might need to pull data out of your database to create the subscription though, which is where it will break down.
but provided you do not need that, then the subscription-related services should probably be singleton...

**Comment by Shane32** [comment]
I don't know how subscriptions mesh with Asp.Net Core, but there's probably some implementation detail that holds the key to the answer -- either it is possible, or it isn't.

However, you can create your own scope inside your field resolver to use scoped services.  Something like this:

```cs
public MyGraphType(IServiceProvider rootServiceProvder) {

    Field("MyField", resolve: context => {
        using var scope = rootServiceProvider.CreateScope();
        var serivce = scope.ServiceProvider.GetRequiredService<MyService>();
        return service.MyField();
    });

}
```

You can also define a "ScopedFieldResolver" to automatically create a scope during execution of the field.  You can see a sample of this in PR #1571.  If `RequestServices` is null, then you'll need to modify it just a bit so that it uses the `IServiceProvider` passed to the constructor of the graph type in order to create the scope from.

**Comment by sungam3r** [comment]
I can add to @Shane32 answer that there have been a lot of questions and problems with subscriptions for a long time. This is a real tangle of dependencies and code that is not easy to understand. One of my dreams is to clean up this code. I have been thinking about these plans for a very long time. This, of course, takes time, effort and a lot of experimentation. Holidays are always an opportunity to work on it. Holidays are coming soon.

**Comment by Shane32** [comment]
Scoped services for subscriptions and within subscriptions are supported in v7, and are covered in the readme (after #856 is merged).

See: https://github.com/graphql-dotnet/server/blob/d670f785f29cb03a2130c0d2eb86b3add74a5adb/README.md#service-scope

Keep in mind all of the typical restrictions with scoped services noted here: https://graphql-dotnet.github.io/docs/getting-started/dependency-injection#scoped-services-with-a-singleton-schema-lifetime
