### ISSUE TITLE
ConfigureAwait seems to be applied inconsistently

### ISSUE THREAD

**Issue by gbiellem** [graphql-dotnet/server#251]
I noticed the that ConfigureAwait seems to be inconsistently applied throughout this codebase.
Since fixing this would touch a lot of files  I'd be curious if you'd like one big PR or several small ones

**Comment by sungam3r** [comment]
Can you explain what type of inconsistecy are you talking about?

**Comment by gbiellem** [comment]
@sungam3r Sure. 

For all await calls in  libraries it's generally best practice is  to configure the `await` call by adding `ConfigureAwait(false);`

For ref:  https://markheath.net/post/async-antipatterns and https://blog.stephencleary.com/2012/02/async-and-await.html

I did a quick search over the code base on GraphQL.Net  and GraphQL.Net Server

For GraphQL.net there are 202 `await` statements,  28 of which have been decorated with `ConfigureAwait(false);`

For GraphQL.Net Server there are 117 `await` statements and 5 of which have been decorated with `ConfigureAwait(false);`

Since undecorated awaits will default to `ConfigureAwait(true)` it's inconsistent.

**Comment by sungam3r** [comment]
I didn’t think there were so many of them. Is it without tests? In the tests there is little sense in changing.You are welcome to make a PR.

**Comment by gbiellem** [comment]
FYI... @SimonCropp  has already done the same in GraphQL.Net

**Comment by SimonCropp** [comment]
here is the one in graphql .net  https://github.com/graphql-dotnet/graphql-dotnet/pull/1263

**Comment by sungam3r** [comment]
Closed via #253
