### ISSUE TITLE
WebSocket transport throwing after browser has closed

### ISSUE THREAD

**Issue by gbiellem** [graphql-dotnet/server#252]
We noticed that the WebSockets middleware throws with the following exception some time after the user has closes the browser:

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task
or accessing its Exception property. As a result, the unobserved exception was rethrown by the
finalizer thread.  (The remote party closed the WebSocket connection without completing the close handshake.) 
```

Looking at the code it doesn't appear to follow the [Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-2.2#accept-websocket-requests)  recommendation to make sure you keep the middleware pipeline running. The doco states:  **Do this by using a TaskCompletionSource<TResult>. Pass the TaskCompletionSource to your background service and have it call TrySetResult when you finish with the WebSocket.** 

I am assuming this is the issue.

**Comment by Shane32** [comment]
This should be solved in v7.  Please re-open if you continue to have issues with this in v7.
