### ISSUE TITLE
ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time

### ISSUE THREAD

**Issue by samyhrer** [graphql-dotnet/server#26]
This is just a sneaking suspicion, but I'd loved to get a discussion going so I might be able to track down the errors I'm experiencing using this library.
When we saturate the Web Socket connection with a lot of outbound traffic we sometimes get this exception:

System.InvalidOperationException: TODO, RESX: net_Websockets_AlreadyOneOutstandingOperation;

This is although the wrong Exception Message, currently beeing fixed in dotnet core and is tracked in https://github.com/aspnet/WebSockets/issues/207

The actual Exception Message is "There is already one outstanding 'SendAsync' call for this WebSocket instance. ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time."

When this happens the Web Socket connection is not torn down correctly, but still open between the Client and Server. But no data is no longer coming through as the server side WebSocket client is in a bad state.

As stated in the WebSocket SendAsync-method documentation https://msdn.microsoft.com/en-us/library/system.net.websockets.websocket.sendasync(v=vs.110).aspx
"This operation will not block. The returned Task object will complete after the data has been sent on the WebSocket. Exactly one send and one receive is supported on each WebSocket object in parallel."

So why would this happen?

I suspect the culprit might be in SubscriptionHandle.cs
`
public void OnNext(object value)
        {
            var json = _documentWriter.Write(value);
            _messageWriter.WriteMessageAsync(new OperationMessage
            {
                Id = Op.Id,
                Type = MessageTypes.GQL_DATA,
                Payload = JObject.Parse(json)
            }).GetAwaiter().GetResult();
        }
` where I believe you shortcut the async nature of WriteMessageAsync by calling GetAwaiter().GetResult(), which would allow multiple outstanding operations at a time.

I would love to contribute a fix to this, but I am currently a bit stuck. So any insight would be appreciated.

**Comment by pekkah** [comment]
Could you try it with the latest version. I did some changes according to some stackoverflow articles. There seems to be bit of issues with mixing async and observable worlds together. 
This is the change I did to how `SubscriptionHandle` subscribes to the stream: https://github.com/graphql-dotnet/server/commit/3e7fd1e048ffeec5f11f576c8c17c117452e9814

**Comment by samyhrer** [comment]
Thanks a lot for a swift reply (and a potential fix :+1:  ). 
My college will perform extensive testing tomorrow, but I won't personally be able to provide any additional feedback on this issue until Monday. Finger's crossed.

**Comment by samyhrer** [comment]
Hi again.

Unfortunately the issue persisted. We still see the same exception occur and brings the WebSocket client  into the Aborted-state. The Exception itself is currently silently handled in OnError in SubscriptionHandle.cs.

We created a small demo app that demonstrate the issue. It is available here:
https://github.com/samyhrer/graphql-sub-test

The demo project contains the graphql-endpoint, as well as a Client Application that initiates multiple subscriptions (Using the Apollo Client)

What we try to simulate is a client that creates multiple subscriptions to the grapql-layer. Each subscription gets connected to an observable. Each of the observables are updated with a new value every 500 milliseconds where we simulate the parallell nature of our datasources using Parallel.ForEach: 
`
           this._timer = Observable.Interval(TimeSpan.FromMilliseconds(500)).AsObservable();
            this._timer.Subscribe(x =>
            {
                Parallel.ForEach<ReplaySubject<DomainValue>>(this._subscriptions, (sub) =>
                {
                    sub.OnNext(new DomainValue
                    {
                        Name = "test",
                        Value = x.ToString()                        
                    });
                });
            }); 
`

The demo should crash pretty quickly and the server side will stop pushing data to the client.

So why does it happen?

The current prime suspect is how the set of SubscriptionHandlers are managed. We suspect the lack of coordination between these can cause multiple write operations at once.

Would it be better that we, for each Subscription, only managed one SubscriptionHandler (and that this Subscriptionhandle would have functionality of adding and removing streams?) 
Instead of maintaining a list of multiple SubscriptionHandlers which could get in each other's way?

**Comment by samyhrer** [comment]
```c#
            Monitor.Enter(_socket);
            try
            {
                return _socket.SendAsync(messageSegment, WebSocketMessageType.Text, true, CancellationToken.None);                
            }            
            finally
            {
                Monitor.Exit(_socket);
            }  
```
Adding a Monitor on the _socket-instance does seems to fix the problem illustrated in the demo.
But not sure about if it has any other implications as of yet. Just wanted to give an update.

**Comment by pekkah** [comment]
Yes I tested also with two phased locking which fixed the issue. I'm currently working on an more long term fix by using queues for reading and writing but due to vacation cannot provide an estimate when I get it done.

**Comment by pekkah** [comment]
Here's a quick write queue implementation https://github.com/graphql-dotnet/server/pull/29. Didn't do any heavy testing on it yet.

**Comment by pekkah** [comment]
Is this still an issue with latest?

**Comment by samyhrer** [comment]
We haven't had the chance to test the early queue implementation as of yet. We moved on with the Monitor-solution as it solved our immediate needs. But we will in the coming two weeks try out the queue-implementation as well. Will provide feedback on our findings, both positive or negative.

**Comment by pekkah** [comment]
Closing this for now. Please reopen if you still hit the same issue.
