### ISSUE TITLE
new project

### ISSUE THREAD

**Issue by kassanj** [graphql-dotnet/server#266]
Hey Fellow GraphQL-ers,
We're looking to improve and create a new open source library/resource for the amazing technology. :) 
We wanted to know the latest issues. How we could help or improve the ecosystem? 
Yeah! Lets us know... we are given the time and resources... we want to make everyone's lives easier....  all ideas are welcomed!

**Comment by joemcbride** [comment]
This post appears to be not about improving THIS implementation but a different one?  If that is the case, this is not the appropriate venue for your inquiry.  If I am mis-interpreting your post, please provide more information and we can re-open.
