### ISSUE TITLE
Plans for stable release?

### ISSUE THREAD

**Issue by msheldon83** [graphql-dotnet/server#268]
I see that you are revving on an alpha release that implements some newer features for the apollo client (such as request batching).   Do you have a goal for a stable release at some point in the future?  

Thanks

**Comment by sungam3r** [comment]
Relates to graphql-dotnet/graphql-dotnet#1321

I think the reason is the same - actual documentation.

**Comment by sungam3r** [comment]
Closed as duplicate of graphql-dotnet/graphql-dotnet#1321
