### ISSUE TITLE
Subscriptions does not work in WebSockets 3.5.0

### ISSUE THREAD

**Issue by mehtanilay10** [graphql-dotnet/server#272]
I am using **ASP.Net core 3** for GraphQL. 
For this, I just need to use WebSockets 3.5.0 (as it only supports .Net Core 3).
In which subscription does not work properly. For similar code in WebSockets 3.4.0 it works. 
I guess issues is in `System.Reactive`, Version 3.4.0 has reference of 3.1.1, where 3.5.0 has 4.1.6 (Due to .Net Standard reference).

You can find entire example in this Repo: https://github.com/mehtanilay10/GraphQLDemo
Here is some snippet of my demo.

### Startup.cs
```
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.AddTransient<IOrderStatusEventService, OrderStatusEventService>();
    services.AddSingleton<PizzaOrderSubscription>();
    ...
    services.AddGraphQL()
        .AddWebSockets()
        .AddDataLoader()
        .AddGraphTypes(typeof(PizzaOrderSchema));
}
```
### PizzaOrderSubscription
```
public class PizzaOrderSubscription : ObjectGraphType
{
    private readonly IOrderStatusEventService _orderStatusEventService;

    public PizzaOrderSubscription(IOrderStatusEventService orderStatusEventService)
    {
        _orderStatusEventService = orderStatusEventService;
        Name = nameof(PizzaOrderSubscription);

        AddField(new EventStreamFieldType
        {
            Name = "orderCreated",
            Type = typeof(OrderStatusEventType),
            Resolver = new FuncFieldResolver<OrderStatusEvent>(ResolverHandler),
            Subscriber = new EventStreamResolver<OrderStatusEvent>(OrderCreateHandler)
        });

        AddField(new EventStreamFieldType
        {
            Name = "statusUpdate",
            Arguments = new QueryArguments(new QueryArgument<NonNullGraphType<OrderStatusEnumType>> { Name = "status" }),
            Type = typeof(OrderStatusEventType),
            Resolver = new FuncFieldResolver<OrderStatusEvent>(ResolverHandler),
            Subscriber = new EventStreamResolver<OrderStatusEvent>(StatusUpdateHandler)
        });
    }

    private OrderStatusEvent ResolverHandler(ResolveFieldContext context)
    {
        return context.Source as OrderStatusEvent;
    }

    private IObservable<OrderStatusEvent> OrderCreateHandler(ResolveEventStreamContext context)
    {
        var events = _orderStatusEventService.OnCreateObservable();
        return events.Where(x => x.OrderStatus == OrderStatus.Created);
    }

    private IObservable<OrderStatusEvent> StatusUpdateHandler(ResolveEventStreamContext context)
    {
        OrderStatus status = context.GetArgument<OrderStatus>("status");
        var events = _orderStatusEventService.OnCreateObservable();
        return events.Where(x => x.OrderStatus == status);
    }
}
```
### OrderStatusEventService
```
#region Inteface

public interface IOrderStatusEventService
{
    void CreateUserEvent(OrderStatusEvent orderEvent);
    IObservable<OrderStatusEvent> OnStatusUpdateObservable();
    void StatusUpdateEvent(OrderStatusEvent orderEvent);
    IObservable<OrderStatusEvent> OnCreateObservable();
}

#endregion

public class OrderStatusEventService : IOrderStatusEventService
{
    #region Status Update

    private readonly ISubject<OrderStatusEvent> _onStatusUpdateSubject = new ReplaySubject<OrderStatusEvent>();
    public void CreateUserEvent(OrderStatusEvent orderEvent) => _onStatusUpdateSubject.OnNext(orderEvent);
    public IObservable<OrderStatusEvent> OnCreateObservable() => _onStatusUpdateSubject.AsObservable();

    #endregion

    #region Create Event

    private readonly ISubject<OrderStatusEvent> _onCreateSubject = new ReplaySubject<OrderStatusEvent>();
    public void StatusUpdateEvent(OrderStatusEvent orderEvent) => _onCreateSubject.OnNext(orderEvent);
    public IObservable<OrderStatusEvent> OnStatusUpdateObservable() => _onCreateSubject.AsObservable();

    #endregion
}
```
Can you pls looking into this issue.
Thanks

**Comment by sungam3r** [comment]
> In which subscription does not work properly

What error do you have?

**Comment by sungam3r** [comment]
> where 3.5.0 has 4.1.6 (Due to .Net Standard reference)

I do not quite understand you - https://www.nuget.org/packages/GraphQL.Server.Transports.WebSockets/3.5.0-alpha0027 has dependency from 4.1.5

**Comment by mehtanilay10** [comment]
1] It does not execute code written in Resolver parameter of AddField()
2] WebSocker v3.5.0 required System. Reactive v4.1.6 in WebSocket v3.4.0 its different. Reactive v4.1.6 is design for dotnet core 3, where prior version does not supported it.

**Comment by sungam3r** [comment]
Let's finally decide on the dependency versions in question. GraphQL.Server.Transports.WebSockets requires System.Reactive v4.1.5:
![изображение](https://user-images.githubusercontent.com/21261007/66271868-8ca0bd80-e86b-11e9-904b-254d4f20499f.png)

**Comment by mehtanilay10** [comment]
Hi @sungam3r ,
I am not sure Reactive library is the root cause for issue. I just guess.
I have checked my project, It has dependancy of 4.1.6 (Maybe due to GraphQL 3.0.0-preview-1268)

![image](https://user-images.githubusercontent.com/5275614/66324354-e1633780-e942-11e9-81a4-178935f80043.png)

Is this working proper in your example with v3.5.0?

**Comment by sungam3r** [comment]
You see so called _unified dependency tree_ in solution explorer. This means that the versions of all the dependencies are shown as they were calculated. Perhaps some other component in your application refers to a newer version of the `System.Reactive` package. Try to add `System.Rective` package 4.1.5 dependency explicitly (dependency overriding) to the root of the project and see if this fixes the error.

**Comment by mehtanilay10** [comment]
Yes, my other project uses a different version of Reactive package. 
Now I have aligned version, but still no luck.

**Comment by duhowise** [comment]
I have the same issue here; Subscribers are not notified when an observed mutation occurs

**Comment by Shane32** [comment]
With GraphQL.NET Server v7, there is no dependency on System.Reactive; you may use whatever version suits your needs.  The only dependencies are the framework itself -- either the newest revision of ASP.NET Core 2.1 (on top of .NET Core 2.1 or .NET Framework 4.8), or the ASP.NET Core 3.1+ framework.

Please re-open if there are further issues along these lines.
