### ISSUE TITLE
Support for Playground in Azure Functions

### ISSUE THREAD

**Issue by NicolasREY69330** [graphql-dotnet/server#273]
Hi,

We successfully implemented GraphQL in an Azure Functions using **graphql-dotnet** and [https://github.com/graphql-dotnet/graphql-dotnet/issues/1209](https://github.com/graphql-dotnet/graphql-dotnet/issues/1209).

The only missing point is to use Playground within the Azure Function, considering there isn't any 
`Configure(IApplicationBuilder app)` method, we can't use the classic `app.UseGraphQLPlayground(new GraphQLPlaygroundOptions());`

Any solution to bypass this ?

Thank you very much for this awesome lib!

**Comment by sungam3r** [comment]
Relates to #232

**Comment by sungam3r** [comment]
If you look inside the Playground package, you will see that it simply returns an [HTML page](https://github.com/graphql-dotnet/server/blob/develop/src/Ui.Playground/Internal/playground.cshtml) from resources after making several variable substitutions. This is an elementary job. You can copy this code to yourself.

**Comment by NicolasREY69330** [comment]
Yes you were right, incredibly easy. It works perfectly
Thanks

**Comment by lundmikkel** [comment]
I'm not sure I get this. If this is super easy, why not show what you need to do to make it work with Functions, or even better, make an extension method similar to what exists? I'm at least having problems figuring out what to do based on the descriptions found here.

**Comment by sungam3r** [comment]
Extension method for what object?

**Comment by lundmikkel** [comment]
Well, the closest I can think of is probably `IFunctionsHostBuilder` which you can get in a startup class inheriting from `FunctionsStartup`, but I honestly don't know if that makes sense.

What I'm trying to say is that @NicolasREY69330 obviously understood how you should add the playground when using functions, but there isn't really any explanation of what he figured out. I, at least, don't seem to understand it. So what does it take to get a playground working with an Azure Functions project like [this one](https://github.com/graphql-dotnet/examples/tree/master/src/AzureFunctions)?

**Comment by NicolasReyDotNet** [comment]
Well I followed this link to host GraphQL in a Azure Functions :
[](https://www.tpeczek.com/2019/05/serverless-graphql-with-azure-functions.html)

Because of the async IO en V3 I need to use the following parameter in local.settings.json :
`"FUNCTIONS_V2_COMPATIBILITY_MODE": true`
**Is there any best solution ?** 

Then after that I created the following class to render the GraphQL view, it's pointing on my GraphQL endoint (/api/graphql) : 
```
    public static class PlaygroundPageModel
    {
        public static string RenderString(ExecutionContext context)
        {
            var stream = new StreamReader("playground.cshtml", Encoding.UTF8);
            var builder = new StringBuilder(stream.ReadToEnd());

            builder.Replace("@Model.GraphQLEndPoint", "/api/graphql");
            return builder.ToString();
        }

        public static Stream RenderSteam(ExecutionContext context)
        {
            string path = Path.Combine(context.FunctionAppDirectory, "playground.cshtml");
            if (!File.Exists(path))
            {
                string home = Environment.GetEnvironmentVariable("HOME");
                path = Path.Combine(home, "site", "wwwroot");
            }

            var stream = new StreamReader(path, Encoding.UTF8);
            var builder = new StringBuilder(stream.ReadToEnd());

            builder.Replace("@Model.GraphQLEndPoint", "/api/graphql");

            byte[] byteArray = Encoding.ASCII.GetBytes(builder.ToString());
            return new MemoryStream(byteArray);
        }
        
    }
```

I also created a static **playground.cshtml** file containing variable inside :
```
<!DOCTYPE html>
<html>
<head>
  <meta charset=utf-8 />
  <meta name="viewport" content="user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, minimal-ui">
  <title>Graphcool Playground</title>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/graphql-playground-react/build/static/css/index.css" />
  <link rel="shortcut icon" href="//cdn.jsdelivr.net/npm/graphql-playground-react/build/favicon.png" />
  <script src="//cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/middleware.js"></script>
</head>
<body>
  <div id="root">
    <style>
      body {
        background-color: rgb(23,42,58);
        font-family: Open Sans,sans-serif;
        height: 90vh;
      }
      #root {
        height: 100%;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: center;
      }
      .loading {
        font-size: 32px;
        font-weight: 200;
        color: rgba(255,255,255,.6);
        margin-left: 20px;
      }
      img {
        width: 78px;
        height: 78px;
      }
      .title {
        font-weight: 400;
      }
    </style>
    <img src='//cdn.jsdelivr.net/npm/graphql-playground-react/build/logo.png' alt=''>
    <div class="loading">
      Loading <span class="title">GraphQL Playground</span>
    </div>
  </div>
  <script>
    window.addEventListener('load', function (event) {
      GraphQLPlayground.init(document.getElementById('root'),
        {
          setTitle: true,
          endpoint: window.location.protocol + "//" + window.location.host + "@Model.GraphQLEndPoint",
            subscriptionEndpoint: (window.location.protocol === "http:" ? "ws://" : "wss://") + window.location.host + "@Model.GraphQLEndPoint",
              settings: {'schema.polling.enable': false}
        });
    })
  </script>
</body>
</html>
```
The Graphql entry point :
   ```
     [FunctionName("GraphQl")]
        public async Task<IActionResult> Run(
            [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = "graphql")] HttpRequest req, ILogger logger)
        {
            try
            {
                ExecutionResult executionResult = await _graphQLExecuter.ExecuteAsync(req);

                if (executionResult.Errors != null)
                    logger.LogError("GraphQL execution error(s): {Errors}", executionResult.Errors);
                
                return new GraphQLExecutionResult(executionResult);
            }
            catch (Exception ex)
            {
                return new BadRequestObjectResult(new { message = ex.Message });
            }
        }
```

Finally I created a new Get route to create the response view :
 ```
       public HttpResponseMessage GetPlayground(
        [HttpTrigger(AuthorizationLevel.Anonymous, "get", Route = "ui/playground")] HttpRequestMessage req, ExecutionContext context)
        {
            var response = new HttpResponseMessage(HttpStatusCode.OK);
            response.Content = new StreamContent(PlaygroundPageModel.RenderSteam(context));
            response.Content.Headers.ContentType = new MediaTypeHeaderValue("text/html");
            return response;
        }
```

I hope it could help

**Comment by NicolasReyDotNet** [comment]
@lundmikkel 
Followinf your link I found how to solve the Async IO problem without using the ENV VAR.
[](https://github.com/graphql-dotnet/examples/blob/master/src/AzureFunctions/Example/GraphQLExecutionResult.cs)

Thank for it
