### ISSUE TITLE
Use header value in GraphQL query as argument

### ISSUE THREAD

**Issue by dshevani** [graphql-dotnet/server#288]
I am getting userid in header and there is no way client can pass in POST payload. Can I use it in graphql query as argument to filter results

**Comment by sungam3r** [comment]
You can implement reading the variable from the header yourself. As a starting point you can copy code from `GraphQLHttpMiddleware`. Note that you will need to decide how to use the variables from the request headers for batch requests.

>there is no way client can pass in POST payloadthere is no way client can pass in POST payload

Now the [specification](https://github.com/APIs-guru/graphql-over-http) describes two ways of obtaining variables - from the request body or from the query string. You **can** use GET request, `GraphQLHttpMiddleware` [supports](https://github.com/graphql-dotnet/server/blob/60234479fee2591eb6cb24bea6e1427aab807e4b/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L55) this.

I am going to close this issue. I hope this helps.
