### ISSUE TITLE
Query returns nothing

### ISSUE THREAD

**Issue by Oxymoron290** [graphql-dotnet/server#291]
Hypothetical question here folks, and I'm not sure how this jives with the GraphQL specification, because honestly I have not yet read it in full. But in a scenario where we make a query and it returns nothing, this library responds with HTTP 200 and an empty object. Would it make sense then, to instead return an HTTP 404 or something? Is that possible with this library or is that not how GraphQL is supposed to work? I look forward to your responses.

**Comment by sungam3r** [comment]
What is _nothing_? Query returns some field, which value **can be** null:
```graphql
{
  "data": {
    "somefield": null
  }
}
```
Can you show an example of your request and response?

**Comment by pekkah** [comment]
No, graphql should always return 200 OK if you go by the book.

**Comment by Oxymoron290** [comment]
@sungam3r that is correct, or alternatively an empty array such as this

```
{
  "data": {
    "somefields": []
  }
}
```

@pekkah do you have a source for that? A like to the book? I want to read it in more detail for context please.

**Comment by sungam3r** [comment]
So, query does not return _nothing_, it returns _something_.

https://github.com/APIs-guru/graphql-over-http

**Comment by Oxymoron290** [comment]
@sungam3r that's correct, it does return _something_, I guess just nothing really of value. I see your link, this is what I was looking for. Thank you @pekkah and @sungam3r for your patience with me! Much appreciated!
