### ISSUE TITLE
DefaultGraphQLExecuter set SchemaFilter on ExecutionOptions

### ISSUE THREAD

**Issue by lillheaton** [graphql-dotnet/server#295]
ExecutionOptions set the default SchemaFilter to DefaultSchemaFilter. If I set a custom SchemaFilter on the Schema this does nothing due to it's not gettting passed down to ExecutionOptions.

**Comment by sungam3r** [comment]
@lillheaton Did you mean that (#296)?

**Comment by lillheaton** [comment]
Hi @sungam3r sorry I've most have missed that. But yes that is what I meant.
