### ISSUE TITLE
Middleware forces you to run Kestrel on .NET Core 3.x with AllowSynchronousIO, as it uses synchronous I/O under the hood

### ISSUE THREAD

**Issue by kieranbenton** [graphql-dotnet/server#297]
From my own project, on first use of the graphql API you get the following stacktrace or similar:

```
System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.Peek()
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.Deserialize(Stream stream, GraphQLRequest& single, GraphQLRequest[]& batch)
   at GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware`1.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

Running with .NET Core 3.1 - this is with the default configuration of Kestrel you will get this error.

It is possible to work around the problem in the short-term using something similar to this in your ```Program.cs```, but at the risk of killing scalability of a server through the usual risks of synchronous I/O:

```
.UseKestrel((context, options) =>
{
        ...
	options.AllowSynchronousIO = true;
        ...
})
```

I've cloned the project and had a look to see if I can provide a PR (as I have done for a few other projects) but this isn't a simple replacement of a synchronous call with its -Async version. The code that needs changing is in ```GraphQLHttpMiddleware.cs```. This may not be the only place where synchronous I/O is used:

```
        private bool Deserialize(Stream stream, out GraphQLRequest single, out GraphQLRequest[] batch)
        {
            ...
            // Do not explicitly or implicitly (via using, etc.) call dispose because StreamReader will dispose inner stream.
            // This leads to the inability to use the stream further by other consumers/middlewares of the request processing
            // pipeline. In fact, it is absolutely not dangerous not to dispose StreamReader as it does not perform any useful
            // work except for the disposing inner stream.
            var reader = new StreamReader(stream);
            using (var jsonReader = new JsonTextReader(reader) { CloseInput = false })
            {
                switch (reader.Peek())
                {
                    ...
                }
            }
        }
```

There is no ```StreamReader.PeekAsync```, so this will have to be rewritten more comprehensively. Any guidance as to how to proceed? I can provide a PR if I can be given a bit of a steer.

**Comment by sungam3r** [comment]
Relates to #265, #271 , #277, #1325. #1326

This is a known issue. After graphql-dotnet/graphql-dotnet#1448 this project will also receive support for an alternative serializer (System.Text.Json). I hope to find time for this during the New Year holidays.

**Comment by kieranbenton** [comment]
No problem @sungam3r - let me know if you need a hand with anything, this is a great project.

**Comment by benmccallum** [comment]
I've been able to solve this issue. PR is [here](https://github.com/graphql-dotnet/server/pull/299). Once merged, you won't need to AllowSynchronousIO anymore.

**Comment by floyd-may** [comment]
It seems odd to me that this issue is closed if the currently published package (v3.4.0) still has this problem.

**Comment by floyd-may** [comment]
Also, this issue has been worked around in OttoTheGeek; new version (0.3.2) just published:
https://www.nuget.org/packages/OttoTheGeek

**Comment by benmccallum** [comment]
@floyd-may, it may not be published to nuget, as it's hard to publish this library without getting the owners involved, but it's fixed since this was released: https://www.myget.org/feed/graphql-dotnet/package/nuget/GraphQL.Server.Transports.AspNetCore.SystemTextJson

You should be depending on the `GraphQL.Server.Transports.AspNetCore.SystemTextJson` package now (as per README docs) which you will need to get from that myget feed if you can't get a valid version from nuget directly.

**Comment by floyd-may** [comment]
I'd rather not take a dependency on a `develop` branch package. I'm not even sure that I can publish my package to NuGet that way.

**Comment by sungam3r** [comment]
> It seems odd to me that this issue is closed if the currently published package (v3.4.0) still has this problem.

Closing the issue does not always mean publishing a stable version of the package. In the current preview versions, the problems of dozens of already closed issues/bugs have been solved. The next stable version will have a lot of backward incompatible changes. In addition, this package depends on GraphQL.NET, which is also in "deep alpha" for a long time. In any case, we need to publish GraphQL.NET next 3.0.0 stable version, then bump this project.

> I'm not even sure that I can publish my package to NuGet that way.

You can.

**Comment by sungam3r** [comment]
> I'd rather not take a dependency on a develop branch package

If this can comfort you a little, then I can say that I’ve been using preview versions in the production for more than a year. This is a banking system with many dozens of microservices hosted in k8s.

**Comment by BenjaBobs** [comment]
I too have used it in production.

**Comment by floyd-may** [comment]
I appreciate your confidence in the quality of what's in the develop branch; however, it's not appropriate for me to publish `OttoTheGeek` to NuGet with a dependency on a package that isn't available on NuGet.

**Comment by sungam3r** [comment]
Well, strictly speaking this package available on nuget:  
![изображение](https://user-images.githubusercontent.com/21261007/79800790-8b496500-8365-11ea-8d61-8df4a0a04137.png)

You can ask @joemcbride to publish the latest version of packages to Nuget, he does this once every few months.

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/103369378-0a895e00-4adb-11eb-861c-c9f06d22524d.png)
