### ISSUE TITLE
End support for netcoreapp2.2

### ISSUE THREAD

**Issue by benmccallum** [graphql-dotnet/server#304]
It's now hit EOL, so we should just document in the readme the last version that will support it and drop it.

To change:
* Samples.Server.csproj
** Startup.cs 
* Samples.Server.Tests.csproj
* Directory.Build.props

To remove:
* Serialization.NewtonsoftJson (unless we want to say it can be used with `AllowSynchronousIO` set to true, but that to me is a really bad idea)

**Update** netcoreapp2.1 (LTS release) EOLs on 2021-08-21, which is ages away. So, given we don't target 2.2 specifically (except in the sample projects), we'd almost need to re-target them to 2.1. It's a brave new world.

**Comment by benmccallum** [comment]
Just saw your comment on the PR where I first raised this. Obviously EOL doesn't mean people will stop using 2.2, but I'd argue we shouldn't take on the maintenance burden that comes with feats/fixes for a target that is no longer supported. They can still stay on 2.2, but we draw the line in the sand and say if you want later versions of this library you need to be on a supported netcore version. 

We can keep this open for a couple of months though if the work required to support both isn't too much. Up to you.

**Comment by sungam3r** [comment]
>  if the work required to support both isn't too much. 

I think it would not be too much. It will be possible to remove with confidence the support of the old serializer, when the number of downloads of the new package will increase significantly. In any case, we must first mark the old package as obsolete to use.

**Comment by sungam3r** [comment]
Done in #427
