### ISSUE TITLE
Schema problem with multiple InputObjectGraphType arguments to mutation

### ISSUE THREAD

**Issue by timsueberkrueb** [graphql-dotnet/server#306]
**Setup**

In `MutationType.cs`:

```csharp
arguments: new QueryArguments(
    new QueryArgument<NonNullGraphType<FooInputType>> { Name = "foo" },
    new QueryArgument<NonNullGraphType<BarInputType>> { Name = "bar" },
    new QueryArgument<NonNullGraphType<BazInputType>> { Name = "baz" }
),
```
where `FooInputType`, `BarInputType` and `BazInputType` are classes derived from `InputObjectGraphType`.

`new SchemaPrinter(schema).Print()` returns the correct schema:

```
# ...

input BarInput {
  test: String
}

input BazInput {
  test: String
}

input FooInput {
  test: String
}

type Mutation {
  addFoo(foo: FooInput!, bar: BarInput!, baz: BazInput!): String
}

type Query {
  whatever(id: ID): String
}
```
... and all three types can be found using `Schema.FindType`.

**Problem**

However, when querying the schema from the server using a client, an incomplete schema is returned:
```
{
  "data": {
    "__schema": {
      "types": [
        // default types omitted ...
        {
          "name": "Query"
        },
        {
          "name": "Mutation"
        },
        {
          "name": "FooInput"
        }
      ]
    }
  }
```

Note that only the first argument, `FooInput` is part of the schema.

Displaying the schema in the playground `/ui/playground` therefore fails:
```
Error: Invalid or incomplete schema, unknown type: BarInput. Ensure that a full introspection query is used in order to build a client schema.
```

I've published a (hopefully) **reproducible test case** here: https://github.com/timsueberkrueb/dotnet-graphql-issue

**Environment:**

```
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.4.0" />
    <PackageReference Include="GraphQL.Server.Transports.WebSockets" Version="3.4.0" />
    <PackageReference Include="GraphQL.Server.Ui.GraphiQL" Version="3.4.0" />
    <PackageReference Include="GraphQL.Server.Ui.Playground" Version="3.4.0" />
```

`.NET Core 3.1`, C# 8 on Ubuntu 18.04

Did I do something wrong? Thanks a lot for your help!

**Comment by sungam3r** [comment]
Please first try to upgrade to the latest preview versions of packages.

**Comment by timsueberkrueb** [comment]
Thanks for the quick response. Upgrading to `3.5.0-alpha0027` fixed the issue.
