### ISSUE TITLE
Could not load type 'GraphQL.Http.IDocumentWriter' from assembly 'GraphQL, Version=3.0.0.1446, Culture=neutral, PublicKeyToken=null'.

### ISSUE THREAD

**Issue by chyyran** [graphql-dotnet/server#308]
I'm trying to add GraphQL to an `IServiceCollection`

```csharp
 services.AddGraphQL(options =>
            {
                options.EnableMetrics = true;
                options.ExposeExceptions = true;
            })
```

and I get the following error `Could not load type 'GraphQL.Http.IDocumentWriter' from assembly 'GraphQL, Version=3.0.0.1446, Culture=neutral, PublicKeyToken=null'.`

I suspect it has something to do with this PR: https://github.com/graphql-dotnet/graphql-dotnet/pull/1448 but I'm not sure how to fix this on my end.

**Comment by chyyran** [comment]
Addressed in https://github.com/graphql-dotnet/server/pull/309.

I assume there is no way to fix this through creative use of type forwarding due to the changes involved.

**Comment by sungam3r** [comment]
You can downgrade graphql-dotnet package version, server 3.5.0-alpha0043 is compatible with 3.0.0-preview-1430.

**Comment by chyyran** [comment]
I've done that for now, I suppose I'll close this issue for the time being.
