### ISSUE TITLE
Update Subscriptions projects to use System.Text.Json

### ISSUE THREAD

**Issue by benmccallum** [graphql-dotnet/server#310]
There's a few exclusive uses of Newtonsoft.Json in this project I'd be keen to try and implement with S.T.Json in a similar vein to what we did in #299 

Options:
1. Create interfaces and new projects with implementations like we did for Transports.AspNetCore.
2. Quicker (but dirtier), do what I did in the Ui projects, with conditional package refs and #if #else in the right code for one of the two serializers.

**Comment by benmccallum** [comment]
There's uses in `Transports.Subscriptions.Abstractions` and `Transports.Subscriptions.WebSockets`:
![image](https://user-images.githubusercontent.com/157336/73926266-a7de1100-48cf-11ea-9b4b-7068b94f3121.png)

**Comment by sungam3r** [comment]
You touched on a sore subject. I generally believe that the structure of projects requires refactoring. I still can’t say which option seems best to me.

**Comment by benmccallum** [comment]
Yea I'm not too familiar with the subscription projects as I haven't been using them (yet), but they could require some refactoring, you're right. Whether we do it as part of this is I guess the key question.

It'd be fairly quick to just do option 2, the only drawback being we don't give the consumer the ability to provide their own serializer for websockets stuff. But that could be a feature add later IMO.

**Comment by benmccallum** [comment]
ie. get the performance enhancement in quick, look to refactor for flexibility later.

**Comment by sungam3r** [comment]
Ok

**Comment by Shane32** [comment]
This has been completed in GraphQL.NET Server version 6
