### ISSUE TITLE
No Settings & UserContext

### ISSUE THREAD

**Issue by KreativJos** [graphql-dotnet/server#33]
At the current moment, there is no possibility to use settings in the middleware, like in the [example of the GraphQL project](https://github.com/graphql-dotnet/graphql-dotnet/blob/b5dfa69fc08ed7f1d35e00e89693458662345c97/src/GraphQL.GraphiQLCore/GraphQLSettings.cs).
Currently, I have hacked my way through the project to get this working (I added it to all Contexts etc), but it would be nice to have a clean way to get this implemented.

**Comment by pekkah** [comment]
Resolved in 1.0.0
