### ISSUE TITLE
AuthorizationValidationRule does not authenticate before authorizing

### ISSUE THREAD

**Issue by bgoerdt** [graphql-dotnet/server#333]
I'm attempting to use the GraphQLAuthorize attribute with the schema-first approach. My API has multiple Authentication schemes, with no default authentication scheme. The authentication schemes are aggregated into the default Authorization Policy, which is used with the Authorize attribute for REST endpoints. I would expect the GraphQLAuthorize attribute to work the same way, but since nothing is enforcing authentication before the `/graphql` endpoint is hit, HttpContext.User is empty and authorization fails. 

The AuthorizationMiddleware uses the [policyEvaluator](https://github.com/dotnet/aspnetcore/blob/b56f84131af2e1ece61241a016e191f5f2fe3fc0/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L57) to authenticate using authentication schemes specified in the AuthorizationPolicy before trying to authorize. I think using this same approach in the [AuthorizationValidationRule](https://github.com/graphql-dotnet/server/blob/develop/src/Authorization.AspNetCore/AuthorizationValidationRule.cs) would solve this issue.

To get around this issue for now, I added this middleware to authenticate using the PolicyEvaluator for the default policy:
```
app.Use(
    async (context, next) =>
        {
            var defaultAuthorizationPolicy = AuthorizationExtensions.CreateDefaultPolicy(
                "my-authentication-scheme-1",
                "my-authentication-scheme-2");

            var policyEvaluator = context.RequestServices.GetRequiredService<IPolicyEvaluator>();
            await policyEvaluator.AuthenticateAsync(defaultAuthorizationPolicy, context);

            await next.Invoke();
        });
```

**Comment by Ekkeir** [comment]
If I'm not mistaken, another approach would be to add net core authentication middleware and set it up to use multiple authentication schemes via default policy or policyScheme to select an appropriate authentication scheme. This way HttpContext.User should be populated before gql-middleware and its' authorization are hit.

Another approach would be to implement your own IValidationRule based on [AuthorizationValidationRule](https://github.com/graphql-dotnet/server/blob/develop/src/Authorization.AspNetCore/AuthorizationValidationRule.cs#L88-L94) and use policy evaluator before authorization like they do in [AuthorizationMiddleware](https://github.com/dotnet/aspnetcore/blob/b56f84131af2e1ece61241a016e191f5f2fe3fc0/src/Security/Authorization/Policy/src/AuthorizationMiddleware.cs#L57-L67).

It seems that policy evaluator used to be an [opt-in functionality](https://github.com/dotnet/aspnetcore/blob/68f0aff1440e61e15eaa90d098c0f136fbbb4c64/src/Security/Authorization/Policy/src/PolicyServiceCollectionExtensions.cs#L20) and only recently got promoted to be added to DI by default in `AddAuthorization` at about [Net Core 3.x](https://github.com/dotnet/aspnetcore/blob/16a47948f80fede807fabe3c291d793590e8fd17/src/Security/Authorization/Policy/src/PolicyServiceCollectionExtensions.cs)

**Comment by sungam3r** [comment]
@bgoerdt I hope you managed to solve the problem. Reopen this issue if you still have questions.
