### ISSUE TITLE
Support for Apollo Federation?

### ISSUE THREAD

**Issue by prcdpr** [graphql-dotnet/server#335]
I have multiple GraphQL schemas as microservices that I'd like to merge into single data graph.

I'd like to use Apollo Federation 
https://www.apollographql.com/docs/apollo-server/federation/federation-spec/

Would you consider adding support for that spec?

**Comment by Tall-Paul** [comment]
Can confirm that Federation does work using the latest Asp.Net Server middleware:

https://github.com/Tall-Paul/dotnetGqlFederation

**Comment by Shane32** [comment]
Closing as answered; I believe the necessary support comes from GraphQL.NET rather than within this repo.
