### ISSUE TITLE
Late-bound schema definitions / ISchemaGenerator

### ISSUE THREAD

**Issue by GeertvanHorrik** [graphql-dotnet/server#339]
I am trying to use the SchemaBuilder from graphql.net to create a fully dynamic (entities are defined at runtime).

I am able to create a dynamic schema, but unfortunately the asp.net core integration requires a schema type at registration.

What I would like to do is fully instantiate the asp.net core, instead of registering the schema, register ISchemaGenerator (or whatever name makes sense):

```
public interface ISchemaGenerator
{
    Task<ISchema> GenerateAsync();
}
```

This will allow the database / adapters / etc to be fully instantiated as soon as the actual asp.net core pipeline comes up. Then, when the first request is made, the ISchemaGenerator can be queried from the ServiceProvider and use that to instantiate the schema (once).

I hope this idea makes sense. I already checked most of the code of this package, and I *think* this shouldn't be too hard because at the end it simply instantiates the schema (which I generate on fly, similar to the interface above).

**Comment by GeertvanHorrik** [comment]
Here is the only instance I see the usage of the schema. But... there already is a non-generic (or just ISchema) implementation available:

https://github.com/graphql-dotnet/server/blob/c291175994e0ee8322a3d3b7e25cbe1be6957259/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L122

**Comment by sungam3r** [comment]
> but unfortunately the asp.net core integration requires a schema type at registration.

`services.AddSingleton<ISchema>(provider => SomeGenerator.GenerateSuperDynamicSchema(provider));`  ?

**Comment by sungam3r** [comment]
> But... there already is a non-generic (or just ISchema) implementation available:

```c#
services.AddSingleton<ISchema, ChatSchema>();
...
app.UseGraphQL<ISchema>();
```

**Comment by GeertvanHorrik** [comment]
The issue is that, during that initialization, the services that I need are being registered. So basically I need a late-bound schema registration.

**Comment by GeertvanHorrik** [comment]
I don't need to have it in the serviceCollection btw, just need a way to customize the schema (I can already customize the fields of the types at runtime, but I want to be able to register types at runtime as well).

**Comment by sungam3r** [comment]
> So basically I need a late-bound schema registration.

`services.AddSingleton<ISchema>(provider => SomeGenerator.GenerateSuperDynamicSchema(provider)); `
But isn't that a late-bound schema registration? Or rather late-bound creation. What do you mean speaking of _registration_?

**Comment by GeertvanHorrik** [comment]
I cannot modify the services collection once it's all up and running? Or am I missing something?

**Comment by sungam3r** [comment]
Right, and you should not. Explain what you want to achieve.

**Comment by GeertvanHorrik** [comment]
So my services (that access the db) are being registered at middleware setup. Then, I will use these providers / adapters to access the db to how the schema should actually look like. Does that make sense?

**Comment by sungam3r** [comment]
What does "middleware setup" mean? You **can** register all you dependencies in the right place - before `IServiceCollection` turns into `IServiceProvider`. Maybe an example code would help. I find it difficult to give advice without seeing what and where you are doing.

**Comment by GeertvanHorrik** [comment]
I will try to explain as good as I can. I have plugins, these plugins are able to register their services in the asp.net core setup phase. These plugins register IDataProvider (basically just sql adapters) instances. 

Once these instances have been registered, I can actually instantiate *new* (hosted) services that can retrieve these data adapters / providers via dependency injection. These providers will actually query the database (there is sort of a master scheme) on how the data model looks.

Then I am able to set up the schema.

So basically:

1. Register types in the service collection (this is the time where I also call this:

```
        public void ConfigureGraphQL(IApplicationBuilder app, IWebHostEnvironment env)
        {
            _logger.Information("Configuring GraphQL");

            // Enable endpoint for websockets (subscriptions)
            app.UseGraphQLWebSockets<MyAppSchema>("/graphql");

            // Enable endpoint for querying
            app.UseGraphQL<MyAppSchema>("/graphql");

            // Playground
            if (env.IsDevelopment())
            {
                app.UseGraphQLPlayground(new GraphQLPlaygroundOptions
                {
                    
                });
            }
        }
```

However, I don't want a typed schema, I want a runtime scheme. So I am not sure what I need to register here. Preferably I would like to register a `ISchemaGenerator`. This gives me more time to actually instantiate the hosted service / async initialization (which need the services in service collection).

I want to generate (late-bound). Here is the code I use to generate a totally dynamic graphql scheme:

```
public async Task<ISchema> GenerateRuntimeSchemaAsync()
{
            var schema = new Schema();

            var schemaDefinition = await _schemaService.GetSchemaDefinitionAsync();
            if (schemaDefinition != null)
            {
                // Convert to data set so we have every relationship we need
                var dataSet = schemaDefinition.ToDataSet();

                var queryGraphType = new ObjectGraphType();
                queryGraphType.Name = "Root";

                // Set up dynamic graphql
                foreach (var dataTable in dataSet.Tables.Cast<DataTable>())
                {
                    var table = dataTable.GetSchemaTable();
                    if (table is null)
                    {
                        _logger.LogWarning($"No schema table is attached to table '{dataTable.TableName}'");
                        continue;
                    }

                    var targetType = dataTable.GetTargetType();
                    if (targetType is null)
                    {
                        _logger.LogWarning($"No target type is specified for '{dataTable.TableName}'");
                        continue;
                    }

                    // Implementation of graph type creation left out for simplicity
                    var objectGraphType = CreateObjectGraphType(dataTable, targetType);
                    schema.RegisterTypes(objectGraphType);

                    var field = new FieldType
                    {
                        Name = table.GetPlural().ToCamelCase(),
                        ResolvedType = new ListGraphType(objectGraphType),
                        Resolver = new AsyncFieldResolver<List<IDynamicModel>>(async (context) => await _dynamicStorageAdapter.GetAsync(table))
                    };

                    queryGraphType.AddField(field);
                }
            }

            return schema;
}
```

**Comment by GeertvanHorrik** [comment]
An extra bonus would be that I could actually change the schema at runtime (so people add new fields to an entity), refresh the graphql schema and enjoy!

**Comment by sungam3r** [comment]
> Register types in the service collection (this is the time where I also call this:

There is no service collection. This is another stage. You need `ConfigureServices` before that.

**Comment by sungam3r** [comment]
>  I could actually change the schema at runtime

This will be a very interesting adventure for you and especially for your customers. I would not advise doing this before thinking 10 times.

**Comment by GeertvanHorrik** [comment]
> There is no service collection. This is another stage. You need ConfigureServices before that.

That's what I mean. ConfigureServices (IServiceCollection)

> This will be a very interesting adventure for you and especially for your customers. I would not advise doing this before thinking 10 times.

It's for an internal product only, so it's aware of schema changes and won't break any clients. I am not too worried about this.

Here is my initialization routine:

![image](https://user-images.githubusercontent.com/1246444/75488944-8beefc00-59b1-11ea-8432-b46c67d5cdad.png)

**Comment by sungam3r** [comment]
As I said before try this:

```c#
   app.UseGraphQLWebSockets<ISchema>("/graphql");

   // Enable endpoint for querying
   app.UseGraphQL<ISchema>("/graphql");
```
\+
```c#
services.AddSingleton<ISchema>(provider => SomeGenerator.GenerateRuntimeSchemaAsync().GetAwaiter().GetResult());
```

**Comment by GeertvanHorrik** [comment]
Will try and let you know, thanks!

**Comment by GeertvanHorrik** [comment]
This seems to do late-bound registration, great! Thanks for the help :-)

```
// Generate runtime
serviceCollection.AddSingleton<ISchema>(provider => provider.GetService<IGraphSchemaGenerator>().GenerateSchemaAsync().GetAwaiter().GetResult());
```
