### ISSUE TITLE
Not using UseMiddleWare api

### ISSUE THREAD

**Issue by KreativJos** [graphql-dotnet/server#34]
The middleware is not currently using the UseMiddleWare-api, which I think it should be.
This can be solved in the 'Startup.Configure'-function, the following way:

`app.UseMiddleware<<ChainCompanySchema>>();`

And next to that, having this function in the ITransport-interface (and inheriting classes):
`async Task Invoke(HttpContext context)`

**Comment by pekkah** [comment]
Added in 1.0.0
