### ISSUE TITLE
System.InvalidOperationException: Unable to resolve service for type 'GraphQL.Server.Transports.AspNetCore.Common.IGraphQLRequestDeserializer' while attempting to activate 'GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware

### ISSUE THREAD

**Issue by eddyjl077** [graphql-dotnet/server#344]
Keep getting this error after update to 

![image](https://user-images.githubusercontent.com/20169438/75833047-cf68b200-5d85-11ea-806b-911e6bf1f9c7.png)

System.InvalidOperationException: Unable to resolve service for type 'GraphQL.Server.Transports.AspNetCore.Common.IGraphQLRequestDeserializer' while attempting to activate GraphQL.Server.Transports.AspNetCore.GraphQLHttpMiddleware

Any solution?

thank you.

**Comment by sungam3r** [comment]
@eddyjl077 I hope you could solve the problem.

**Comment by eddyjl077** [comment]
Yes, i did, thank you.

**Comment by jgwynn2901** [comment]
Thanks for the info
