### ISSUE TITLE
(string) Field(h => h.Name) = null, causes resolving GraphQL object to be null 

### ISSUE THREAD

**Issue by Fogerty** [graphql-dotnet/server#345]
After upgrading from 3.5.0-alpha0005 to 3.5.0-alpha0068,

Declaration method 1:
Field(h => h.Name).Description("The name of the type ")
Field(h => h.Id).Description("The id of the type")

If a _string_ field (h.Name) = null, the whole GraphQL object is resolved as null.

Declaration method 2:
Field<StringGraphType>("name", "The name of the type", resolve: context => context.Source.Name);
Field<IntGraphType>("id", "The id of the type", resolve: context => context.Source.Id);

If _string_ field is declared using method 2 instead, the GraphQL object including h.Id will resolve normally, even if h.Name = null:

Declaration method 2 solves the problem

**Comment by sungam3r** [comment]
> the whole GraphQL object is resolved as null

So your parent object field declared as nullable in the schema?

See https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Composite/ComplexGraphType.cs#L328

It works as designed - not nullable field being returned as null caused parent field to be null.

**Comment by sungam3r** [comment]
3.5.0-alpha0005 depends on GraphQL (>= **2.3.0**)
3.5.0-alpha0068 depends on GraphQL (>= **3.0.0**-preview-1585)

Major version bump always may break your code.

**Comment by Fogerty** [comment]
The two declaration methods have different behaviors as Method 1 defaults to nonNullable, and method 2 defaults to nullable, and has to explicitly declared as <NonNullable<StringGraphType>>. This caught me a bit off guard. When null is passed to a nonNullable type, it could have helped in this situation to throw an exception instead of nulling out the parent object.

Thank you for the work you are doing with this repo!

**Comment by sungam3r** [comment]
Relates to graphql-dotnet/graphql-dotnet#1290
