### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by TheBlaze** [graphql-dotnet/server#347]
I would like to call my .Net Graphql API from a Vue.js app (using Apollo) and I'm getting CORS errors. Is there a way to enable CORS support? I tried adding:
services.AddCors(... to my Startup.cs but it's not working.

Please advise.

**Comment by thiagozulato** [comment]
Hey! @TheBlaze  Have you tried to call the middleware in the `Configure` method? `app.UseCors()`

Here is my Cors confguration:

```csharp
public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors(options =>
            {
                options.AddPolicy("DefaultPolicy", builder =>
                {
                    builder.AllowAnyHeader()
                           .WithMethods("GET", "POST")
                           .WithOrigins("http://localhost:3000");
                });
            });

            services.AddHttpContextAccessor();

            services.AddGraphQL(options =>
            {
                options.EnableMetrics = true;
                options.ExposeExceptions = true;
            })
            .AddGraphSchemas()
            .AddGraphTypes(Assembly.GetExecutingAssembly())
            .AddNewtonsoftJson()
            .AddUserContextBuilder(httpContext => new GraphQLUserContext { User = httpContext.User });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app)
        {
            app.UseCors("DefaultPolicy");

            app.UseGraphQL<ISchema>();
            app.UseGraphQLPlayground();
        }
```

**Comment by TheBlaze** [comment]
Thank you, now it works.

**Comment by geochavarria** [comment]
Here is my Cors Net. 6
`
var builder = WebApplication.CreateBuilder(args);
//Add GraphQL Services
builder.Services.AddInMemorySubscriptions();
builder.Services.AddGraphQLServer()
               .AddQueryType<Query>()
               .AddType<DesarrolloHumanoQuery>()
               .AddType<CompraQuery>()
               .AddType<RegistroAcademicoQuery>()
               .AddType<FinanzaQuery>()
               .AddMutationType(_ => _.Name("mutation"))
               .AddType<CompraMutation>();

//Add Cors
var mySpecificOrigin = "_SpecificOrigins";
builder.Services.AddCors(builder =>
{
    builder.AddPolicy(name: mySpecificOrigin,
        policy =>
        {
            policy.WithOrigins("http://localhost:3000")
            .AllowAnyMethod()
            .AllowAnyHeader();
        });
});

// Add services to the container. My custom SQL Service Init 
builder.AddPersistenceInfrastructure();
builder.Services.AddControllers();

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseRouting();
app.UseCors(mySpecificOrigin);
app.UseAuthorization();
app.UseWebSockets();


app.UseEndpoints(endpoints =>
{
    endpoints.MapGraphQL()
        .WithOptions(new GraphQLServerOptions
        { 
            AllowedGetOperations = AllowedGetOperations.QueryAndMutation,
            EnableGetRequests = false,
            Tool = { Enable = false }
        });
});

app.Run();
`

**Comment by geochavarria** [comment]
Here is my Cors Net 6
```

var builder = WebApplication.CreateBuilder(args);
//Add GraphQL Services
builder.Services.AddInMemorySubscriptions();
builder.Services.AddGraphQLServer()
               .AddQueryType<Query>()
               .AddType<DesarrolloHumanoQuery>()
               .AddType<CompraQuery>()
               .AddType<RegistroAcademicoQuery>()
               .AddType<FinanzaQuery>()
               .AddMutationType(_ => _.Name("mutation"))
               .AddType<CompraMutation>();

//Add Cors
var mySpecificOrigin = "_SpecificOrigins";
builder.Services.AddCors(builder =>
{
    builder.AddPolicy(name: mySpecificOrigin,
        policy =>
        {
            policy.WithOrigins("http://localhost:3000")
            .AllowAnyMethod()
            .AllowAnyHeader();
        });
});

// Add services to the container. My custom SQL Service Init 
builder.AddPersistenceInfrastructure();
builder.Services.AddControllers();

// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();
app.UseRouting();
app.UseCors(mySpecificOrigin);
app.UseAuthorization();
app.UseWebSockets();


app.UseEndpoints(endpoints =>
{
    endpoints.MapGraphQL()
        .WithOptions(new GraphQLServerOptions
        { 
            AllowedGetOperations = AllowedGetOperations.QueryAndMutation,
            EnableGetRequests = false,
            Tool = { Enable = false }
        });
});

app.Run();

```
