### ISSUE TITLE
Issues with Scoped DbContext since switch to 3.0

### ISSUE THREAD

**Issue by julienFlexsoft** [graphql-dotnet/server#350]
## Summary
Hi!
Yesterday I updated my project to .NET Core 3.1. I then updated all my dependencies to the latest version. I then switched to graphql-dotnet 3.0. But now I have the classic EfCore "A second operation started on this context before a previous operation completed" error. Which is weird because I didn't have this issue before the update. And when I switch back to my not-yet-updated branch it all still works.

After researching this issue I found a potential solution which is to changed my query execution to work in series instead of the default parallel. The thing is, I have no idea where to do that. Is it somewhere in Startup.cs, or in my schema, or somewhere else? I can't find any examples so I'm quite lost.

## Relevant information
`
GraphQL - 3.0.0-preview-1490
GraphQL-Parser - 5.1.0
GraphQL.Authorization - 3.0.39-preview-39
GraphQL.Server.Transports.AspNetCore - 3.5.0-alpha0046
GraphQL.Server.Transports.AspNetCore.SystemTextJson - 3.5.0-alpha0046
GraphQL.Server.Transports.WebSockets - 3.5.0-alpha0046
GraphQL.Server.Ui.Playground - 3.5.0-alpha0046
GraphQL.SystemTextJson - 3.0.0-preview-1490`

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server#getting-started

Use myget feed.
