### ISSUE TITLE
Add Extensions to GraphQLRequest

### ISSUE THREAD

**Issue by DaniilSokolyuk** [graphql-dotnet/server#352]
Hello, currenly we implement [Apollo Persisted Query](https://www.apollographql.com/docs/apollo-server/performance/apq/) in custom GraphQLHttpMiddleware.
After split request deserialization in separate nuget it got a little harder to do)
Can we have extensions field in [GraphQLRequest](https://github.com/graphql-dotnet/server/blob/develop/src/Core/Common/GraphQLRequest.cs) like Inputs?

**Comment by sungam3r** [comment]
Where and how are you going to use this property?

**Comment by DaniilSokolyuk** [comment]
For  [Apollo Persisted Query](https://www.apollographql.com/docs/apollo-server/performance/apq/)  protocol implementation, protocol details [here](https://github.com/apollographql/apollo-link-persisted-queries), all apollo clients (js, ios, android) support this feature, we use this feature to implement whitelists (save request only under certain conditions)

**Comment by sungam3r** [comment]
@DaniilSokolyuk See https://github.com/APIs-guru/graphql-over-http/pull/4 . I think we should wait decision about this property.

**Comment by DaniilSokolyuk** [comment]
@sungam3r https://github.com/graphql/graphql-over-http/pull/4 merged

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server/releases/tag/4.2.0

**Comment by DaniilSokolyuk** [comment]
@sungam3r Thanks!

**Comment by tobias-tengler** [comment]
I'm trying to implement persisted queries as well, but I'm having some issues. Hopefully one of you can help me out! :)

I created a custom middleware:
```csharp
/// PersistedQueriesMiddleware.cs
public class PersistedQueriesMiddleware<TSchema> : GraphQLHttpMiddleware<TSchema> where TSchema : ISchema
{
    public PersistedQueriesMiddleware(RequestDelegate next, PathString path, IGraphQLRequestDeserializer requestDeserializer) : base(next, path, requestDeserializer)
    {
    }

    protected override Task RequestExecutingAsync(GraphQLRequest request, int? indexInBatch = null)
    {
        // Custom code resolving the query for the specified query hash and setting request.Query would go here.

        // request.Extensions is null here :(

        return base.RequestExecutingAsync(request, indexInBatch);
    }
}

// Startup.cs
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    // ...

    app.UseGraphQL<ISchema, PersistedQueriesMiddleware<ISchema>>("/");
}
```

This is the request body I'm sending:
```json
{
    "extensions": {
        "documentId": "test",
        "nested": {
            "hash": "test2"
        }
    }
}
```

When sending a request the middleware is invoked as expected, but the `Extensions` property is always `null`.

What am I missing? @DaniilSokolyuk could you maybe provide some insights into your final implementation?

**Comment by sungam3r** [comment]
@tobias-tengler Also see #132

**Comment by DaniilSokolyuk** [comment]
@tobias-tengler we have not yet migrate to version 3 due to the large number of changes, sorry

**Comment by sungam3r** [comment]
We plan to release GraphQL.NET v4 / Server v5 on February 1.
