### ISSUE TITLE
[Question] Authentication with ASP.NET Core, should use Controller?

### ISSUE THREAD

**Issue by lydonchandra** [graphql-dotnet/server#359]
Should we use ASP.NET Core Controller to perform authentication? eg. provide an endpoint to login?
Or what is the best practice?

**Comment by sungam3r** [comment]
You can also use middleware. In general, this question is not specific to that project.

**Comment by sungam3r** [comment]
https://wakeupandcode.com/authentication-authorization-in-asp-net-core-3-1/
