### ISSUE TITLE
Batching support

### ISSUE THREAD

**Issue by Jan080906** [graphql-dotnet/server#361]
Hello everyone, I have been struggling about how to make it work on the server side. Do you have any example or explanation about it? 

1. I want to use this with batch link in apollo. like this
POST /graphql?batchOperations=[Operation1, Operation2, Operation3, Operation4]
the url here does it need to specified on server side?

2. Can Batching be used from Api to Api? I mean if I have openApi which is interface between client and all backend components. So client will trigger openApi which then will send the request to specified backend components.

I'm very new to this. Please guide me :)

**Comment by sungam3r** [comment]
Send payload like that:
```json
[
  {
    "query": "",
    "operationName": "",
    "variables": ""
  },
 {
    "query": "",
    "operationName": "",
    "variables": ""
  },
]
```

Server executes requests in batch sequentially.

**Comment by Jan080906** [comment]
what about the path here, we don't need to specify?
POST /graphql?batchOperations=[Operation1, Operation2, Operation3, Operation4]

**Comment by sungam3r** [comment]
You don't need to specify any data in query string. Use your ordinal graphql path /graphql.

**Comment by Jan080906** [comment]
oh ok thank you so much :)

**Comment by sungam3r** [comment]
I did not work with apoolo products.

**Comment by sungam3r** [comment]
Closed as answered.
