### ISSUE TITLE
help with apollo client graphql-ws sub protocol

### ISSUE THREAD

**Issue by emceelovin** [graphql-dotnet/server#362]
@joemcbride , when using graphql-dotnet-server with an apollo client, everything works 100%. websocket subscriptions and full graphql over websockets work great. HOWEVER, i am writing my own proxy, and have successfully forwarded all HTTP requests. works extremely well, BUT, when i try to proxy a graphql-ws subprotocol request over, apollo client INSTANTLY disconnects due to an internal timer error as soon as i call WebSocketManager.AcceptWebSocketAsync(). I found a fix on the apollo client github, but your server doesn't appear to suffer from this issue at all. it does not require this fix on our SPA side. i looked all throughout the graphql-dotnet-server middleware to see if something is going on that i am not doing, but i cannot find anything, so that's why i'm reaching out to you; because your server works lol. when creating the graphql dotnet server, did you run into this issue, and if so, how did you fix it? if you could help me find out what is going on with graphql dotnet server, that i do not know about, i would be greatly appreciative!

**Comment by joemcbride** [comment]
Hey @emceelovin, I didn't write the protocol, so I won't be of much help.  @pekkah was the primary developer on the protocol, which he has written more than once (check out his new project which looks pretty cool).

https://github.com/pekkah/tanka-graphql
https://pekkah.github.io/tanka-graphql/2-server/2-graphql-ws/3-graphql-ws.html

**Comment by emceelovin** [comment]
very good! I will definitely check that out!

**Comment by emceelovin** [comment]
I appreciate the guidance a lot! hopefully @pekkah can help me resolve this issue. it. has been bugging me forever. I have resolved the issue a client-side fix, but apparently the issue is in WebSocketClient class in Apollo-link-ws, or maybe it was an issue in subscription-transport-ws. thanks again though! much appreciated

**Comment by pekkah** [comment]
How are you proxying the websocket connection?

**Comment by sungam3r** [comment]
This issue will be transferred into the server project.

**Comment by emceelovin** [comment]
@pekkah unfortunately i am not able to get to that point yet, but i fire up a connection to the actual graphql server from the proxy, which is fine once i put it into a receive loop. then i want to take anything that comes in off the apollo client websocket connection, and just marshal the data to/from the connection i establish to the graphql server. the problem is, i cant establish a connection from the apollo-client to my proxy, and i am not sure why. as soon as i attempt to connect to the proxy with the apollo-client without the fix, it instantly disconnects before i even get to AcceptWebSocketAsync() middleware code in the pipeline. i'm trying to remember if it instantly disconnects before the call to AcceptWebSocketAsync() or not, but i'm pretty sure it does. i'm gonna do another test and see, but i think even if i set a breakpoint on the AcceptWebSocketAsync() line, chrome console shows "websocket is closed before the connection is established." when i debug that, its a clientside call to close() based on a timer, but  your server doesn't suffer from the clientside issue somehow. it works 100% fine. my server will only work if i apply the fix from the apollo-client github issues section. when i looked at the graphql-server websocket middleware source, i can't seem to find anything different than what i'm doing. pretty frustrating. thanks for replying btw!

**Comment by pekkah** [comment]
Could you show some code? It's bit hard to tell what is happening without it.

**Comment by emceelovin** [comment]
absolutely. here is all i have so far. sorry about the formatting. i'm not really great with this GitHub reply section yet. if i set a breakpoint at the line with "if(context.WebSockets.IsWebSocketRequest)," which is hit, i don't even get a chance to accept the websocket connection from our SPA,  GraphQL playground, or anything using apollo-client. it immediately prints this to the chrome console: "failed: WebSocket is closed before the connection is established" before i step over that breakpoint  to the accepting code. which is making me think i have something wrong with my IApplicationBuilder, IServiceCollection, or even something else that i am not knowing about. i've been fighting with this issue for weeks and weeks, so hopefully i can get some help. its really frustrating. i appreciate the responses also. i hope this is enough code!

// IApplicationBuilder
app.UseWebSockets()
               .UseCors("AllowAllOriginsPolicy") // temporary
               .UseGraphQLProxy()

// proxy graphql api portal not on the default /graphql route
               .UseGraphQL<GraphQL.Schema.Schema>(playgroundOptions.GraphQLEndPoint)
               .UseGraphQLWebSockets<GraphQL.Schema.Schema>(playgroundOptions.GraphQLEndPoint)
               .UseGraphQLPlayground(playgroundOptions);

// proxy middleware
public async System.Threading.Tasks.Task InvokeAsync(Microsoft.AspNetCore.Http.HttpContext context)
        {
            if ("/graphql" == context.Request.Path)
                await Router.Router.RouteRequest(context);
            else
                await _next(context);
        }

// RouteRequest(HttpContext)
static public async System.Threading.Tasks.Task RouteRequest(Microsoft.AspNetCore.Http.HttpContext context)
        {
// breakpoint at this condition is hit, and the apollo-client connections immediately closes before the accepting code 
            if(context.WebSockets.IsWebSocketRequest)
            {
                var webSocket = context.WebSockets.AcceptWebSocketAsync("graphql-ws");
            }
            else
            {
                // http request proxy code omitted
            }
        }

**Comment by emceelovin** [comment]
@pekkah  if i use this code on the SPA side that i found on the apollo-client issues section, i dont have any problem at all accepting a graphql websocket request from apollo-client

class CustomSubscriptionClient extends SubscriptionClient {
  constructor(
    url: string,
    options?: ClientOptions,
    webSocketImpl?: any,
    webSocketProtocols?: string | string[]
  ) {
    // It needs to be forced lazy otherwise it will try to connect before the setting up the following workaround
    super(url, { ...options, lazy: true }, webSocketImpl, webSocketProtocols);

    // Workaround suggested for ISSUE 377 on subscriptions-transport-ws package
    // https://github.com/apollographql/subscriptions-transport-ws/issues/377#issuecomment-375567665
    // @ts-ignore
    this.maxConnectTimeGenerator.setMin(this.maxConnectTimeGenerator.max);
    const { lazy = false } = options || {};
    if (!lazy) {
      // @ts-ignore
      this.connect();
    }
  }
}

**Comment by Shane32** [comment]
@emceelovin Are you still looking for answers for this topic?  I can provide some insight or links to protocol details if that would help.

**Comment by Shane32** [comment]
@emceelovin I'll close this issue for now.  If you have questions, please re-open this issue.  I should be able to answer any questions you have regarding the protocol.
