### ISSUE TITLE
Pre- and post actions per http request

### ISSUE THREAD

**Issue by taimo42** [graphql-dotnet/server#363]
It would be quite handy, if there is a pre- and post action which is triggered by the default graphql middleware before and after executing the graphql request.
In my use case, I would begin and commit a database transaction in these action methods, but of course it could also be used for other stuff.
So could it be possible to add two empty virtual methods like this to GraphQLHttpMiddleware?

```C#
        protected virtual Task PreRequestExecutionAsync(GraphQLRequest graphQlRequest)
        {
            // nothing to do in this middleware
            return Task.CompletedTask;
        }

        protected virtual Task PostRequestExecutionAsync(ExecutionResult[] executionResults)
        {
            // nothing to do in this middleware
            return Task.CompletedTask;
        }
```

Then I can easily derive from this class and override the two methods to add my custom logic.

I really don't want to replace the whole middleware because then I have to rewrite all the complex logic which is implemented there. I also already thought about using a custom GraphQLExecuter, but for batched queries it is called for every batch item. The same stands for the already existing virtual method `RequestExecutedAsync`. 

Or is there another possibility to execute some pre- and post http request actions without implementing a custom middleware?

Your help would be very appreciated.

**Comment by sungam3r** [comment]
> Or is there another possibility to execute some pre- and post http request actions without implementing a custom middleware?

Why not just add one more custom middleware?

**Comment by taimo42** [comment]
So, yes, it should be possible to add one custom middleware before the default GraphQLHttpMiddleware, which will then opening the transaction, and another one after it, which will then commit the transaction. 

But it would also be necessary to pass additional data, e.g. if the execution of the graphql operation was succesfull, by using a scoped service, because the method signature is just `Task InvokeAsync(HttpContext context)`. Additionaly I don't want to open a transaction for an introspection query, so I also need to parse the graphql query in both of these new custom middleware, even if this is done in GraphQLHttpMiddleware anyway. 

So I'm just wondering if there is an easier way to achive this. These two empty virtual methods would solve it in a clean way.

**Comment by sungam3r** [comment]
> and another one after it

It is the same **single** middleware. You execute code before and after calling `next()` delegate. 

> These two empty virtual methods would solve it in a clean way.

OK. I'll think about it when I have time.

**Comment by sungam3r** [comment]
OK. Here are available options:
1. Write your custom middleware and do whatever you want before or after it.
2. Write your custom `IGraphQLExecuter` and inject it in DI before calling `AddGraphQL` method.

Well, I don't see any real benefit to writing the two methods you suggest. Actually `PostRequestExecutionAsync` is `RequestExecutedAsync`. OK. I will add new `RequestExecutingAsync` method for v4.3, but for v5.0 the whole middleware may be rewritten from ground.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server/releases/tag/4.3.0
