### ISSUE TITLE
Default Config for UseGraphQLPlayground

### ISSUE THREAD

**Issue by manoochehrkateb** [graphql-dotnet/server#364]
Hello ,
I Just New to GraphQL but I realize that :
```
            app.UseGraphQLPlayground(new GraphQLPlaygroundOptions()
            {
                Path = "/ui/playground"
            });
```
We have only path config , 
I want to **change** default **settings** on UseGraphQLPlayground Like :

  'schema.polling.enable': boolean
  'request.credentials': 'omit' | 'include' | 'same-origin'

thanks guys for supporting .

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server/blob/develop/src/Ui.Playground/GraphQLPlaygroundOptions.cs

https://github.com/graphql-dotnet/server#graphql-for-net---subscription-transport-websockets

**Comment by manoochehrkateb** [comment]
Thanks for answer . 
But not apply to playground .

**Comment by sungam3r** [comment]
> But not apply to playground .

?

**Comment by manoochehrkateb** [comment]
Nothing happening man ,
```
app.UseGraphQLPlayground(new CustomeGraphQLPlaygroundOptions()
            {
                Path = "/ui/playground",
                RequestCredentials = RequestCredentials.Include,
                SchemaPollingEnabled = false
            });
```

CustomeGraphQLPlaygroundOptions inherit from GraphQLPlaygroundOptions

**Comment by sungam3r** [comment]
Well, try modify sample app from this repo and see if it works.

**Comment by manoochehrkateb** [comment]
It's because of my version .

**Comment by sungam3r** [comment]
Closed as answered.
