### ISSUE TITLE
Base Response for fields

### ISSUE THREAD

**Issue by manoochehrkateb** [graphql-dotnet/server#369]
I have a base class for response 

```
    public class BaseResponseGraphType<TGraphType> : ObjectGraphType<TGraphType>
    where TGraphType : IGraphType
    {
        public BaseResponseGraphType()
        {
            Field<ListGraphType<TGraphType>>(name : "items");
            Field<IntGraphType>(name : "itemCount");
        }
    }
```

but when I use multiple time it returns same type 

```
            Field<BaseResponseGraphType<ChargingLogGraphType>>(); // returns :items:SmsGraphType **(which is wrong . it should be items:ChargingLogGraphType)**
            Field<BaseResponseGraphType<SmsGraphType>>(); // returns :items:SmsGraphType
```

note : see my comments plz

**Comment by sungam3r** [comment]
What version do you use? What do you mean "it returns same type"?

**Comment by manoochehrkateb** [comment]
GraphQL.Server : 1.7.0.1
see my comments on code 

![image](https://user-images.githubusercontent.com/15786908/86504874-1c5fa200-bdd3-11ea-8447-cf5b6960da24.png)
![image](https://user-images.githubusercontent.com/15786908/86504883-3e592480-bdd3-11ea-9608-9f612fe708ad.png)

**Comment by sungam3r** [comment]
1.7.0.1 ? I even do not know such old version. Try the latest preview. See readme.

**Comment by manoochehrkateb** [comment]
Thanks ,
Now I have GraphQL : 3.0.0-preview-1490 .

Now I get error that said its "already registered" , but it's **not** the same type .

> unable to register GraphType 'project.BaseListFilterResponseGraphType`1[[project.Cms.Customers.ReportCustomerAppEventLogGraphType, IntegratedDashboad.Infra.Dto.Dtoes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]' with the name 'BaseListFilterResponseGraphType_1';\nthe name 'BaseListFilterResponseGraphType_1' is already registered to 'project.BaseListFilterResponseGraphType`1[[project.Cms.Customers.ReportCustomerSubscribePackageGraphType, IntegratedDashboad.Infra.Dto.Dtoes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]] 

![image](https://user-images.githubusercontent.com/15786908/86511233-4e412a80-be0c-11ea-8f51-17b556aec98a.png)

**Comment by sungam3r** [comment]
> with the name **BaseListFilterResponseGraphType_1**

Note that you did not specify the name so it was **inferred** by the library for you. In case of generics this name does not include generic type info. It is by design to not complicate naming doing it awkward. You can always set the graph type name in ctor.

**Comment by manoochehrkateb** [comment]
thanks man
