### ISSUE TITLE
GraphiQL not working behind a reverse proxy (nginx, kubernetes)

### ISSUE THREAD

**Issue by bmmathe** [graphql-dotnet/server#381]
I'm hosting my API in kubernetes which exposes the service URL at a specific path.
For example the base URL for all services is https://s.mycompany.com and the services are exposed at a specify path like https://s.mycompany.com/orders which means the graphql endpoint would be at https://s.mycompany.com/orders/graphql.  

I can hit the graphql URL and see the GraphiQL client interface however all requests from GraphiQL go to https://s.mycompany.com/graphql instead of https://s.mycompany.com/orders/graphql.

Has anyone gotten the GraphiQL interface to work behind a reverse proxy?

**Comment by Shane32** [comment]
Likely fixed in #853 

Please re-open if there are further issues in v7
