### ISSUE TITLE
Method not found: 'Void GraphQL.ExecutionOptions.set_ExposeExceptions(Boolean)

### ISSUE THREAD

**Issue by thefat32** [graphql-dotnet/server#383]
## Description

Execution error after updating deps:

Method not found: Void GraphQL.ExecutionOptions.set_ExposeExceptions(Boolean)

### Steps to reproduce

Updated deps from:

```
    <PackageReference Include="GraphQL" Version="3.0.0-preview-1352" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0027" />
```
to:

```
    <PackageReference Include="GraphQL" Version="3.0.0" />
    <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="3.5.0-alpha0073" />
```

Using option ExposeExceptions = true

```
            services.AddGraphQL(options =>
            {
                options.ExposeExceptions = true;
            });
```

### Expected result

Not to crash

### Actual result

Crash with:

Method not found: 'Void GraphQL.ExecutionOptions.set_ExposeExceptions(Boolean)

### Environment
Windows 10 64-bit
.NETCore 3.1

**Comment by ssougnez** [comment]
Hello,

any idea how long is "shortly" :-D
Not to rush you but I need to plan a release and I'd be glad to use the new version of GraphQL libraries :-)

Thanks

**Comment by Shane32** [comment]
I think @sungam3r said he was going to do this next week.... see https://github.com/graphql-dotnet/graphql-dotnet/issues/1847

**Comment by ssougnez** [comment]
Awesome, thanks 👍

**Comment by sungam3r** [comment]
I will post a new package today or tomorrow.
