### ISSUE TITLE
MissingMethodException using SystemTextJson package

### ISSUE THREAD

**Issue by adamjones1** [graphql-dotnet/server#387]
I'd like to expose a GraphQL schema over ASP.Net Core 3. As per the advice in this repo's readme, I'm referencing GraphQL.Server.Transports.AspNetCore.SystemTextJson, using 3.5.0-alpha0073 because of the readme's warnings on 3.4.0 and also because there're no stable versions published on nuget anyway. The readme further says that this is incompatible with GraphQl 2.4.0, so I'm also referencing version 3.0.0 of the GraphQl package. 

However, when launch my app and try to query the `/graphql` endpoint, I get a MissingMethodException on `GraphQL.ExecutionOptions.set_ExposeExceptions(bool)` from ``GraphQL.Server.Internal.DefaultGraphQLExecuter`1.GetOptions``. I can see from the source that this property appears to have existed in GraphQl 2.4.0 but has been removed in 3.0.0, and indeed the latest version of the SystemTextJson package references GraphQl 2.3.0.

So I'm a bit confused - to use this in ASP.Net Core 3, which packages should I be using?

**Comment by sungam3r** [comment]
See #1847

> the latest version of the SystemTextJson package references GraphQl 2.3.0.

![изображение](https://user-images.githubusercontent.com/21261007/93031323-65816d00-f632-11ea-9433-fd68f0f881bb.png)

**Comment by sungam3r** [comment]
Please try one of the latest releases https://github.com/graphql-dotnet/server/releases .
