### ISSUE TITLE
When 3.5 and/or 4.0 version would be released?

### ISSUE THREAD

**Issue by 1ronclad** [graphql-dotnet/server#389]
More than 18 months has passed since 3.4 release. 3.5 is in alpha for quite a long time now and I see that 4.0 tag has been created

We don't want to stick with alpha release for too long, so would be nice to understand which version is coming next & when would that be.

**Comment by Shane32** [comment]
4.0 should be released this week, compatible with the newly released 3.0 version of GraphQL.NET. It is essentially the final version of the 3.5 alpha.

**Comment by sungam3r** [comment]
I have problems with AppVeyor 4.0 release. I need some time to investigate.

**Comment by Shane32** [comment]
@sungam3r  Lmk if you need help -- that is, I can probably help get it building and publishing to nuget with GitHub Actions, if you want to switch.

**Comment by sungam3r** [comment]
Wouldn't it take longer than solving the AppVeyor issue? Maybe I'm just doing something wrong. I would not want to change the entire CI because of this.

**Comment by Shane32** [comment]
Well, not for me, because I can copy and paste a GitHub action script that I know works. I don’t know anything about appveyor. Anyone that knows appveyor should be able to fix it easier than replace it.

**Comment by sungam3r** [comment]
Ok. Let's do it.

**Comment by Shane32** [comment]
See #391
