### ISSUE TITLE
New 4.0.1 versions on NuGet with invalid GraphQL reference

### ISSUE THREAD

**Issue by bp74** [graphql-dotnet/server#397]
Hi,

All the 4.0.1 versions on NuGet do reference a GraphQL version 3.0.0.2026 which is not published. There is only the GraphQL version 3.0.0 (which probably should be referenced anyway).

https://www.nuget.org/packages/GraphQL.Server.Core/4.0.1

Thanks for releasing a stable version number anyway!

**Comment by sungam3r** [comment]
I published [3.0.0.2026](https://www.nuget.org/packages/GraphQL/3.0.0.2026). I think that such a version is not [semver](https://semver.org/) compatible but it just works.

> (which probably should be referenced anyway).

Agree. I Published 3.0.0.2026 so as not to detain you and anyone else. We have yet to put the CI in order.

**Comment by bp74** [comment]
Thanks, but now the next problem occurred :)

NU1102: Unable to find package GraphQL.SystemTextJson with version (>= 3.0.0.2026)
  - Found 4 version(s) in nexus.admiral [ Nearest version: 3.0.0 ]
  - Found 4 version(s) in nuget.org [ Nearest version: 3.0.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages
NU1102: Unable to find package GraphQL.NewtonsoftJson with version (>= 3.0.0.2026)
  - Found 4 version(s) in nexus.admiral [ Nearest version: 3.0.0 ]
  - Found 4 version(s) in nuget.org [ Nearest version: 3.0.0 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages

**Comment by sungam3r** [comment]
Published, GraphQL.NewtonsoftJson as well.

**Comment by reureu** [comment]
Would you consider releasing a GraphQL.Server.Core 4.0.2 that has the corrected reference to GraphQL 3.0.0 ?
Kind regards,
Reureu

**Comment by reureu** [comment]
Just seen #400. It looks good! 👍

**Comment by sungam3r** [comment]
Well, not good enough yet. I have problems with versioning.

**Comment by reureu** [comment]
@sungam3r ,
Do you want to tell us more about this versioning issue? Would it make sense to reopen this issue? Or maybe you could open a new issue to describe this versioning problem, so that we know what's blocking the release of 4.1.0?
Kind regards,
Reureu

**Comment by reureu** [comment]
@sungam3r , 
Any answer about a real 4.1.0 release? I see an alpha release on MyGet, but could we have a valid 4.1.0 release on nuget please? That would be much appreciated.
Thanks!
Reureu

**Comment by sungam3r** [comment]
Sorry, now I have almost no free time to fully support the project. Many tasks are delayed and are on long TODO lists.

**Comment by sungam3r** [comment]
@Shane32 Please close this issue when 4.1.0 is ready.

@reureu  We switched CI to GitHub Actions from AppVeyor. See #417

**Comment by Shane32** [comment]
- 4.0.2 was released with the proper reference to GraphQL.NET 3.0.0
- 4.1.0 was released with a reference to GraphQL.NET 3.1.0
