### ISSUE TITLE
GraphQL.Server.Transports.AspNetCore.SystemTextJson extension not applied nodatime converters.

### ISSUE THREAD

**Issue by RomanCharnashei** [graphql-dotnet/server#401]
When try to use GraphQL.Server.Transports.AspNetCore.SystemTextJson extention with extension nodatime I did not got expectited iso format. Here is code.
`            services.AddGraphQL((options, provider) =>
            {
                options.EnableMetrics = false;
            })
            .AddGraphTypes(typeof(AppSchema))
            .AddSystemTextJson(null, serializerSettings => 
            {
                serializerSettings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
            })
            .AddDataLoader();
`
But if I apply nodatime converters for IMvcBuilder (in Startup) then this gives me expected result.
expected format for LocalDateTime is YYYY-MM-DDTHH:mm:ss but I got MM/DD/YYYY HH:mm A.
Package for nodatime: NodaTime.Serialization.SystemTextJson.
Enviorment:
asp net core 3.1.6
graphql is 3.0.0.2026 version.
all graphql.server dependency 4.0.1
NodaTime.Serialization.SystemTextJson  1.0.0
NodaTime 3.0.0

**Comment by sungam3r** [comment]
Maybe this question should be asked in nodatime extension repo? I have nothing to say about `ConfigureForNodaTime` method and its internals.

**Comment by RomanCharnashei** [comment]
OK, You may be right. But I would like to make sure that you checked or created some tests regarden following method: 
`serializerSettings.Converters.Add();`, that it work as expected in your extension.

**Comment by nikita-lobkov** [comment]
Got the same problem with nodatime convertors.
What information should I provide in order to investigate this issue?

**Comment by Shane32** [comment]
A sample repo that demonstrates the failure would be ideal.  For instance, you could fork this project, make a new branch, and make a minimum number of changes in the included Harness sample to demonstrate the problem.

**Comment by Shane32** [comment]
As it is now, there really isn't enough information about the problem to offer suggestions, much less begin an investigation.

**Comment by sungam3r** [comment]
> A sample repo that demonstrates the failure would be ideal. 

Or just a unit test with added converter.

**Comment by sungam3r** [comment]
Closed after a month of inactivity and due to the lack of feedback. Feel free to reopen.
