### ISSUE TITLE
Hosting on IIS as a subsite

### ISSUE THREAD

**Issue by RaySheikh** [graphql-dotnet/server#403]
Hello,
I am having an issue publishing the site. Is there a way to manually configure the GraphQL endpoint as a subsite. Currently it auto defaults to the site root.
Result is 404.

eg: http://siteroot.com/**subsite**/graphql returns 404

**Comment by redplane** [comment]
Still happens in 2022

**Comment by Shane32** [comment]
Tested as working in v7, so long as within the UI endpoint options, you use a relative path.
