### ISSUE TITLE
Enabling Metrics via HTTP Header

### ISSUE THREAD

**Issue by kiran94** [graphql-dotnet/server#404]
### Summary

At the moment, it seems like Metrics are only enabled when they are set it in [`options.EnableMetrics`](https://github.com/graphql-dotnet/graphql-dotnet/blob/2f2c23f46c507e633002c5cd952ec1bb2b895335/src/GraphQL.Harness/GraphQLSettings.cs#L11) inside `AddGraphQL` so that when it hits the [GraphQLMiddleware](https://github.com/graphql-dotnet/graphql-dotnet/blob/8d6f7d046335b601dc2128bc6813bb8228b4b55a/src/GraphQL.Harness/GraphQLMiddleware.cs#L67) we enable it.  However if I wanted to enable metrics temporarily to trace something then I would need to redeploy my application or I could hook it up to my `appsettings.json`. This approach will however turn it on for every request coming into the server. 

I'd like to find a way to enable a metrics for just my request without any redeployment. I though that providing a specific HTTP header might be a good option. i.e I provide `X-GRAPHQL-METRICS` and metrics are enabled for that specific request.

### Basic example

I looked inside `GraphQLMiddleware` and found that we could do this by putting something [here](https://github.com/graphql-dotnet/graphql-dotnet/blob/8d6f7d046335b601dc2128bc6813bb8228b4b55a/src/GraphQL.Harness/GraphQLMiddleware.cs#L57) like:

```cs
_settings.EnableMetrics = _settings.EnableMetrics || context.Request.Headers.ContainsKey("X-GRAPHQL-METRICS");
```

I'm not sure if we've purposely not done this or if it's a good fit within the library, but I think it would give users some additional flexibility with Metrics.

### Motivation

Enable Metrics on a request basis if a user requires it without impacting other clients.

**Comment by sungam3r** [comment]
Good suggestion. Now you can use this workaround:
```c#
 public class MyGraphQLExecuter<TSchema> : DefaultGraphQLExecuter<TSchema>
    {
        private readonly IHttpContextAccessor _accessor;

        public MyGraphQLExecuter(
           TSchema schema,
           IDocumentExecuter documentExecuter,
           IOptions<GraphQLOptions> options,
           IEnumerable<IDocumentExecutionListener> listeners,
           IEnumerable<IValidationRule> validationRules,
           IHttpContextAccessor accessor
           ) : base(schema, documentExecuter, options, listeners, validationRules)
        {
            _accessor = accessor;
        }

        protected override ExecutionOptions GetOptions(string operationName, string query, Inputs variables, IDictionary<string, object> context, IServiceProvider requestServices, CancellationToken cancellationToken)
        {
            var options = base.GetOptions(operationName, query, variables, context, requestServices, cancellationToken);

            options.EnableMetrics = _accessor.HttpContext.Request.Headers.ContainsKey("X-GRAPHQL-METRICS");
                
            return options;
        }
    }
```

Also add `services.AddTransient(typeof(IGraphQLExecuter<>), typeof(MyGraphQLExecuter<>));` before `AddGraphQL`

**Comment by kiran94** [comment]
@sungam3r Thanks! I will use this as a workaround for now.

**Comment by sungam3r** [comment]
Recommended way of doing this for v7:
```c#
public static class GraphQLBuilderMetricsExtensions
{
        public static IGraphQLBuilder EnableMetricsByHeader(this IGraphQLBuilder builder, string headerName = "X-GRAPHQL-METRICS")
        {
            return builder.ConfigureExecution(async (options, next) =>
            {
                if (!options.EnableMetrics)
                {
                    var accessor = options.RequestServices.GetRequiredService<IHttpContextAccessor>();
                    options.EnableMetrics = accessor.HttpContext.Request.Headers.ContainsKey(headerName);
                }
                return await next(options).ConfigureAwait(false);
            });
        }
}
```

**Comment by sungam3r** [comment]
Closed as answered. Now is tracked by https://github.com/graphql-dotnet/graphql-dotnet/pull/3232.
