### ISSUE TITLE
Release page not up to date

### ISSUE THREAD

**Issue by reureu** [graphql-dotnet/server#405]
Hi there,

This issue is only about release documentation. 
I've just seen that the release page still mentions v 3.4 as latest release.
https://github.com/graphql-dotnet/server/releases

As v4.0.1 was released more than one month ago, it would be a good idea to update the release page accordingly.
This would also notify watchers of this page.

Thanks!
Reureu

**Comment by sungam3r** [comment]
I will deal with this in the coming days.

**Comment by sungam3r** [comment]
Well, release page was updated by @Shane32. We will make releases more frequently because they are automated with GitHub Actions. I'm going to publish 4.2.0 release with #372 tomorrow.

**Comment by Shane32** [comment]
Yes, I updated the repo releases list
