### ISSUE TITLE
Your o someone know explained course to implement JWT with login?

### ISSUE THREAD

**Issue by AAIING** [graphql-dotnet/server#406]
Hi community!

i seeking information to how apply json web token with login user without big results

someone know? pay for it !!

**Comment by AAIING** [comment]
> This question is not related to GraphQL.NET itself.

yes i do

**Comment by OpenSpacesAndPlaces** [comment]
If you're talking about purely adding JWT to a .Net site - there's lots of sample out there for doing this in .Net Core with Identity Core - should be straightforward. If you're talking about shimming JWT into .Net Framework - that's possible, but it's a fair bit custom coding unless someone has come out with a package for simplifying things there.

**Comment by AAIING** [comment]
thanks for your responses, i founded a course in udemy with complete auth with login

[https://www.udemy.com/share/102wPuBEMZclxbQn4=/](url)
