### ISSUE TITLE
NullReferenceException 

### ISSUE THREAD

**Issue by STRATZ-Ken** [graphql-dotnet/server#420]
###  Description

I have a very large GraphQL API server.  Upon fixing some issues with a Sentry reporting agent, I am finally getting my errors in Sentry.  I recently found a NullReferenceException which is coming with little to know information.

```
System.NullReferenceException: Object reference not set to an instance of an object.
  File "/home/runner/work/graphql-dotnet/graphql-dotnet/src/GraphQL/Execution/ExecutionHelper.cs", line 68, col 17, in GetFieldDefinition
  File "/home/runner/work/graphql-dotnet/graphql-dotnet/src/GraphQL/Execution/ExecutionStrategy.cs", line 87, col 9, in SetSubFieldNodes
  File "/home/runner/work/graphql-dotnet/graphql-dotnet/src/GraphQL/Execution/ExecutionStrategy.cs", line 280, col 9, in CompleteNode

```
### Steps to reproduce

I am not really sure.  Due to my logging being broken for so long, I am not sure when this started.  I was on the pre-release of 3.0.0, which it occurred. I just upgraded to 3.1.0 and it still occurs.  

### Environment

IIS
.Net Core 3.1
Entity Framework
WebSockets (GraphQL)
Windows Server 2012 R2.

**Comment by sungam3r** [comment]
Well, we need a minimum repro to move on. For now I can see this
![изображение](https://user-images.githubusercontent.com/21261007/97240282-ee2d2480-17fe-11eb-9776-0c27c79d9d18.png)

So, no `NullReferenceException` can happen on line 68.

**Comment by STRATZ-Ken** [comment]
I would be happy to try a build for you, I am not even sure how/why its happening.  :/

**Comment by sungam3r** [comment]
@STRATZ-Ken Do you have additional information?

**Comment by STRATZ-Ken** [comment]
Sorry all, I was away.  

I have not been able to replicate this.  I am still having the issue, almost to the point of spamming the console, so I have turned the error off for not to prevent it from spamming my logs.

**Comment by Shane32** [comment]
Can you provide the exact version of graphql-dotnet that you are currently using, with another copy of the stack trace (in case it is reporting on another line than previously)?

**Comment by Shane32** [comment]
Is your schema and graph types all registered as singletons?  Is there any possibility that some are registered as scoped while some are registered as singletons?

**Comment by sungam3r** [comment]
Closed as stale.
