### ISSUE TITLE
WebSocketException

### ISSUE THREAD

**Issue by STRATZ-Ken** [graphql-dotnet/server#421]
Recently, I started adding Subscriptions to my GraphQL API .Net Core 3.1 server.

I just started seeing these messages.

`The WebSocket is in an invalid state ('Aborted') for this operation. Valid states are: 'Open, CloseReceived, CloseSent'`

Is this for any concern?  Getting thousands of them, and not sure if I should just ignore them.

**Comment by sungam3r** [comment]
We have similar errors in other issues somewhere. I had plans to do them, but no guarantees.

**Comment by STRATZ-Ken** [comment]
This is resolved in the latest version of V5.0 Websockets (New package Subscription.Websockets).

**Comment by STRATZ-Ken** [comment]
See #255
