### ISSUE TITLE
Even though the Subscription has stopped, the Server keeps on sending data to the Client

### ISSUE THREAD

**Issue by samyhrer** [graphql-dotnet/server#43]
Problem: 
Data for stopped subscriptions continues to flow to the Client.

Version:
Master branch

How to reproduce:
We are using the Apollo client with React, and the faulty behavior occurs when we unmount and remount components that subscribe to data. We attached an image that shows the issue in the Network Panel in Chrome

Suggested fix:
So far we have not debugged the codebase, but just wanted to raise the issue. You might immediately know what is going on. Let us know if you need help to further investigate this issue. We can provide a small test project that reproduces the problem.

![stream-after-stop](https://user-images.githubusercontent.com/186749/34296228-ea1012b6-e711-11e7-85be-6b554f0e17cd.png)

**Comment by pekkah** [comment]
I think I'm not disposing the subscription when connection closed. I'll fix it beginning of next week once I return from my vacation. Thank you for reporting.

**Comment by pekkah** [comment]
Subscription to the observable was not disposed when stop message was received. Can you try out the latest version and observer if the behavior is now correct.

**Comment by samyhrer** [comment]
Seems to be correct now. Thanks alot.
