### ISSUE TITLE
Include extensions for ASP.NET Core 3.x Endpoints for easy use of Authorization

### ISSUE THREAD

**Issue by danielwertheim** [graphql-dotnet/server#430]
Been looking for information on how-to make use of `Endpoints` in ASP.NET Core 3.x to hook in the middleware. Was expecting it to exist in the library. Is there something similar to the sample below? If not, is it worth a PR or worth to be included in docs somewhere?

```csharp
    public static class GraphQlEndpointRouteBuilderExtensions
    {
        public static IEndpointConventionBuilder MapGraphQl<TSchema>(
            this IEndpointRouteBuilder endpoints, 
            string pattern = "/graphql") where TSchema : ISchema
        {
            var pipeline = endpoints
                .CreateApplicationBuilder()
                .UseMiddleware<GraphQLHttpMiddleware<TSchema>>(new PathString())
                .Build();
                
            return endpoints.Map(pattern, pipeline);
        }
    }
```

Which then allows you to do the following in e.g. `Startup`:

```csharp
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
{
    if (env.IsDevelopment())
    {
        app.UseDeveloperExceptionPage();
    }

    app.UseHttpsRedirection();

    app.UseRouting();

    app.UseAuthorization();

    app.UseEndpoints(endpoints =>
    {
        endpoints
            .MapGraphQl<PetsSchema>()
            .RequireAuthorization();
    });
}
```

**Comment by sungam3r** [comment]
> .UseMiddleware<GraphQLHttpMiddleware<TSchema>>(**new PathString()**)

See `GraphQLHttpMiddleware.InvokeAsync`:
```c#
 public async Task InvokeAsync(HttpContext context)
        {
            if (context.WebSockets.IsWebSocketRequest || !context.Request.Path.StartsWithSegments(_path))  <--------------
            {
                await _next(context);
                return;
            }
```

What about `PathString path` argument in `GraphQLHttpMiddleware` ? Does this mean that it is now simply not needed and should be removed?

**Comment by sungam3r** [comment]
@Shane32 Are you familiar with `UseRouting` and `UseEndpoints` APIs ? It seems to me that we need to remove path parameter from middleware and `context.Request.Path.StartsWithSegments(_path)` from `InvokeAsync`. I've seen other issues related to this check. I'm sure this check is wrong to do inside middleware.

**Comment by Shane32** [comment]
@sungam3r No I have not, although we should investigate; I just don't have the time now.  (I want to learn more about those APIs.)

**Comment by sungam3r** [comment]
OK. I checked https://docs.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-3.1 and it will be 100% breaking changes. I would like to do it after #334.

**Comment by danielwertheim** [comment]
Did a quick test using the above as an extension method and that worked without any internal changes. Also was able to serve at other URL. I guess you also could pass the string downwards to not affect any internals as of now and then not be breaking.

**Comment by danielwertheim** [comment]
On the other hand, in order to not having to support it as of now, I guess you could document it somewhere.

**Comment by sungam3r** [comment]
I am working on routing support. Almost done.

**Comment by sungam3r** [comment]
@danielwertheim  #440 was merged in `develop`. You can download preview packages [here](https://github.com/orgs/graphql-dotnet/packages?repo_name=server). Could you check your case?

**Comment by sungam3r** [comment]
Closed due to the lack of feedback. @danielwertheim v5 will be published soon with all routing changes.
