### ISSUE TITLE
Possibility to add "GraphiQL Explorer"?

### ISSUE THREAD

**Issue by varasinp** [graphql-dotnet/server#451]
I would like to know if there is a plan to include GraphiQL Explorer (part of GraphiQL).
GraphiQL Explorer is very useful. It allows users to point and click on GraphQL node and it auto-generate the query.
Here's the example of GraphiQL Explorer https://api.spacex.land/graphql/

**Comment by sungam3r** [comment]
I've seen this UI somewhere. GraphiQL middleware just returns "simple" html - https://github.com/graphql-dotnet/server/blob/master/src/Ui.GraphiQL/Internal/graphiql.cshtml. I am not an expert in JS and frontend. Do you know how to change html? Are more serious server side changes required to support this functionality?

**Comment by varasinp** [comment]
Sorry, I'm not an expert when it comes to front-end stuff like JavaScript or TypeScript. However, I don't believe there's a need to change a lot of code on the server-side. I believe only the GraphiQL version update is required.

I look into the "graphiql.cshtml" file that you mentioned and I noticed this (line 42 & 43)

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/graphiql/0.13.0/graphiql.min.js"></script>
```
As you can see, the graphiql version is "0.13.0" which is the older version. Maybe all that needs to be done is just to use the latest version which is "1.0.6"? https://cdnjs.com/libraries/graphiql 

So line 42 & 43 in "graphiql.cshtml" should be modified to use version "1.0.6" instead probably. I hope that's will do it but I didn't try that myself just yet.
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/graphiql/1.0.6/graphiql.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/graphiql/1.0.6/graphiql.min.js"></script>
```

I went to the https://github.com/graphql/graphiql and I saw this picture. They specicy GraphiQL Explorer as an external key (not sure what that means)
![GraphiQL](https://raw.githubusercontent.com/graphql/graphiql/main/resources/images/current-ecosystem.jpg)

If this work, maybe others UI (Altair, Playground, Voyager) need a version update also probably?

**Comment by varasinp** [comment]
Just want to confirm that upgraded GraphiQL from version 0.13.0 to 1.0.6 did not add the GraphiQL Explorer to the GraphiQL UI. 
The HTML body section of this file you mentioned https://github.com/graphql-dotnet/server/blob/master/src/Ui.GraphiQL/Internal/graphiql.cshtml needs to be updated to include the explorer.

**Comment by imolorhe** [comment]
It should only require frontend changes, no change required on the server side. I could help to add it to GraphiQL.

Ps: It should be available in [Altair GraphQL](https://graphql-dotnet.github.io/docs/getting-started/altair-graphql/) as a beta plugin.

<img width="1440" alt="Screenshot 2020-11-18 at 1 51 15 AM" src="https://user-images.githubusercontent.com/4608143/99468344-a488b300-2940-11eb-860d-fc5edec0f651.png">

**Comment by varasinp** [comment]
If you can add it to GraphiQL, that would be great!
I'm also very interested in Altair. Could you please guide me on how to get that beta plugin? Does that mean if I add the code to use GraphQLAltair (see below) the Explorer will automatically be shown in Altair UI?

```C#
public void Configure(IApplicationBuilder app, IHostingEnvironment env)
{
    app.UseGraphQLAltair();
}
```

**Comment by imolorhe** [comment]
Created the PR for GraphiQL

**Comment by sungam3r** [comment]
Done in #455 
https://github.com/graphql-dotnet/server/releases/tag/4.3.1
