### ISSUE TITLE
GraphQL.Server.GraphQLBuilderExtensions class is defined multiple times in different assemblies

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/server#456]
[GraphQL.Server.GraphQLBuilderExtensions in GraphQL.Sever.Authorization.AspNetCore assembly](https://github.com/graphql-dotnet/server/blob/master/src/Authorization.AspNetCore/GraphQLBuilderExtensions.cs)
[GraphQL.Server.GraphQLBuilderExtensions in GraphQL.Sever.Core assembly](https://github.com/graphql-dotnet/server/blob/master/src/Core/GraphQLBuilderExtensions.cs)

This may be the cause of some issues such as in #353 because it becomes near impossible to reference methods from both.

**Comment by infogulch** [comment]
Also here: https://github.com/graphql-dotnet/server/blob/master/src/Transports.AspNetCore.NewtonsoftJson/GraphQLBuilderExtensions.cs

**Comment by infogulch** [comment]
For others' reference, I was able to work around this issue by setting up alias support in package references.

1. Add the following content into `Directory.Build.targets`:

    ```
    <Project>
      <Target Name="AddPackageAliases" BeforeTargets="ResolveReferences" Outputs="%(PackageReference.Identity)">
        <PropertyGroup>
          <AliasPackageReference>@(PackageReference->'%(Identity)')</AliasPackageReference>
          <AliasName>@(PackageReference->'%(Alias)')</AliasName>
        </PropertyGroup>
    
        <ItemGroup>
          <ReferencePath Condition="'%(FileName)'=='$(AliasPackageReference)'">
            <Aliases>$(AliasName)</Aliases>
          </ReferencePath>
        </ItemGroup>
      </Target>
    </Project>
    ```

2. Add the newly defined alias attribute to the offending package.  (Note the `Alias="GraphQLServerAuthorization"` part):

    ```
    <Project Sdk="Microsoft.NET.Sdk.Web">
    ...
      <ItemGroup>
        <PackageReference Include="GraphQL" Version="3.1.5" />
        <PackageReference Include="GraphQL.Server.Authorization.AspNetCore" Version="4.3.1" Alias="GraphQLServerAuthorization" />
    ...
    ```

3. In Startup.cs add extern alias reference on the *first line*

    ```
    extern alias GraphQLServerAuthorization;
    ```

4. Use the builder extension by fully qualifying the namespace of the extension method

    ```
        var builder = services.AddGraphQL(opt =>
            {
                opt.ComplexityConfiguration = new GraphQL.Validation.Complexity.ComplexityConfiguration
                {
                    MaxDepth = 15,
                    MaxComplexity = 10,
                };
            })
            .AddSystemTextJson()
            .AddGraphTypes(ServiceLifetime.Scoped);

        GraphQLServerAuthorization::GraphQL.Server.GraphQLBuilderExtensions.AddGraphQLAuthorization(builder, options =>
        {
            options.DefaultPolicy = new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build();
        });
    ```

**Comment by sungam3r** [comment]
I agree that in general, extension method classes should have distinguished names to avoid naming conflicts. But I don't understand what kind of conflict you are talking about. All methods have different names, although they are located in classes with the same name. Please clarify.

**Comment by infogulch** [comment]
The problem isn't that the class name is the same, the problem is that the *fully qualified* name is the same for all of them: `GraphQL.Server.GraphQLBuilderExtensions`.  The C# compiler cannot reference multiple classes with the same fully qualified name (including namespace), even if the methods themselves have different names.  The fact that they are extension methods is immaterial -- extension methods are just syntax sugar, the class still has to be referenced by the compiler.

**Comment by infogulch** [comment]
Well, upon further investigation it seems I need to walk back some of my claims here.  I attempted to reproduce the issue by adding `AddGraphQLAuthorization` and `AddUserContextBuilder` to the Samples.Server project in this repo, with no luck.  I also tried changing all project references to package references of the latest version (4.3.1), also without issue.

However, if I add `using ext = GraphQL.Server.GraphQLBuilderExtensions;` to `GraphQL.Samples.Server.Startup.cs`, I do get an error:

```
Build FAILED.

Startup.cs(15,28): error CS0433: The type 'GraphQLBuilderExtensions' exists in both 'GraphQL.Server.Authorization.AspNetCore, Version=4.3.1.0, Culture=neutral, PublicKeyToken=null' and 'GraphQL.Server.Core, Version=4.3.1.0, Culture=neutral, PublicKeyToken=null' [C:\projects\graphql-dotnet-server\samples\Samples.Server\Samples.Server.csproj]
    0 Warning(s)
    1 Error(s)
```

There may be some other peculiarity I'm encountering in my project that is preventing me from referencing the `AddGraphQLAuthorization` extension naturally.  (Maybe mismatched versions? I'll try to isolate it.)  Whatever its origin, I was unable to reference `AddGraphQLAuthorization` at all until I found the workaround I mentioned in my previous comment.

**Comment by sungam3r** [comment]
What you describe is [_using alias directive_](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-directive). Of course the compiler reports an error because it doesn't know what type you are referring to. But this problem is completely different from the "usual" use of the extension methods of these classes (at least until we add two identical methods).

**Comment by sungam3r** [comment]
I really see no reason to use alias. `using GraphQL.Server;` is quite enough for calling whichever extension method.

**Comment by infogulch** [comment]
I mentioned the using statement to demonstrate that the names clash, I'm not saying this is a normal way to use extension methods.

**Comment by sungam3r** [comment]
Done in #461
