### ISSUE TITLE
There is already one outstanding 'ReceiveAsync' call for this WebSocket instance

### ISSUE THREAD

**Issue by sergiogarciadev** [graphql-dotnet/server#458]
I am getting a lot of logs with this message in production:

> There is already one outstanding 'ReceiveAsync' call for this WebSocket instance. ReceiveAsync and SendAsync can be called simultaneously, but at most one outstanding operation for each of them is allowed at the same time.

The exception is throw by [src/Transports.Subscriptions.WebSockets/WebSocketReaderPipeline.cs:110](https://github.com/graphql-dotnet/server/blob/665257cb2bd21631f512960a7c2a39d8d8f7d506/src/Transports.Subscriptions.WebSockets/WebSocketReaderPipeline.cs#L110)

I am trying to reproduce this but have no success yet.

**Comment by sungam3r** [comment]
In theory it can happen if you somehow pass the same socket info `IWebSocketConnectionFactory.CreateConnection(WebSocket, string)` or just call `new WebSocketReaderPipeline(WebSocket, JsonSerializerSettings)` twice on the same socket. I made this conclusion after a quick look at the code. I am not an expert in websockets.

**Comment by Shane32** [comment]
This should not occur in v7.  Please re-open if there are continuing problems in v7.
