### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by joemcbride** [graphql-dotnet/server#46]
I think we should add logging using .NET Core Logging for the following:

* Queries
* Errors

**Comment by pekkah** [comment]
* Use structured logging instead of string interpolation

**Comment by terjebra** [comment]
Logging of queries and errors in the middleware would be great, but perhaps a more generic approach, like a custom handler, that is invoked by the middleware, might be something to consider as well. For instance, if I want to do more extensive logging, like including request information (IP-address, current user etc), or do some other postprocessing that requires access to the execution errors. With the current middlware this is not straightforward.  I'm not sure about the best way to solve this, but maybe a callback (for instance an action delegate on the GraphQLHttpOptions) that is invoked by the middleware with the errors could work. Any thoughts?

**Comment by KreativJos** [comment]
This would be very nice indeed.
To accomplish this myself, I created my own middleware for GraphQL, copying the code from the repository and using DI for getting the logger.
This works fine, but isn't great, because I have to merge the code by hand once in a while (too many changes by now).

**Comment by pekkah** [comment]
Improved in 3.0

**Comment by FrankyBoy** [comment]
If you are talking about this https://github.com/graphql-dotnet/server/blob/7c2091caea7b12a90a8e0ffb73b9cc1360eefe8a/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L92 I think this could see some more improvements. It would be great to allow to inject some custom handler here to handle different types of errors and such (eg. client vs server errors and such). 

Cheers :)

**Comment by AmbroiseCouissin** [comment]
Hi there! For some reason, logs are not being sent (console & serilog -> elastic search) when errors.

Do you have a small sample to show how to inject properly the Loggers inside the GraphQLHttpMiddleware?

Here's my code 
```
        public Startup(IConfiguration configuration, IHostingEnvironment environment)
        {
            Configuration = configuration;
            Environment = environment;

            Log.Logger = new LoggerConfiguration()
                .Enrich.FromLogContext()
                .MinimumLevel.Debug()
                .MinimumLevel.Override("Microsoft", LogEventLevel.Information)
                .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level}] {SourceContext}{NewLine}{Message:lj}{NewLine}{Exception}{NewLine}", theme: AnsiConsoleTheme.Literate)
                .WriteTo.Elasticsearch(new ElasticsearchSinkOptions(new Uri($"{Configuration["serviceUrls:logging"]}"))
                {
                    MinimumLogEventLevel = LogEventLevel.Information,
                    AutoRegisterTemplate = true
                })
                .CreateLogger();
        }
```

and 

```
app.UseGraphQL<MySchema>("/graphql");
```

Any clue?

**Comment by lucax88x** [comment]
Got same problem, how to get propert logging?
