### ISSUE TITLE
How to pass websocket header /http header for subscriptions via Playground ?

### ISSUE THREAD

**Issue by MatheswaranSagadevan** [graphql-dotnet/server#460]
Play ground provides the http header section, and the header variable added in this section are working fine for Query and Mutation.
When I tried to use the same http header section for passing header value for my subscription request, it does not take the parameter...

what is the ideal way to solve this ?

**Comment by MatheswaranSagadevan** [comment]
any updates?

**Comment by MatheswaranSagadevan** [comment]
Gentle Reminder ..

**Comment by sungam3r** [comment]
See https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md . You can pass additional payload in GQL_CONNECTION_INIT event. Actually GraphQL Playground already does it. If you expected to receive your data in headers on the server, then you will not find it there. You can add `IOperationMessageListener` and handle `OperationMessage` with `Type`=`MessageType.GQL_CONNECTION_INIT` and then deserialize `Payload` property. It will be your data.

**Comment by MatheswaranSagadevan** [comment]
your suggestion is valid Sungam. But my requirement is to deal with request headers.
1) I need to pass the request headers for both Http and ws.
2) and I will pass the request header through some proxy server. so it is not good to add the additional payload in proxy server.
3) my asp.net core web server will have the middleware to check the request headers. (of course, this 3rd point can be done as you suggested, ws with messagehandling context (operationlisteners) and http some user context builders etc, but we do not prefer multiple implementation for simple request header extraction.)

To test this, I am using play ground and some graphql client for unit tests.

so both Playground and GraphQL Client does not accept the request headers for web socket connections. :(

**Comment by Shane32** [comment]
@MatheswaranSagadevan It is impossible to pass an Authorization header (or any other custom headers) within a WebSocket connection from a browser.  This is a limitation of current browsers available today, and not the fault of Playground or GraphQL.NET Server.  This is why the `GQL_CONNECTION_INIT` message exists; to allow the browser to pass authorization or other setup information to the server prior to requests being executed.

Within GraphQL.NET Server version 7, you can easily write code to set the `HttpContext.User` property and/or user context based on the `GQL_CONNECTION_INIT` message payload.  This is fully documented in the readme file.  I plan to write a sample application using JWT authentication but have not done so yet.

**Comment by Shane32** [comment]
Closing as answered; but please re-open if you have further questions.
