### ISSUE TITLE
Enable calling AuthorizeWith() on a Schema directly

### ISSUE THREAD

**Issue by infogulch** [graphql-dotnet/server#463]
Calling `this.AuthorizeWith(MYPOLICY)` in the constructor of a class that derives from Schema has no effect.  It took me a while to realize that I had to call it on the Query and Mutation types directly:

```c#
public class MySchema : Schema
{
    public MySchema(IServiceProvider provider)
    {
        // 1. NO
        // this.AuthorizeWith(AuthorizationPolicies.ApiAccessPolicy);

        var schemaText = new[] {
            File.ReadAllText("Schema/Mutation.graphql"),
            File.ReadAllText("Schema/Query.graphql")
        };

        var schema = For(schemaText, _ =>
        {
            _.Types.Include<MutationResolver>("Mutation");
            _.Types.Include<QueryResolver>("Query");
            _.ServiceProvider = provider;
        });

        // 2. Yes :)
        schema.Mutation.AuthorizeWith(AuthorizationPolicies.ApiAccessPolicy);
        schema.Query.AuthorizeWith(AuthorizationPolicies.ApiAccessPolicy);

        Mutation = schema.Mutation;
        Query = schema.Query;
    }
}
```

Hence a feature request: change the framework to enable 1. to work.  If we choose to not implement this feature, then I hope that we can change AuthorizeWith to fail when called on a schema since it won't work anyway.

**Comment by sungam3r** [comment]
See `public Task<INodeVisitor> AuthorizationValidationRule.ValidateAsync(ValidationContext context)` and `public class ValidationContext : IProvideUserContext`. `ValidationContext` class has `Schema` property so I think nothing stops us from implementing such a feature. @joemcbride @Shane32 ?

**Comment by Shane32** [comment]
Sounds fine to me. I’ve never used AuthorizeWith FYI.

**Comment by infogulch** [comment]
I published a gist with with something close to the authentication configuration I'm using in my project.  I created it to post a help issue here, but in the process of writing that issue I learned that you can't call AuthorizeWith on Schema, thus this issue is an enhancement instead. :)

https://gist.github.com/infogulch/c23cd77a653cfb794973690d85a1384f

* It calls `AuthorizeWith` on Schema
* It uses ~JWT authentication

@Shane32 do you use a different strategy to authenticate calls to your graphql schema?

**Comment by sungam3r** [comment]
@infogulch Done https://github.com/graphql-dotnet/server/releases/tag/4.4.0

**Comment by infogulch** [comment]
@sungam3r that's great, thank you!
