### ISSUE TITLE
How to enable GraphQL Playgorund on a Production environment?

### ISSUE THREAD

**Issue by raschmitt** [graphql-dotnet/server#464]
I'm creating a sample project in .Net Core 3.1 with a GraphQL API that I'm going to use in a live demo session and I would like to be able to use the Playground in a Production environment.

I've searched the docs on how to do it but found nothing.

How can I achieve so?

Note that I'm running my API on a Docker container, my Dockerfile is as follows:

```docker
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

WORKDIR /src
COPY . ./

WORKDIR /src/GraphQL.Sample.Api
RUN dotnet restore 
RUN dotnet publish -c Release -o out --no-restore

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

COPY --from=build-env /src/GraphQL.Sample.Api/out .
ENTRYPOINT ["dotnet", "GraphQL.Sample.Api.dll"]

EXPOSE 80
```

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server/blob/master/samples/Samples.Server/Startup.cs#L74

**Comment by raschmitt** [comment]
> `app.UseGraphQLPlayground()`
> https://github.com/graphql-dotnet/server/blob/master/samples/Samples.Server/Startup.cs#L74

I'm setting up GraphQL Playground, on my `Startup.cs` just like that.

When I run my code in debug mode through `Visual Studio`, Playground gets initialized as it should, yet when I run it inside my `Docker`container it doens't.

None of the options on the provided sample seems to be able to solve my issue.

You can check out my code here:

https://github.com/raschmitt/graphql-dot-net-sample/blob/master/GraphQL.Sample/GraphQL.Sample.Api/Startup.cs#L58

**Comment by sungam3r** [comment]
Press F12 in your browser and check console output for errors.

**Comment by raschmitt** [comment]
> Press F12 in your browser and check console output for errors.

As I said Playground doesn't get initialized at all. When I try to access it in my browser I simply get a `ERR_CONNECTION_REFUSED`.

**Comment by sungam3r** [comment]
Maybe because of this https://github.com/graphql-dotnet/server/blob/master/src/Ui.Playground/Internal/playground.cshtml#L7-L9 ?

**Comment by sungam3r** [comment]
I've encountered such problems in protected environments.

**Comment by raschmitt** [comment]
Any idea on what can I do about it?

**Comment by raschmitt** [comment]
Any idea on what can I do about it?

**Comment by sungam3r** [comment]
Are you try localhost or <VM IP ADDRESS> to connect?

**Comment by raschmitt** [comment]
> Are you try localhost or `VM IP ADDRESS` to connect?

localhost

**Comment by sungam3r** [comment]
https://stackoverflow.com/questions/36813690/connection-refused-on-docker-container

I think you can try this.

**Comment by raschmitt** [comment]
I don't think my issue is related to docker at all.

I've added a "custom path" to my GraphQL options and it started working inside my container:

```csharp
app.UseGraphQLPlayground(new GraphQLPlaygroundOptions
{
    Path = "/ui/playground",
    HideTracingResponse = true,
});
``` 

Do you have any idea why it works like that? 

I mean my path is just the same as the default path...

**Comment by sungam3r** [comment]
What is your Ui.Playground package version?

**Comment by raschmitt** [comment]
> What is your Ui.Playground package version?

```xml
<PackageReference Include="GraphQL.Server.Ui.Playground" Version="4.3.1" />
```

**Comment by sungam3r** [comment]
> I mean my path is just the same as the default path...

Are you saying that when you add a setter with `/ui/playground`, the code works, but when you remove it it stops?

**Comment by sungam3r** [comment]
I don't know how this can be. The current condition for invoke middleware is 
```c#
private bool IsPlaygroundRequest(HttpRequest httpRequest)
            => HttpMethods.IsGet(httpRequest.Method) && httpRequest.Path.StartsWithSegments(_options.Path);
```

Perhaps, `httpRequest.Path` has some unusual value for some reason?

**Comment by raschmitt** [comment]
> > I mean my path is just the same as the default path...
> 
> Are you saying that when you add a setter with `/ui/playground`, the code works, but when you remove it it stops?

Yes, that is exactly the case, when I try to run my code in a Linux container.

Otherwise, when I run it on development straight from `Visual Studio` on windows it works just fine, with or without the setter.

**Comment by sungam3r** [comment]
You can try the v5 pre-release version of the [packages](https://github.com/orgs/graphql-dotnet/packages?repo_name=server), there it became possible to use ASP.NET Core routing feature. Maybe there behavior will be normal.

**Comment by sungam3r** [comment]
GraphQL.Server.All meta-package is the simplest one to use

**Comment by sungam3r** [comment]
Closed as stale.
