### ISSUE TITLE
Specify services for subscriptions

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#466]
See this line https://github.com/graphql-dotnet/server/blob/master/src/Transports.Subscriptions.Abstractions/SubscriptionManager.cs#L82 and comment https://github.com/graphql-dotnet/graphql-dotnet/issues/2033#issuecomment-738533523

**Comment by Shane32** [comment]
Scoped services is now supported in v7 with documentation in the readme for proper use.  Please re-open if there are further questions.
