### ISSUE TITLE
Changing GraphQLHttpMiddleware components to be public static, so they can be reused without having to use the middleware

### ISSUE THREAD

**Issue by Glaschu** [graphql-dotnet/server#475]
Summary
At the moment,all the code to parse,validate and execute the a query is locked inside a GraphQLHttpMiddleware so if you used a project inside of azure function, the user would have to handle each operation themselves which would make it harder to add to projects that want to take advantage of functions.

I would like find a way to make parts GraphQLHttpMiddleware static functions so they could be called without having to create an instance of GraphQLHttpMiddleware in a function. ie the code inside of the if (isPost) could be made static allowing another user to use the same parser.

Basic example
I looked inside GraphQLMiddleware and found that we could do this by putting something here like:

by changing DeserializeFromFormBody to be in a separate file as static, there is a few items like this in GraphQLMiddleware

Motivation
Make some of the items inside of GraphQLHttpMiddleware public static functions

**Comment by sungam3r** [comment]
I doubt it should be done. The methods you mentioned (DeserializeFromFormBody / DeserializeFromQueryString / DeserializeFromGraphBodyAsync) are small enough to be of little value. In addition, we will increase the surface of the public api, which will require more support. I don't think all changes will be limited to doing some static public methods. Surely azure functions have other features/specifics that will require more and more code changes it this project. Returning to the title of this repo
![изображение](https://user-images.githubusercontent.com/21261007/102714465-b9f65180-42df-11eb-9d50-c703c05cd331.png)
and its purpose, I think the best option is to create a separate project or repo (if it doesn't already exist) specifically for GraphQL in azure functions. We already have this [example](https://github.com/graphql-dotnet/examples/tree/master/src/AzureFunctions) provided by @StefanSchoof . This example can serve as a starting point.

**Comment by sungam3r** [comment]
ping @Shane32 What do you think?

**Comment by Shane32** [comment]
I would not make them public static functions. As @sungam3r indicated, the functionality can be easily replicated. Now with the serialization moved to the main project, it is even easier. And it is trivial to expose protected methods, if such a need arises. 

Ideally for this use case, you’d create a class just for the needs of the azure function code.

**Comment by Shane32** [comment]
I suggest to close as won’t-fix
