### ISSUE TITLE
Question: How Graphql-dotnet server handles the web socket reconnection scenarios ..?

### ISSUE THREAD

**Issue by MatheswaranSagadevan** [graphql-dotnet/server#481]
according asp.net core documentation, server will not be aware of the websocket connection interruptions happened in client side.

But in reality, when we use web sockets for subscriptions using GraphQL dotnet, what is the best way to handle the websocket reconnections ?
1) Client disconnected, server lives
2) Client lives, server disconnected
what is the best way to handle the reconnection scenario...?
How did in GraphQL dotnet already handle this ?

**Comment by sungam3r** [comment]
Hi. These are questions that interest me myself and are part of a large pool of questions that I would like to receive an answer to. Now I am not ready to answer them. Hope someone else can help you. Nevertheless, for a long time now I have not lost hope of finding the time to understand the source code of the websocket and everything related to subscriptions. Perhaps on New Year's holidays I can do it and then it will be included in the v5 which now is under develop.

**Comment by MatheswaranSagadevan** [comment]
Hi sungam3r,
any update on this..?
I'm often facing websocket error in server side, how does the server retry automatically?
kindly do the needful asap.

**Comment by sungam3r** [comment]
Unfortunately I have no answer, I do not have enough time to support all projects. Now I'm working on authorization repository after GraphQL.NET v4 release. After that I plan to continue to work on the server project issues.

**Comment by Shane32** [comment]
In v7, once the GraphQL.NET Server detects that the TCP connection has been terminated, it will shut down (dispose of) any active subscriptions.  Typically either (a) the subscription will attempt to send data, and the TCP subsystem will fail to send the data, or (b) the underlying TCP subsystem will periodically send keep-alive packets which will fail, or (c) a reset packet will be received when the client disconnects.

Note that I have read that the default keep-alive packet timer is 2 hours on Windows/Linux.  I cannot verify this.  Within v7 you may set your own keepalive timer which will cause the server to send WebSocket application-layer keepalive packets at the specified interval.

Please re-open if you have further questions regarding this

**Comment by Shane32** [comment]
Note that there is no way for a server to re-open a channel to a disconnected client.  The client must detect the disconnection and retry the connection.
