### ISSUE TITLE
Extensions Property not added to GraphQLRequest

### ISSUE THREAD

**Issue by tobias-tengler** [graphql-dotnet/server#488]
The `Extensions` property on the `GraphQLRequest` is [not set in the default GraphQLHttpMiddleware](https://github.com/graphql-dotnet/server/blob/80bde26b6e0626a01de5b9d87662a0dc24f4187d/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L122). (I also checked the develop branch - same issue)

Is this intentional or not?

I planned on using the `Extensions` property for [implementing persisted queries](https://github.com/graphql-dotnet/server/issues/352#issuecomment-758597256). I'm probably going to end up writing my own Middleware though so i can process HTTP calls like this `https://example.com/persisted/<hash>`. This would allow me to utilize caching for specific endpoints. Nonetheless I think that other people might depend upon the `Extensions` property on the `GraphQLRequest`.

**Comment by sungam3r** [comment]
@tobias-tengler Thanks. In #372 I just forgot to handle all cases 🤦

**Comment by sungam3r** [comment]
@tobias-tengler Also see #132

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server/releases/tag/4.4.1
