### ISSUE TITLE
Graphql playground trying to get schema from host url instead of whole application url.

### ISSUE THREAD

**Issue by subithal** [graphql-dotnet/server#495]
Here is my application url - https://abc.com/def
graphql endpoint - /demo
playground path - ui/playground

now graphql playground trying to get the schema from **https://abc.com/demo**. 

I tried to change the graphql endpoint like this and Getting 404 error.

graphql endpoint - def/demo (Surprisingly it is working fine in localhost but not in my hosted server)

**Comment by sungam3r** [comment]
Duplicates #184

**Comment by Shane32** [comment]
This does not duplicate #184 but rather is related to #403

#184 relates to relative urls, which are now supported

This issue is still outstanding

**Comment by Shane32** [comment]
Closing, as hosting on a subsite is tested as working in v7, so long as relative paths are used for the UI option's endpoint addresses.  Solved by #853
