### ISSUE TITLE
Supporting unicode characters

### ISSUE THREAD

**Issue by toorajhelmi** [graphql-dotnet/server#500]
I came across an issue where GraphQL breaks when I add an Enum with unicode character in it: Ecole_Polytechnique_Fédérale_de_Lausanne

If I change this to below ( é --> e) it works fine.

Ecole_Polytechnique_Federale_de_Lausanne 

Looks like GraphQL does not support unicode, does it?

**Comment by sungam3r** [comment]
It is a known issue. This is not the first time I have answered this question. See http://spec.graphql.org/June2018/#sec-Names

**Comment by Shane32** [comment]
This is an indication that we need name checking similar to field names. See #2123

**Comment by sungam3r** [comment]
Of course.

**Comment by sungam3r** [comment]
Closed as answered.
