### ISSUE TITLE
Add note and nuget reference for GraphQL.MicrosoftDI

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#501]
https://github.com/graphql-dotnet/graphql-dotnet/pull/2261#issuecomment-774795008

[UPDATE]: Add PackageReference into `GraphQL.Server.All` metapackage.

**Comment by Shane32** [comment]
A nuget reference, not a note

**Comment by sungam3r** [comment]
Was added in the main repo
![изображение](https://user-images.githubusercontent.com/21261007/111788887-a6a05580-88d1-11eb-8af1-bc0c7f8c386e.png)

Also see #523:
![изображение](https://user-images.githubusercontent.com/21261007/111788987-bfa90680-88d1-11eb-96ae-6da117dcc963.png)

All auxilary packages were included in All-metapackage.

**Comment by sungam3r** [comment]
#523 was merged into `develop`.
