### ISSUE TITLE
[GraphiQL] Add headers

### ISSUE THREAD

**Issue by jasonlaw** [graphql-dotnet/server#504]
Hi,

May I know how to add headers with GraphiQL?

Thank you.

**Comment by sungam3r** [comment]
Most likely, this question is worth asking the GraphiQL authors. I found that [thread](https://github.com/graphql/graphiql/issues/500).

**Comment by nur858** [comment]
@jasonlaw Is GraphiQL absolute necessity for you? Otherwise I found [altair](https://github.com/imolorhe/altair) to be much richer UI with ability to add headers.

**Comment by jasonlaw** [comment]
> @jasonlaw Is GraphiQL absolute necessity for you? Otherwise I found [altair](https://github.com/imolorhe/altair) to be much richer UI with ability to add headers.

Not really, but I found the explorer is very convenient.

**Comment by dasco144** [comment]
> > @jasonlaw Is GraphiQL absolute necessity for you? Otherwise I found [altair](https://github.com/imolorhe/altair) to be much richer UI with ability to add headers.
> 
> Not really, but I found the explorer is very convenient.

There does seem to be a plugin that can add a GraphiQL like explorer into Altair.

![image](https://user-images.githubusercontent.com/10575019/111600762-64e0b380-87da-11eb-90eb-656b0487dba2.png)

**Comment by sungam3r** [comment]
Closed as answered.
