### ISSUE TITLE
DefaultGraphQLExecuter incompatibility with graphql-dotnet 4.0.0

### ISSUE THREAD

**Issue by corstian** [graphql-dotnet/server#507]
As additional point of interest for #477;

The `DefaultGraphQLExecuter` assumes it can set some settings it cannot, therefore throwing `MissingMethodException`'s.

See these; 

https://github.com/graphql-dotnet/server/blob/1668688e3ceb47ba4ef2652c2cb4d635dfc5d7d7/src/Core/DefaultGraphQLExecuter.cs#L68

https://github.com/graphql-dotnet/server/blob/1668688e3ceb47ba4ef2652c2cb4d635dfc5d7d7/src/Core/DefaultGraphQLExecuter.cs#L70

**Comment by Shane32** [comment]
GraphQL v4.0 has not been released yet.  Once it has been released (should be very soon), this project will be updated appropriately.

**Comment by Shane32** [comment]
If you would like to assist by creating a PR that targets the develop branch, we would welcome the assistance.  But I think the hold-up is not here but in the graphql-dotnet repo.

**Comment by corstian** [comment]
Okay I'll follow the progress over there, and will keep an eye out on whether I happen to have some free time at the right time!
