### ISSUE TITLE
Mutations over Websocket

### ISSUE THREAD

**Issue by wakemaster39** [graphql-dotnet/server#51]
According to the Apollo web socket transport implementation, a websocket is suppose to be able to handle Queries and Mutation in addition to Subscriptions. I was playing around with attempting to send a mutation over the websocket channel but the response back from this is always a GQL_ERROR package with the payload of both the data and the errors being null, which makes it very difficult to track down where the error actually occurs.

**Comment by pekkah** [comment]
At the moment queries and mutations over websockets are not implemented. Do you want to make a PR for it?

**Comment by wakemaster39** [comment]
@pekkah I was trying to look at the codebase and figured out where to tie it in and haven't quiet figured out how would be best. I have managed to learn most of how the websocket package functions, but how a document/subscription executor functions is still a black box for me. 

Do you have any suggestions on where might be a good place to start tying that feature set in and I can take a look from there? My initial thought was it should be handled by the GraphQL subscription executor and it should just immediately unsubscribe after result is send.
