### ISSUE TITLE
GraphQL.Server.Transports.WebSockets version 5.0.0?

### ISSUE THREAD

**Issue by Rensvind** [graphql-dotnet/server#527]
Hi!

I have tried to upgrade to version 5.0 but it seems like GraphQL.Server.Transports.WebSockets is still on 4.4.1. Is there a timeframe for when GraphQL.Server.Transports.WebSockets will be released as 5.0.0?

Currently trying to use `app.UseGraphQLWebSockets<MySchema>("/graphql");` results in 
![image](https://user-images.githubusercontent.com/282209/112114446-5e768100-8bb8-11eb-83e0-c0a9b392d214.png)

**Comment by sungam3r** [comment]
My bad. I renamed package. Use GraphQL.Server.Transports.Subscriptions.WebSockets. I will update readme today.
