### ISSUE TITLE
Defining multiple Subscription with different Schema not working

### ISSUE THREAD

**Issue by bayupuspanugraha** [graphql-dotnet/server#530]
Dear Team,

I would like to ask your guidance to use GraphQL.net libs in the correct way to achieve my target.

I have several schema that has eachown subscription. But once I run all of them, Only one of the subcription under 1 schema is working, another subcription from other schema keep showing error when I ran it (I run it via playgroud).

Below is the following libs version and configuration that I used on the project:

Libs version:
<img width="775" alt="Screen Shot 2021-03-26 at 04 38 40" src="https://user-images.githubusercontent.com/8692017/112540475-32901100-8ded-11eb-9e8e-17a728abf66c.png">

Configure Service:
<img width="612" alt="Screen Shot 2021-03-26 at 04 40 20" src="https://user-images.githubusercontent.com/8692017/112540677-6f5c0800-8ded-11eb-9142-b86c397d87c8.png">

![image](https://user-images.githubusercontent.com/8692017/112431548-a1805200-8d7a-11eb-9dbd-5f4680933cf9.png)

![image](https://user-images.githubusercontent.com/8692017/112431608-b1983180-8d7a-11eb-877c-605c10d228c6.png)

After Tried on Playgroud: 
First Schema Run Correctly (UserSubscription):
![image](https://user-images.githubusercontent.com/8692017/112431878-09cf3380-8d7b-11eb-9d38-b210ba2fa7b1.png)

The other Schema subscription Not Working (AppSubscription):
![image](https://user-images.githubusercontent.com/8692017/112431960-23707b00-8d7b-11eb-94d0-b9891f39085a.png)

Fun Fact, when I tried to commented/disabled UserSubscription configuration and re-run it, then AppSubscription will work normally. Seems I cannot have 2 different subscriptions from different schemas on the same time (CMIIW). But with the ability to registering different Schema (Mutation and Query working normally), I assume I can have multiple websocket running at the same too. 

I tried some trial and error to add path on the UseGraphQLWebSocket like this:
![image](https://user-images.githubusercontent.com/8692017/112432237-90841080-8d7b-11eb-96c6-b268dc3cb319.png) 

the result made all websocket (2 different schemas) not working
![image](https://user-images.githubusercontent.com/8692017/112432175-75b19c00-8d7b-11eb-8e07-406a6db8871b.png)

Thank you for your help 👍

**Comment by sungam3r** [comment]
Regarding the first picture - it does not work because both websocket middlewares are mapped to the same url '/graphql' (by default):
![изображение](https://user-images.githubusercontent.com/21261007/112554540-8ee83600-8dd7-11eb-9786-c4559c12c545.png)


Regarding the last picture - show the address input. I think you should change it from /graphql.

**Comment by bayupuspanugraha** [comment]
@sungam3r Sorry Im still not clear with your direction, By changing from the default as you can see from the last 2 ScreenShot above, it leads to error right? how we solve it?

**Comment by sungam3r** [comment]
> Regarding the last picture - **show the address input**. I think you should change it from /graphql.

**Comment by bayupuspanugraha** [comment]
@sungam3r  as per my understanding with or without defining app.UseGraphQLWebSockets<UserSchema>() <- or ('/graphql') will be lead to same path. And Its only working for a single schema, and the other schema is still not working.

![image](https://user-images.githubusercontent.com/8692017/112561972-464d6e80-8e11-11eb-8d96-a3424228bc49.png)
UserSchema Subscription:
![image](https://user-images.githubusercontent.com/8692017/112562013-5b2a0200-8e11-11eb-8a78-eed2b0c2d627.png)


AppSchem Subscription:
![image](https://user-images.githubusercontent.com/8692017/112562051-6c730e80-8e11-11eb-8774-3304126a5673.png)

Tried to change the second with same as graphql app path also no luck:
![image](https://user-images.githubusercontent.com/8692017/112562544-75181480-8e12-11eb-9d4f-d2855cbc3bd7.png)

Sorry if I still failed to understand your guidance with this result.

**Comment by sungam3r** [comment]
Maybe I do not understand. I will make an example and check it. Give me 1-2 days.

**Comment by bayupuspanugraha** [comment]
@sungam3r Can I have the latest update regarding your trial? or Should I prepare my sample project case for you? So it could speed up the process?

**Comment by sungam3r** [comment]
Ooops. I forgot, sorry. Too much work. Of course, a working example/test is welcome.

**Comment by bayupuspanugraha** [comment]
@sungam3r  I have made the sample code, please take alook on that. Hopefully you can suggest how to solve to run all subscription with different schema soon.

REPO : [https://github.com/bayupuspanugraha/netgraphql](Sample Project)

Thank you;

**Comment by mahendrasonwane** [comment]
I am also having the same issue. I have two schemas registered the same way as mentioned above and subscription works only for one which is registered first. Haven't yet figured out the problem and how to resolve it.

**Comment by sungam3r** [comment]
Hi, guys. I had a long break from OSS this year. @bayupuspanugraha you registered websockets middleware on the same url for different schemas. Second - for multiple schemas that use subscriptions you should specify `SubscriptionsEndPoint` in playground options. See [here](https://github.com/bayupuspanugraha/netgraphql/pull/1).

**Comment by sungam3r** [comment]
https://github.com/bayupuspanugraha/netgraphql/pull/1

**Comment by bayupuspanugraha** [comment]
> Hi, guys. I had a long break from OSS this year. @bayupuspanugraha you registered websockets middleware on the same url for different schemas. Second - for multiple schemas that use subscriptions you should specify `SubscriptionsEndPoint` in playground options. See [here](https://github.com/bayupuspanugraha/netgraphql/pull/1).

Hi Sungam3r,

Thank you for your response and solution. I have tried to add "SubscriptionsEndPoint " and it is now working as expected. 
Thank you.
