### ISSUE TITLE
Subscriptions didnt work out of the box in current examples and readme.md

### ISSUE THREAD

**Issue by lanwin** [graphql-dotnet/server#544]
Maybe I miss something, but I copied the example server over to play with it and subscriptions always raise a not supported exception.

It took me some time until I noticed that this line is missing both in the example server and in the readme.md.

`services.AddSingleton<IDocumentExecuter,SubscriptionDocumentExecuter>();`

**Comment by egokick** [comment]
@lanwin  I have seen the same issue when trying out subscriptions in the samples projects with each UI project. 

Subscriptions were broken in commit 79b10768eb9739686b1ad99aac15c7e8411761eb on 2020-12-20 
The last working commit for subscriptions in the UI was fbb99b67727f94a75e4847d0a0cf5ec350405013 on 2020-11-28. If you pull that down, it should work for you or version 4.2.1 or earlier.
