### ISSUE TITLE
GraphQL.Authorization or GraphQL.Server.Authorization.AspNetCore

### ISSUE THREAD

**Issue by Alfieri** [graphql-dotnet/server#546]
Hello @all

I'm currently using GraphQL.Authorization package to handle authorization in my ASP.NET Core API. But now I notice that there is also an GraphQL.Server.Authorization.AspNetCore package.

What are the differences? Is there any matrix or something to see which features are implemented in the packages?
What package should be used in the future? Is there any plan to merge these two? What is the "offical" suggested one?

Many questions, thanks for the reply's!

Cheers

**Comment by Alfieri** [comment]
I found by myself this answer issue with this answer here https://github.com/graphql-dotnet/authorization/issues/49#issuecomment-703125017

So my questions are partially answered but it make no sense that in the context of GraphQL two packages exists which are try to solve the exact same problem.

**Comment by Shane32** [comment]
`GraphQL.Server.Authorization.AspNetCore`'s authorization rule has been integrated into the `GraphQL.Server.Transport.AspNetCore` repository.  The authorization rule itself has been updated to include support for `AllowAnonymous`, `AuthorizeWithRoles`, `@skip`, and `@include`.  It is designed to integrate with ASP.NET Core, pulling the identity directly from `HttpContext.User`.  It now requires only a single line of code to add the validation rule into a user's codebase -- `.AddAuthorizationRule()`.

The `GraphQL.Authorization` nuget package requires more configuration and does not yet support `AllowAnonymous` or `AuthorizeWithRoles`.  It may be better suited when not running on top of ASP.NET Core.

**Comment by Shane32** [comment]
Closing this issue as answered.
