### ISSUE TITLE
IUserContextBuilder is not called when subscription starts

### ISSUE THREAD

**Issue by lanwin** [graphql-dotnet/server#548]
I would expect the be able to build a usercontext when my subscription starts.

I can see that the IUserContextBuilder code is called in the GraphQLHttpMiddleware. But I an not sure where to place that for a string subscription. Any hints?

**Comment by Shane32** [comment]
GraphQL.NET Server v7 fully supports `IUserContextBuilder` for subscriptions.  This is a change from existing v6.
