### ISSUE TITLE
Subscriptions.Abstractions depends on Newtonsoft.Json

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/server#551]
The `GraphQL.Server.Transports.Subscriptions.Abstractions` package depends on `Newtonsoft.Json`.  The effectively means that both `Newtonsoft.Json` and `System.Text.Json` are imported any time that `GraphQL.Server.Transports.AspNetCore.SystemTextJson` is imported.

An "abstractions" library should not contain references to any specific transport protocol.  It isn't an abstraction if it's dependent on an underlying technology.  It also isn't an abstraction if it contains code.  In this case both rules are violated.

> In computer science, an abstraction layer is a generalization of a conceptual model or algorithm, away from any specific implementation

The `OperationMessagePayload` class needs to be reviewed, which contains a `Variables` object of type `JObject`.  There is also code within `ProtocolMessageListener` which casts a message payload to `JObject`.

Compare to any Microsoft "abstraction" library like `Microsoft.Extensions.Caching.Abstractions` or `Microsoft.Extensions.DependencyInjection.Abstractions` or `Microsoft.Extensions.Logging.Abstractions`.  They generally contain only interfaces or minimal extension methods.  Not implementations.

**Comment by sungam3r** [comment]
I know. That's right. The project has long been requested a large refactoring. I started once or twice, but the volume of changes was such that I did not dare.

**Comment by Shane32** [comment]
Fixed in v6
