### ISSUE TITLE
How this source code is licensed ?

### ISSUE THREAD

**Issue by MiroKentico** [graphql-dotnet/server#593]
Dear development team,

I was checking this graphql-dotnet server GitHub repository for any license file, but I got only license for Nuget packages themselves (stated as MIT). How it is with source code license ? According to some discussion on StackOverflow, no license for GitHub repository means, that code is not open source and in de facto is that strict one, when all rights are reserved. That means the source code is in fact read only for people outside of code authors.

Does this default "closed source" license really apply for this repository ?

Best Regards
   Miroslav

**Comment by Shane32** [comment]
The main GraphQL.NET project contains a MIT license.  You are correct in that this project does not specify a license file, and without one, the project is implicitly closed-source.  Of course each contributor's contributions are technically owned by them, so this makes for a quite complicated mess from a licensing perspective.  Most likely this is simply an oversight with the original developers (primarily @pekkah ) so as long as he is good with it, we will add a MIT license here which matches the MIT license in the main project.  @sungam3r has contributed considerably to the project as well and should also approve the PR.

To add the MIT license file, we certainly need approval from @pekkah , however, as my adding a license to the repo without his approval means nothing.

Once a MIT license has been added, contributors are implicitly agreeing for their contributions to be licensed under the same license, as each of their pull requests include each of the files in the repository, including the stated license.

**Comment by MiroKentico** [comment]
Hello Shane, I understand. Thank you for you reply and explanation.

 Yes, the main GraphQL.NET project is MIT licensed.

Okay, so I will be watching this thread for some (potential) changes, but for now, I am treating this GraphQL.NET server repository as closed source.

**Comment by sungam3r** [comment]
@MiroKentico #594 was merged 6 months ago so I close this issue.
