### ISSUE TITLE
There are no way to add description (not the comment) to field or type in GraphType First Approach

### ISSUE THREAD

**Issue by bohdan-kolomiiets** [graphql-dotnet/server#595]
## Summary
According to official graphql specification, field description is surrounded by double-quotes, type description is surrounded by triple double-quotes. 
In turn, comments start from the # character.

Value set via `GraphQL.Builders.Description`  method results in comment (not a description) in the schema.
```
Field<SomeGraphType>()
    .Name("fieldName")
    .Description("field description")
```

Value set via `Description` property of `GraphQL.Types.GraphType` also results in comment (not a description) in the schema.
```
public class MyGraphType : ObjectGraphType<MyModel>
{
    public MyGraphType()
    {
        Name = "TypeName";
        Description = "type description";
    }
}
```

Is there a way to specify description (not the comment) for the type or for its fields in the "GraphType First Approach"?

## Relevant information
Assembly GraphQL, Version=4.1.0.0
GraphQL.Server.All, Version=5.0.2

https://spec.graphql.org/June2018/#sec-Descriptions
https://spec.graphql.org/June2018/#sec-Comments

**Comment by Shane32** [comment]
This is a bug/enhancement for the SchemaPrinter and needs to be fixed in the main project.

See: https://github.com/graphql-dotnet/graphql-dotnet/issues/2574 and https://github.com/graphql-dotnet/graphql-dotnet/pull/2592
