### ISSUE TITLE
Adding execution errors to context returns 200(ok) instead of 400 (badrequest)

### ISSUE THREAD

**Issue by ravividap** [graphql-dotnet/server#597]
```

validationErrors.ForEach(e =>
{
   context.Errors.Add(new ExecutionError($"FieldName: {e.FieldName}, Message: {e.DefaultMessage}"));
`            `});
            return null;

```
I am adding ExecutionError to context and return null, but I get 200 (ok) result. How do I get 400 ?

**Comment by Shane32** [comment]
After calling documentExecuter.ExecuteAsync, check for any errors returned in the result, and if there are any, set the http status code to 400.

**Comment by ravividap** [comment]
I am not using controller, I will need to figure out.
