### ISSUE TITLE
Next release to bump package versions

### ISSUE THREAD

**Issue by galpin** [graphql-dotnet/server#624]
Do you have a timeframe for the next release of the server packages?

Specifically, we are waiting for changes in released packages (GraphQL and parser) to propagate through to the server.

If there is anything we can do to help out, please let me know.

**Comment by Shane32** [comment]
I can release a new version now, but note that it will still depend on GraphQL 4.1.0 and not 4.6.1, allowing users the flexibility of taking the latest bug fixes in the server project without the latest changes in the GraphQL library.  You will need to import GraphQL 4.6.1 to utilize the latest engine and parser.  By the same token, you can import GraphQL 4.6.1 now without pulling the latest changes to the server project.

Versioning for GraphQL.NET is done as follows:
- No binary-breaking changes within a major version; so any code compiled against 4.0.0 (including any version 5.x of server project) should be work with all of 4.x
- Minor changes to semantics are allowed, specifically for error handling (such as changing an error message), but typically will bump the minor version
- API changes bump minor versions
- Bug fixes bump revisions
- For releases, the repo publishes all nuget packages at the same time with unified version numbers, even if there is no change in one of the projects

Note that a bug fix may change behavior if user code was relying on the behavior of a bug.

For the server project:
- Same as above, plus:
- Always targets the oldest compatible version of the GraphQL.NET project
- Bump major version number when GraphQL.NET's major version number changes.

It is also noteworthy that the changes to GraphQL.NET 4.6.0 may cause naming conflicts to the server project, requiring changes to source code (even though it is binary-compatible).

**Comment by galpin** [comment]
Thanks for the confirmation - we will use an explicit package version on 4.6.1.

**Comment by sungam3r** [comment]
Thanks for explanation @Shane32 . Closed as answered.

P.S. I returned back after a long break from the OSS.

**Comment by Shane32** [comment]
> Thanks for explanation @Shane32 .

Maybe we should throw this in a readme or something,..

**Comment by sungam3r** [comment]
Well, I don't know. This is a fairly general approach. Documenting it is not the task of this repository. If you want, you can add a section in the end of readme after API Changes. I will review if you want.

**Comment by Shane32** [comment]
I’m not interested if you’re not
