### ISSUE TITLE
Subscription examples not working

### ISSUE THREAD

**Issue by MartinDawson** [graphql-dotnet/server#66]
First, thanks for this package.

Browser: Latest Chrome

I cloned the examples and ran samples.server through visual studio.

I followed the examples with 2 different windows. The query works fine, the mutation updates the query successful when the page is reloaded as expected but the subscriptions don't work. They just hang on 'listening' with no changes in the response window.

Console error:

> client.js:363 WebSocket connection to 'ws://localhost:60340/graphql' failed: Error during WebSocket handshake: Unexpected response code: 500

**Comment by MartinDawson** [comment]
@pekkah You have any idea? I really need to get subscriptions working.

**Comment by BenjaBobs** [comment]
If the response code was 500, something must have happened in the server. If you check the output log are there any exceptions?

**Comment by pekkah** [comment]
Which hosting are you using? IIS, IIS Express, bare Kestrel?

**Comment by MartinDawson** [comment]
I got this working on my project so I don't need this now.

**Comment by codestellar** [comment]
but what changes were done?
