### ISSUE TITLE
Using Altair in an offline environment

### ISSUE THREAD

**Issue by wakuflair** [graphql-dotnet/server#661]
The URL refers cdn.jsdelivr.net, but we want to host a GraphQL server in internal network.
Is there a way to customize/replace the URL?

https://github.com/graphql-dotnet/server/blob/2ab8faaf71b5ec4a6075a9459c28436bcd14b881/src/Ui.Altair/Internal/altair.cshtml#L34

**Comment by sungam3r** [comment]
Yes. See #652 . #655 is our stopper.

**Comment by wakuflair** [comment]
Thanks for the help.
I have seen the PR and got the idea about it.

**Comment by sungam3r** [comment]
v5.1 was released.
