### ISSUE TITLE
Question: how to access http headers from IResolveEventStreamContext?

### ISSUE THREAD

**Issue by fallenwood** [graphql-dotnet/server#663]

**Comment by sungam3r** [comment]
You can store this information beforehand in `UserContext`.

**Comment by fallenwood** [comment]
Hi @sungam3r ,thanks for quick responding.
I have managed to add the custom properties into `IResolveEventStreamContext.UserContext as MessageHandlingContext` by adding a custom `SubscriptionServer`, with most code copied from the original one, and the only differs come in constructor and `BuildMessageHandlingContextAsync`.

```csharp
        private Task<MessageHandlingContext> BuildMessageHandlingContextAsync(OperationMessage message)
        {
            var context = new MessageHandlingContext(this, message);
            context.Properties["HttpContext"] = this.httpContext;
            return Task.FromResult(context);
        }
```

I wonder there is a nicer solution rather than copy-and-paste a new `SubscriptionServer` class. From my side, I think it would be easier to implement if the `BuildMessageHandlingContextAsync` is `protected virtual` rather than `private`.

**Comment by sungam3r** [comment]
`SubscriptionServer` calls `OnBeforeHandleAsync/OnHandleAsync/OnAfterHandleAsync` later. These methods work with `IOperationMessageListener`. Implement your one and add into DI like that (code from `GraphQLBuilderWebSocketsExtensions`):
```csharp
 public static IGraphQLBuilder AddWebSockets(this IGraphQLBuilder builder)
        {
            builder.Services
                .AddTransient(typeof(IWebSocketConnectionFactory<>), typeof(WebSocketConnectionFactory<>))
                .AddTransient<IOperationMessageListener, LogMessagesListener>() // <------
                .AddTransient<IOperationMessageListener, ProtocolMessageListener>(); <-------

            return builder;
        }
```

**Comment by sungam3r** [comment]
In other words no need to make `BuildMessageHandlingContext` `protected` or `virtual`.

**Comment by fallenwood** [comment]
I know the lifetime calling of `IOperationMessageListener`, but the injected `OperationMessageListener` is unable to access http context either, right?
Sorry for misleading, I should show all the deferences

```csharp
    public class CustomSubscriptionServer : IServerOperations
    {
        private readonly HttpContext httpContext;

        public CustomSubscriptionServer (
            HttpContext httpContext,
            ...)
        {
            this.httpContext = httpContext;
            ...
        }

        private Task<MessageHandlingContext> BuildMessageHandlingContextAsync(OperationMessage message)
        {
            var context = new MessageHandlingContext(this, message);
            context.Properties["HttpContext"] = this.httpContext; // <------ http context referenced here
            return Task.FromResult(context);
        }
    }
```

**Comment by sungam3r** [comment]
@fallenwood v7 is coming, it was largely rewritten by @Shane32 with docs and samples. @Shane32 please chime in here.

**Comment by Shane32** [comment]
@fallenwood The new subscription server fully supports custom user contexts via `AddUserContextBuilder()`.  There is no need to create your own classes.

**Comment by Shane32** [comment]
Another way is to use `context.RequestServices.GetRequiredService<IHttpContextAccessor>().HttpContext`

**Comment by Shane32** [comment]
Please re-open this issue if you have further questions
