### ISSUE TITLE
Remove BasicGraphQLExecuter/DefaultGraphQLExecuter ?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#679]
See https://github.com/graphql-dotnet/server/pull/602#discussion_r775285677

**Comment by Shane32** [comment]
`IGraphQLExecuter` is virtually identical to `IDocumentExecuter`.  Both accept the following as inputs:

- Operation name
- Query
- Variables
- User context
- Service provider
- Cancellation token

And both return an `ExecutionResult`.

The difference is that `IGraphQLExecuter` was designed to use DI to configure the validation rules and document listeners applied to the execution.  However, this can now be configured via `IGraphQLBuilder` extension methods or manually via the `IGraphQLBuilder.ConfigureExecutionOptions` method.

The only remaining difference is that `IGraphQLExecuter<TSchema>` also defines the schema, allowing for different configurations for different schema.  However, even in this scenario, an `if` condition to check `options.Schema` can be used to selectively apply configurations to different schema.

It seems to me that this means that the `IGraphQLExecuter` interface serves no purpose for most scenarios anymore.  I recommend marking it obsolete in v6 and removing it in v7.

**Comment by Shane32** [comment]
Also, the entire `AddServer` builder method and `GraphQLOptions` class is also redundant given that the execution options can be configured via the `IGraphQLBuilder` interface.  I would also recommend marking these methods/classes obsolete in v6 and removing them in v7 -- mainly to ease transition.

**Comment by Shane32** [comment]
Done
