### ISSUE TITLE
Release v5.2

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/server#688]
Open PRs marked with the 5.2 milestone:

- [x] #649 
- [ ] #195 
- [x] #691 

@sungam3r Let's review these PRs/issues and decide what else, if anything, should be in 5.2 - or revise these milestones if they will not make it in 5.2

**Comment by sungam3r** [comment]
I doubt about #195 and I'm sure we''ll merge #649 and #691.

**Comment by sungam3r** [comment]
Let's release without #195.

**Comment by Shane32** [comment]
Sounds good.  You want to issue the release?

**Comment by sungam3r** [comment]
Yes.

**Comment by sungam3r** [comment]
https://github.com/graphql-dotnet/server/releases/tag/5.2.0
