### ISSUE TITLE
Question: Authentication over Websocket

### ISSUE THREAD

**Issue by terjebra** [graphql-dotnet/server#70]
We are currently trying to authenticate the clients before allowing them to set up subscriptions.  A common way of doing this seems to be to add a token to the payload on the initial  connection ( connection_init):

```json
{"type": "connection_init", "payload": {"token": "123456"}}}
```
[This approach is seen here](https://github.com/apollographql/apollo-client/blob/master/docs/source/features/subscriptions.md#authentication-over-websocket)

We have tried to access the payload through **OperationMessageContext** in the **BuildUserContext** delegate, but we are not able to get the payload for the initial  connection, just the subsequent connections after the ack is received.  The intention is to build a usercontext there and do further checks in the validation rules before allowing the subscription.

Is this currently possible in the library or is there another preferred way of doing an initial authentication?

**Comment by pekkah** [comment]
Currently this is not supported but with should be doable with the 3.0 version

**Comment by pekkah** [comment]
You could probably do it with a middleware if you add the token as query string to the connection request. That seems to be the way SignalR solved the authentication problem.

**Comment by KreativJos** [comment]
This was a big issue on our side too.
To help to overcome this, I have hacked a lot into the code, and I do hate the way it is right now, but it is working fine. I think there are much better ways to do it, but if you'd like to see **a** solution, I can put a fork online with my hacks in it.

**Comment by pekkah** [comment]
3.0 will allow setting message listeners. You should be able to check the payload and close the reader if it doesn't contain what you want. You can also send a reply to the client.

**Comment by pekkah** [comment]
* Inherit from https://github.com/graphql-dotnet/server/blob/master/src/Transports.Subscriptions.Abstractions/IOperationMessageListener.cs
* Apply your authorization
* Write your reply using the writer or just complete the reader which should close the connection

**Comment by pekkah** [comment]
Closing this. Please feel free to reopen if you have any questions.
