### ISSUE TITLE
How do we use this with Entity Framework?

### ISSUE THREAD

**Issue by MartinDawson** [graphql-dotnet/server#72]
The example `Chat.cs` uses an `ISubject` which works fine.

However for me project I get the data from the server using Entity Framework Core.

```csharp
public class AppSubscription : ObjectGraphType<object>
{
    public AppSubscription(ICommentService commentService)
    {
        AddField(new EventStreamFieldType
        {
            Name = "commentAdded",
            Type = typeof(CommentPayload),
            Resolver = new FuncFieldResolver<Comment.Models.Comment>(c => {
                return (Comment.Models.Comment)c.Source;
            }),
            Subscriber = new EventStreamResolver<Comment.Models.Comment>(c => {
                var comments = repository.GetComments().ToObservable;

                return comments;
            }),
        });
    }
}

public class CommentsRepository {
    public virtual IQueryable<Comment> GetComments()
    {
        return Context.Set<Comment>();
    }
}
```

The above gives the exception, it seems to call `OnCompleted` before `unSubscribe` is assigned which results in `Unsubscribe.Dispose()` throwing a null reference error:

> System.NullReferenceException: Object reference not set to an instance of an object.
   at GraphQL.Server.Transports.WebSockets.SubscriptionHandle.OnCompleted()
   at System.Reactive.AnonymousSafeObserver`1.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.Merge`1.MergeConcurrent.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.Catch`2._.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.SelectManyImpl.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnCompleted()
   at System.Reactive.Linq.ObservableImpl.ToObservable`1._.LoopRec(State state, Action`1 recurse)
   at System.Reactive.Concurrency.Scheduler.InvokeRec1[TState](IScheduler scheduler, Pair`2 pair)
   at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
   at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
   at GraphQL.Server.Transports.WebSockets.SubscriptionHandle..ctor(OperationMessage op, IObservable`1 stream, IJsonMessageWriter messageWriter, IDocumentWriter documentWriter)
   at GraphQL.Server.Transports.WebSockets.SubscriptionProtocolHandler`1.<>c__DisplayClass14_0.<AddSubscription>b__0(String connectionId)
   at System.Collections.Concurrent.ConcurrentDictionary`2.AddOrUpdate(TKey key, Func`2 addValueFactory, Func`3 updateValueFactory)
   at GraphQL.Server.Transports.WebSockets.SubscriptionProtocolHandler`1.<AddSubscription>d__14.MoveNext()

If I replace the above code with the example code it works fine, so it seems to be a problem with how I am using it with EF:

```csharp
public class AppSubscription : ObjectGraphType<object>
{
    private readonly ISubject<Comment.Models.Comment> _messageStream = new ReplaySubject<Comment.Models.Comment>(1);

    public AppSubscription()
    {
        AddField(new EventStreamFieldType
        {
            Name = "commentAdded",
            Type = typeof(CommentPayload),
            Resolver = new FuncFieldResolver<Comment.Models.Comment>(c => {
                return (Comment.Models.Comment)c.Source;
            }),
            Subscriber = new EventStreamResolver<Comment.Models.Comment>(c => {
                var comments = _messageStream.AsObservable();

                return comments.ToObservable();
            }),
        });
    }
}
```

**Comment by pekkah** [comment]
Looks like a bug as the stream is completed as soon as all all of the rows are pushed out. Timing issue. I'll check if this is fixed in the release 3.0.0 branch.

**Comment by MartinDawson** [comment]
@pekkah Thanks a lot. Much appreciated.

**Comment by pekkah** [comment]
This shouldn't happen with the 3.0

**Comment by MartinDawson** [comment]
@pekkah Fantastic, I'll test it later tonight. Thanks again.

**Comment by MartinDawson** [comment]
@pekkah I just upgraded to graphql server 3.0 alpha and I still get this error.

> Microsoft.AspNetCore.Server.Kestrel[13]
>       Connection id "0HLCCVEES2JD9", Request id "0HLCCVEES2JD9:00000001": An unhandled exception was thrown by the application.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at GraphQL.Server.Transports.Subscriptions.Abstractions.Subscription.OnCompleted()
>    at System.Reactive.SafeObserver`1.OnCompleted()
>    at System.Reactive.Linq.ObservableImpl.Catch`2._.OnCompleted()
>    at System.Reactive.Linq.ObservableImpl.SelectMany`2.SelectManyImpl.OnCompleted()
>    at System.Reactive.Linq.ObservableImpl.Select`2._.OnCompleted()
>    at System.Reactive.Linq.ObservableImpl.ToObservable`1._.LoopRec(State state, Action`1 recurse)
>    at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass49_0`1.<InvokeRec1>b__0(TState state1)
>    at System.Reactive.Concurrency.Scheduler.<>c__DisplayClass49_1`1.<InvokeRec1>b__2(IScheduler scheduler1, TState state3)
>    at System.Reactive.Concurrency.ScheduledItem`2.InvokeCore()
>    at System.Reactive.Concurrency.ScheduledItem`1.Invoke()
>    at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue)
>    at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action)
>    at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action)
>    at System.Reactive.Producer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard)
>    at System.Reactive.Producer`1.Subscribe(IObserver`1 observer)
>    at GraphQL.Server.Transports.Subscriptions.Abstractions.Subscription.Subscribe(SubscriptionExecutionResult result)
>    at GraphQL.Server.Transports.Subscriptions.Abstractions.SubscriptionManager.<ExecuteAsync>d__11.MoveNext()

**Comment by pekkah** [comment]
I'll try making a proper test came for it. To me it feels like a bug in Reactive extensions but have to see. The stream is completed while subscribe call hasn't returned yet.

**Comment by pekkah** [comment]
Fix in 3.1.0-alpha0004

**Comment by MartinDawson** [comment]
@pekkah I'm still getting the same issue in alpha 0004.

**Comment by MartinDawson** [comment]
@pekkah Still getting the same issue.

**Comment by pekkah** [comment]
At least this test now passes https://github.com/graphql-dotnet/server/commit/b8ab6188ed042be3c36797a99fd8c96d477d1c11

Could you create a failing test case for it?

**Comment by MartinDawson** [comment]
@pekkah It seems to be entity framework specific, is calling `.ToObservable` valid for this? I have no idea about Reactive to be able to understand what's going wrong here or create a failing test case.

**Comment by pekkah** [comment]
What are you trying to do?

**Comment by MartinDawson** [comment]
@pekkah Create a comment system that automatically updates when users create a new comment. Similar to twitch.tv comments system.

**Comment by pekkah** [comment]
I mean how are you planning to implement it? Now you're just trying to push the whole comments table contents trough the websocket to the client.

**Comment by MartinDawson** [comment]
I am not sure how I was going to implement it. I wanted to solve this issue and then play around with it.

At the moment I am just doing this:

`const subscription = graphql`
  subscription commentSubscription {
    commentAdded {
      id
    }
  }
`;

export default () => requestSubscription(
  environment, // see Environment docs
  {
    subscription,
    onError: error => console.error(error), // eslint-disable-line no-console
  },
);
`
and calling it in my app.js.

**Comment by MartinDawson** [comment]
Actually I guess I don't even need Entity Framework for this if I don't care about preserving the comments right? I can just copy the sample chat schema where the comments will last until app restart which seems good to me.

**Comment by sungam3r** [comment]
Closed due to inactivity. @MartinDawson I hope you solved the problem.
