### ISSUE TITLE
Reference DefaultGraphQLExecuter<> claims it is defined in GraphQL.Server.Core but it could not be found

### ISSUE THREAD

**Issue by bruno-salapic** [graphql-dotnet/server#734]
Hello,

I've been tasked with migrating a v2 project to v4, I managed to successfully go from v2 to v3 and now in the works to move to v4.
I'm running into an issue where the "DefaultGraphQLExecuter" is not able to be found because it claims to be defined in GraphQL.Server.Core.

When i in inspect the actual one it is using it is sending me to a namespace of GraphQL.Server.Internal.

I installed the GraphQL.Server.Core package aswell. 

also all my using for GraphQL.Server.Internal that use to work before now say they GraphQL.Server does not contain a namespace called Internal.

Referenced the documentation related to moving from v3 to v4 and i don't say anything obvious that helps me with this issue

**Comment by Shane32** [comment]
Just to verify - are you suing the GraphQL version 4 and GraphQL Server version 5?  Perhaps you can post the exact versions of the nuget packages you have referenced.

**Comment by bruno-salapic** [comment]
sorry, these are the packages i have referenced 
![image](https://user-images.githubusercontent.com/84862823/154675364-fc67f97e-e636-4c44-8766-93f05e3ef494.png)

**Comment by bruno-salapic** [comment]
nvm i figured it out
