### ISSUE TITLE
Playground endpoint http/https

### ISSUE THREAD

**Issue by BenjaBobs** [graphql-dotnet/server#74]
When loading Playground through a https uri, I get the following errors:
```
Mixed Content: The page at 'https://<my graphql api playground>' was loaded over HTTPS, but requested an insecure resource 'http://<my graphql api>'. 
This request has been blocked; the content must be served over HTTPS.
```

I think the source can be found here:
https://github.com/graphql-dotnet/server/blob/master/src/Ui.Playground/Internal/playground.cshtml#L54
But I don't know how to make the check to see if the endpoint should be http or https.

**Comment by pekkah** [comment]
I think we should change the configuration to allow setting the whole url to the GraphQL endpoint instead of just a relative url.

**Comment by BenjaBobs** [comment]
I submitted a pull request with a solution where we can still have relative paths for simplicity.

It seems that the wss protocol causes some exceptions though, so subscriptions still only work in http. Not sure exactly what the problem is, but I'm hoping you'll have a look at the pull request and add some comments. :)
