### ISSUE TITLE
Multi-query requests with 1 request do not return an array with 1 result

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/server#751]
Consider:

```json
[
  { "query": "{hero}" }
]
```

Incorrectly returns this in v5:

```json
{
  "data": { "hero": "Luke Skywalker" }
}
```

Rather than this:

```json
[
  {
    "data": { "hero": "Luke Skywalker" }
  }
]
```

This bug is due to changes in #716 and did not exist in server v5.

### Suggestion 1

Add class/struct to main project that contains both the array and a boolean indicating if it is a multi-query request.

Some possibilities:

```cs
// suggestion A
class MultipartGraphQLRequest
{
  public IList<GraphQLRequest> Requests { get; set; }
  public bool IsSingleRequest { get; set; }
}

// suggestion B
class MultipartGraphQLRequest
{
  public GraphQLRequest Single { get; set; }
  public IList<GraphQLRequest> Multiple { get; set; }
}
```

The class and support for it would be added to the main project.  Then here we simply deserialize the new type:

```cs
var requests = serializer.Deserialize<MultipartGraphQLRequest>(data);
```

### Suggestion 2

Take advantage of the knowledge of how GraphQL.NET works and deserialize to `IList<GraphQLRequest>`.  If the type is an array, then it is a single result; if it is a List then it is a multi-part request.

```cs
var requests = serializer.Deserialize<IList<GraphQLRequest>>(data);
if (requests is GraphQLRequest[] array)
{
    var singleRequest = requests[0];
}
else
{
    var multipleRequests = requests;
}
```

While this answer 'works', I feel it is the wrong one.

**Comment by sungam3r** [comment]
I did not notice that it broke after `GraphQLRequestDeserializationResult` was removed. Both options do not look very good. I tend to use suggestion 2 for now.

**Comment by sungam3r** [comment]
I think that the likelihood that someone uses his own deserializer and batch requests is very small.

**Comment by Shane32** [comment]
The problem exists with the serializers provided by GraphQL.NET, and did not exist before.

**Comment by Shane32** [comment]
Oh I didn’t see your earlier message. Ok I’ll write a PR.
