### ISSUE TITLE
Suggestion: Remove IGraphQLExecuter and maybe GraphQLOptions

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/server#758]
## IGraphQLExecuter

It seems unnecessary to me.

1. Configuration of any of the `ExecutionOptions` can be performed from DI, and largely has been already done so - for instance, validation rules and document executers.
2. Any other configuration of options can be done from DI via `ConfigureExecution`.
3. The only other purpose of `IGraphQLExecuter` is to wrap `ExecuteAsync` - for instance for enriching the results for apollo tracing.  This can be done with a custom `IDocumentExecuter` which does the wrapping and calls `base.ExecuteAsync`.  We should probably provide a derived `DocumentExecuter` class within GraphQL.NET which 'enriches the results with apollo tracing' if metrics is enabled.  (Or build it into the base document executer.)
4. We now have a typed `IDocumentExecuter<T>` in case custom behavior for different schemas is desirable.

## GraphQLOptions

Also seems unnecessary to me.

1. `EnableMetrics` can already be configured via the metrics builder method
2. `ComplexityConfiguration` can already be configured via the builder methods
3. `ConfigureExecution` can be used to configure the unhandled execution delegate and max parallel execution count

Note that if `GraphQLOptions` was not removed, `ConfigureExecution` can still be used to pull `GraphQLOptions` and configure the `ExecutionOptions` instance properly.  There is no need for `IGraphQLExecuter`

**Comment by sungam3r** [comment]
OK, let's try.

**Comment by Shane32** [comment]
So that leaves literally nothing in Server.Core.  We have already removed the STJ and NSJ converter libraries.  I wanted to rewrite the websockets implementation so it does not need the dataflow library and so it will support the newer graphql-ws (#749).  Then I looked at the middleware and realized that the middleware for websockets should be rolled into the middleware for the rest of the project.  I did so.  Finally, I wanted to add configuration options, so you can do stuff like enable/disable handling "GET" requests (for example, I use a GET request to return GraphiQL).  I also wanted better documentation, more complete samples, and better tests.  Oh and I wanted the websocket code pluggable so future protocols can easily be added.

Mostly I have accomplished all of the above, besides finishing tests.  You can view my progress here:

https://github.com/Shane32/GraphQL.AspNetCore

I have about 100% test coverage on all the websocket code.  Tests were done with the methodology that each individual function is tested apart from the rest of the project.  Remaining is to test the middleware and options.  I will likely write those tests that simulate a full request using the ASP.NET Core test pipeline.

To view coverage (at the moment), view the most recent build check and download the artifacts.  I don't know why codecov isn't working right; it works for my other projects.

If you are supportive, we can move the code back to the server repo when I'm done.  Otherwise I will continue with my own library.  Of course I welcome assistance reviewing and so on.  But basically I am rewriting the server project 90%+ from scratch.

**Comment by sungam3r** [comment]
What can I say? Move in small steps is always easier.

**Comment by Shane32** [comment]
Yeah, not going to work this time unfortunately.  Either we replace the majority of the code with the new implementation or not.  I can split it up into multiple pull requests, but any changes we want to make would need to be at the end (after everything is merged).  I'm not going to keep reworking all the subsequent PRs to change an issue in the first PR.

As far as I'm concerned, I'd just as soon publish my own implementation.  The UI nuget packages and the Authorization package do not depend on the Server package, so those pieces don't change.  And there's nothing that my package doesn't do that the server project does, assuming IGraphQLExecuter and GraphQLOptions are removed.

Let me know what you think.

**Comment by sungam3r** [comment]
You know that almost every our PR (except primitive ones) in the end turns out to be merged with a lot of suggestions and comments, bug fixes, typos and design decisions. I welcome the changes. Everything I want to say is that it takes a lot of time to check everything at once. It will take longer than the sum of all changes but smaller portions. I myself have a few PRs, which I abandoned because of their size.

**Comment by sungam3r** [comment]
In both cases, one big PR or many small ones - review is required before merging. I would never merge the code simply because there is some kind of conditional date that we have identified themselves for a long time ago. By the way, I do not have enough time to complete my PR c with the federation and the full rework of the printing bits. In the last month there were a lot of work and other events that demanded my attention. I was going to return to my work, perhaps in the first week of April. If we make a GraphQL.NET v5 release from day to day (and accompaying server v6), then I can say with a 100% probability that I will need to make a GraphQL v6 (and accompaying server v7) release after a couple of weeks because I need all that bits around printing. In any case, I do everything possible from me to carry out the maximum detailed and thoughtful code review on all PRs.

**Comment by Shane32** [comment]
So what are you suggesting?  Option 2, abandoning the server project?  I need this done asap.

> then I will need to make a GraphQL v6

Fine; it will not hurt anything.

However, I suggest we consider reducing the API of the printing bits (making almost all exisiting methods internal) such that no major version bump is necessary.  If someone needs to override the existing printing library's virtual methods, then they must stay on v4 until the new printing support is ready in 5.1.

> and accompaying server v7

Should not be necessary if only the printing code changes.  It is not called by the server project.  We can easily add CI tests to validate the server project works with both v5 and v6 of GraphQL.NET - just like we already have in the authorization project.

**Comment by sungam3r** [comment]
I do not urge to abandon this project. And I do not feel responsible for choosing a binary decision between two aforementioned options.

>  I need this done asap.

What does "this" mean exactly? You may use your version of server project for some time while waiting all changes beeing merged and after that just merge and switch to using "well-known" bits. Now I see two pending PRs for server project in my email - #749 and #755. I remember about them. Every day I'm paying time to triage email. Let's put priorities and move on.

**Comment by Shane32** [comment]
My priority in this case is to release GraphQL.NET v5 asap.  You set the date; I have been working towards that goal for quite awhile (two months? longer?).  I would like to release it asap (today if we could!).  I looked through the issue list again.  While there is always stuff to work on, there's nothing left there that I feel compelled to work on.

**Comment by sungam3r** [comment]
I doubt that SDL printing works well in v5. I remember some TODOs that I promised to fix as part of big printing/AST converter rework. I can not give warranties that the current code works correctly without my pending changes (I stopped on the federation - `FederatedSchemaPrinter`). If you do not use schema printing bits, you will not have problems. But the code for those who use can explode. Unfortunately, I could not return to work on the PR in the last few weeks, because I was busy. I need a couple of days to remember what I did and continue.

**Comment by Shane32** [comment]
It can't work any worse than v4 can it?  All the tests are still there and they still pass.  And there are quite a few of them.  Below is only half!  Or am I misunderstanding something?

![image](https://user-images.githubusercontent.com/6377684/160713492-2461d69c-f6cd-442b-9935-50e8ceb0f452.png)

**Comment by Shane32** [comment]
Note that the SchemaPrinter does not convert to an AST; so it is unaffected by the changes to the parser library we have made.  It also does not use any type of visitor, so it's unaffected by any of those changes also.

I had thought that the goal was to add an AST printer to the parser library (did we do that?), and then write code to convert a schema to an AST.  But as of now, the schema printer doesn't use any of that code and should work as well (or as poorly) as it ever did.

**Comment by Shane32** [comment]
The SDL printer in the parser library is new for v5 and is not used by GraphQL.NET, correct?  If that's what you are referring to, we can just remove it for now if you'd rather only release it when it's done.

**Comment by sungam3r** [comment]
All printing code in parser works well. I'm talking about GraphQL.NET. Perhaps it will work, I do not remember. I can say exactly two things:
1. My changes around schema printing are strongly backward incompatible. 
2. I will need to do them in next weeks, that is, it does not take the ~year to fit the next major version.

I'm OK to release v5 if you want but note that I'll need to release v6 rather soon after v5 release.

**Comment by Shane32** [comment]
FYI my server middleware is published as GraphQL.AspNetCore3 v1.0.0.  It has 96% code coverage and supports both the older and newer subscription protocols, has numerous bug fixes and added features, and only requires a single line of code in Program.cs to configure.  It has much more documentation within the readme file, complete xml comments, and a number of complete sample applications.  It does not depend on System.Reactive or System.Threading.Tasks.Dataflow.  It does not include the UI projects or the server Authorization project.  (The UI projects do not depend on GraphQL.Server.Core and the Authorization project in v6 will not either.)

**Comment by Shane32** [comment]
As for this original suggestion, I will plan to issue a PR for it when I have time.

**Comment by sungam3r** [comment]
Done in #762. Regarding discussion around GraphQL.AspNetCore3 see milestone 7 description.
