### ISSUE TITLE
Publish to nuget.org

### ISSUE THREAD

**Issue by jinhong-** [graphql-dotnet/server#76]
One question, will you be publishing it to nuget.org?

**Comment by pekkah** [comment]
As soon as the main graphql-dotnet has a stable release available.

**Comment by pekkah** [comment]
While that is brewing you can just add the myget feed and install from there.

**Comment by glennblock** [comment]
Was just about to file this issue. I recently created a LinkedIn Learning / Lynda course promoting this. Currently I include a nuget.config to point to MyGet, but that is not ideal.

Why not publish to NuGet as pre-release until it is ready?

**Comment by pekkah** [comment]
Just did a publish to NuGet. @joemcbride do you need to approve something in NuGet to them to be visible?

**Comment by glennblock** [comment]
w00t!

**Comment by pekkah** [comment]
Seems to be visible now.
