### ISSUE TITLE
Altair: LongGraphType being rounded

### ISSUE THREAD

**Issue by zepedr0** [graphql-dotnet/server#764]
Having the following schema:

```cs

var schema = new Schema();

var site = new ObjectGraphType { Name = "Site" };
site.Field("id", new LongGraphType(), resolve: ctx => 2202210000000000001);

var root = new ObjectGraphType { Name = "Root" };
root.Field("site", site, resolve: ctx => new { });

schema.Query = root;
schema.RegisterTypes(site);
```
If we have an Altair client set up and send the following query:

```
{
  site {
    id
  }
}
```

We receive the data object with the id field equal to `2202210000000000000`. It seems there is some rounding happening. If we instead run the query against the schema like so:

```cs
var json = await schema.ExecuteAsync(_ =>
{
  _.Query = "{ site { id } }";
});

Console.WriteLine(json);
```

We get the correct value of `2202210000000000001`. Also tested sending the query trough Postman and got the correct value.

Haven't tested enough to figure out what really happens, but seems kinda similar to this [issue](https://github.com/graphql-dotnet/graphql-dotnet/issues/1205) for some reason, and I believe it might affect other types and not just `LongGraphType`.

Using Version 5.2.0.

**Comment by Shane32** [comment]
If you see the correct value in postman then it’s not the server or GraphQL but rather the Altair implementation which is likely reading the JSON output before printing it. JavaScript cannot properly understand a value that large so it gets rounded. To demonstrate, write this in jsfiddle.net or similar:

```javascript
alert(2202210000000000001);
```

It will always print the incorrect value. This is not the fault of GraphQL, Altair or JSON but rather JavaScript’s ability to retain numeric values parsed from JSON.

**Comment by Shane32** [comment]
If testing with postman revealed an incorrect value then it would be another story, but it seems you have already confirmed that it is not a problem with the server or GraphQL.

**Comment by Shane32** [comment]
Depending on your use case, you may wish to use an ID graph type which will encode values as strings. Or of course the String graph type would work. But if you will be consuming the JSON in JavaScript, it will not accurately read large numbers like 2202210000000000001

**Comment by zepedr0** [comment]
Yeah makes sense, didn't think of that. Thanks for the input!
