### ISSUE TITLE
AuthorizeWith attribute on graph type does not fire authentication

### ISSUE THREAD

**Issue by pykos** [graphql-dotnet/server#768]
I am having trouble with authenticating graphql requests with JWT bearer token. Full disclosure, I am using graph ql in conjunction with umbraco 9 so there is a possibility that this might be a problem. 
This is how we set up graphql in ConfigureServices class.          
          
```
GraphQL.MicrosoftDI.GraphQLBuilderExtensions.AddGraphQL(services)
                .AddServer(true)      
                .AddGraphQLAuthorization(builder =>
                {
                    builder.AddPolicy("Authenticated", p => p.RequireAuthenticatedUser());
                })
                .AddSystemTextJson()
                .AddErrorInfoProvider()
                .Configure<ErrorInfoProviderOptions>(opt => opt.ExposeExceptionStackTrace = _env.IsDevelopment())
                .AddDataLoader()
                .AddUserContextBuilder(context => new GraphQLUserContext { User = context.User });
```

The jwt auth setup (I am using Azure AD):

```
services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
                .AddJwtBearer(options =>
                {
                    options.Audience = audience;
                    options.Authority = authority;
                });
```
The Configure method in startup.cs
```
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseGraphQL<BuiltSchema>("/umbraco/graphql");

            app.UseUmbraco()
                .WithMiddleware(u =>
                {
                    u.UseBackOffice();
                })
                .WithEndpoints(u =>
                {
                    u.UseInstallerEndpoints();
                    u.UseBackOfficeEndpoints();
                });
        }
```

I can confirm that JWT authentication works when using ` [Authorize(JwtBearerDefaults.AuthenticationScheme)]` on a controller level. The Authorization header iz present in every request but the authentication does not fire on graph ql requests. I tried debuging with  break points on jwt events but none of them fired and the process went straight to setting the `context => new GraphQLUserContext { User = context.User }) ` wich was not set. When testing the ` [Authorize(JwtBearerDefaults.AuthenticationScheme)]` with break points on the events, the process works as expected.
 
I get `"GraphQL.Server.Authorization.AspNetCore.AuthorizationError: You are not authorized to run this query.\r\nThe current user must be authenticated."` every time. 
I found out that if I add `x.FallbackPolicy = new AuthorizationPolicyBuilder("Bearer").RequireAuthenticatedUser().Build();` to `AddGraphQLAuthorization` the authentication get fired and I get the graphql query result, but then every endpoint gets protected by this authentication schema wich is the correct behaviour but wrong in my case :). If i try the same with `x.DefaultPolicy = new AuthorizationPolicyBuilder("Bearer").RequireAuthenticatedUser().Build();` nothing happens and I get the same authorization error as above.

I have a feeling that when I add .AuthorizeWith attribute to a graph type, this does not get registered in the "authentication pipeline" or something :)

I am using the latest graphql.server.all packages 5.2.1 and graphql.authorization version 4.0.0.

I found one similar issue with authorizing mutations #353 wich wasnt resolved.

I kind of ran out of ideas where the problem might be. Any help will be greatly appreciated.

**Comment by Shane32** [comment]
Can you post your Program.cs / Startup.cs  ?  Specifically, the point at which you inserted `.UseGraphQL()` could be a potential problem.

**Comment by pykos** [comment]
I tried moving all this parts (grphql, UseAuth, UuseAuthr) up and down the Configure and ConfigureServices methods, but nothing seems to work. 

```
public class Startup
  {
      private readonly IWebHostEnvironment _env;
      private readonly IConfiguration _config;

      public Startup(IWebHostEnvironment webHostEnvironment, IConfiguration config)
      {
          _env = webHostEnvironment ?? throw new ArgumentNullException(nameof(webHostEnvironment));
          _config = config ?? throw new ArgumentNullException(nameof(config));
      }

      public void ConfigureServices(IServiceCollection services)
      {
          services.AddUmbraco(_env, _config)
              .AddBackOffice()
              .AddComposers()
              .AddAzureADBackendUserAuthentication(config => _config.GetSection("AzureAd").Bind(config))
              .Build();
      
          GraphQL.MicrosoftDI.GraphQLBuilderExtensions.AddGraphQL(services)
              .AddServer(true)      
              .AddGraphQLAuthorization(builder =>
              {
                  builder.AddPolicy("Authenticated", p => p.RequireAuthenticatedUser());
              })
              .AddSystemTextJson()
              .AddErrorInfoProvider()
              .Configure<ErrorInfoProviderOptions>(opt => opt.ExposeExceptionStackTrace = _env.IsDevelopment())
              .AddDataLoader()
              .AddUserContextBuilder(context => new GraphQLUserContext { User = context.User });


          services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
              .AddJwtBearer(options =>
              {
                  options.Audience = "audience";
                  options.Authority = "authority";
              });

      }

      public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
      {
          if (env.IsDevelopment())
          {
              app.UseDeveloperExceptionPage();
          }

          app.UseAuthentication();
          app.UseAuthorization();

          app.UseGraphQL<BuiltSchema>("/umbraco/graphql");

          app.UseUmbraco()
              .WithMiddleware(u =>
              {
                  u.UseBackOffice();
              })
              .WithEndpoints(u =>
              {
                  u.UseInstallerEndpoints();
                  u.UseBackOfficeEndpoints();                    
              });
      }
  }
```

**Comment by Shane32** [comment]
@pykos Were you able to solve your problem?  It appears I neglected to answer you when you asked previously.

Your experience may be related to one of mine, where I was attempting to use two different authentication schemes in one application.  The web app used cookie authentication by default, but my GraphQL endpoint needed JWT Bearer authentication.

My only solution was to write ASP.NET Core middleware for "/graphql" requests to manually process the JWT Bearer authentication header and set the HttpContext.User property appropriately prior to handing off control to the GraphQL.NET Server ASP.NET Core middleware.  I'm sure there's a way, but I could not figure out how to have ASP.Net Core automatically authenticate using the configured JWT Bearer authentication.  (Both cookie and JWT Bearer authentication were configured.)

This might not be it at all, but at least I thought I'd mention it.  I don't see anything else wrong with your code.

**Comment by Shane32** [comment]
Please reopen if you need further assistance
