### ISSUE TITLE
Change content-type

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#775]
https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#content-types

Change `MediaType.GRAPH_QL` from `application/graphql` to `application/graphql+json` . Ping @Shane32 .

**Comment by sungam3r** [comment]
🤔 Actually, not change but append since
> A server MAY support requests from clients with other content types.

**Comment by sungam3r** [comment]
Also note 
> A server must indicate the content type of the response with a Content-Type header. This default value should be Content-Type: application/graphql+json

but now server **always** returns `application/json` 
```
 protected virtual Task WriteResponseAsync<TResult>(HttpResponse httpResponse, IGraphQLSerializer serializer, CancellationToken cancellationToken, TResult result)
    {
        httpResponse.ContentType = "application/json";
        httpResponse.StatusCode = 200; // OK

        return serializer.WriteAsync(httpResponse.Body, result, cancellationToken);
    }
```

**Comment by sungam3r** [comment]
More:
> A server MUST return a Content-Type HTTP Header with a value of a valid GraphQL content type. If there is no Accept header in the request, the response MUST be serialized as JSON and MUST include a Content-Type: application/graphql+json header.

**Comment by Shane32** [comment]
Yup we should support this spec. I read a bit of the link you posted.

**Comment by Shane32** [comment]
It will be a separate PR

**Comment by sungam3r** [comment]
Completed?

**Comment by Shane32** [comment]
Yes
