### ISSUE TITLE
Return 400 in case of validation errors?

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#776]
This surprises me a bit https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md#document-validation 
> The server SHOULD deny execution with a status code of 400 (Bad Request).

Now server just calls `IDocumentExecuter.ExecuteAsync` and then writes response (ExecutionResult) with 200 OK. I'm 100% sure that switching from 200 to 400 will break a lot of out services. ping @Shane32

**Comment by Shane32** [comment]
It is a configurable option in my implementation right now.

**Comment by sungam3r** [comment]
`ExecutionResult.Executed` to the rescue!

**Comment by Shane32** [comment]
Hmm actually … well I need to check ….

**Comment by Shane32** [comment]
Oh yeah it is. However for batched requests it always returns 200 because some requests may have executed successfully.

**Comment by sungam3r** [comment]
Side note - I think that we should not spend to much energy trying to jump around all nuances of batching. It's a sort of advanced feature out of official specs and it may be implemented in many ways.

**Comment by sungam3r** [comment]
Completed, right?

**Comment by Shane32** [comment]
Yes
