### ISSUE TITLE
How can I have the API respond to only POST and the UI respond only to GET?

### ISSUE THREAD

**Issue by justinmchase** [graphql-dotnet/server#778]
How can I get the graphql endpoint and the UI to both listen on /graphql? But have one respond to GET and the other to POST?

**Comment by justinmchase** [comment]
I was kind of hoping it would be this simple:

```cs
builder
  .AddSchema<ExampleSchema>(Methods.Post, "/graphql")
  .UseGraphQLAltair(Methods.Get, "/graphql")
```

But I don't see that and I don't see how to configure which methods it listends to in general.

**Comment by Shane32** [comment]
You can do that easily with GraphQL.AspNetCore3. It also has many other improvements, bug fixes and documentation over GraphQL.Server, particularly in the areas of configurability, WebSocket support and authentication.  We hope to import all of the changes here, but that may be a month or two out. 

Until then, take a look at https://github.com/Shane32/GraphQL.AspNetCore3

All of my servers are configured as you described, with the UI and the GraphQL endpoint configured at the same address.

**Comment by Shane32** [comment]
You can also try swapping the order of the UseGraphQL and UseGraphQLAltair statements and see if that works with the old GraphQL.Server project.

**Comment by justinmchase** [comment]
I did swap the order but it seems like the UI has the same problem it is also listening for POST and then the api becomes uncallable.

**Comment by Shane32** [comment]
Well that should be considered a bug probably

**Comment by Shane32** [comment]
You can probably do this if you like:

```cs
        app.UseWhen(
           context => HttpMethods.IsGet(context.Request.Method) && context.Request.Path.StartsWithSegments("/graphql", out var remaining) && string.IsNullOrEmpty(remaining),
           b => b.UseMiddleware<AltairMiddleware>(options ?? new AltairOptions()));
```

**Comment by justinmchase** [comment]
@Shane32 Thanks, that worked perfect. I was just experimenting with something similar and this just solved it for me. 

It could be a feature request to add the `IsGet(context.Request.Method)` either by default for the UI's or perhaps optionally.

I could be wrong but I think its pretty standard to have the UI handle GET and the API handle POST for the same route.
