### ISSUE TITLE
 Immediately respond with 405 instead of 400

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#794]
I agree but the parsing has not occurred prior. You are welcome to create a PR that works better. For now this is an improvement over nothing, which is what happens now.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/server/pull/774#discussion_r877585267_

**Comment by sungam3r** [comment]
Also change base type from `ValidationError` to `RequestError`.

**Comment by sungam3r** [comment]
@Shane32 Are you agree to change base type for these errors?

**Comment by Shane32** [comment]
I think requesterror should be for errors that occur prior to processing. Once we change the http method validation rule to occur prior to processing then it would be appropriate to change the base type. Access denied generally should always be a validation error -- ????  I'll think more later. Just my quick thoughts now.

**Comment by sungam3r** [comment]
> Access denied generally should always be a validation error 

Really? It happens before request parsing in `HandleAuthorizeAsync` at the beginnig of `GraphQLHttpMiddleware.InvokeAsync`.

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/169418417-1db77065-854d-4bac-9f78-87eaff125021.png)
I'm done for today. Actually only one file left to review - it is middleware itself. This should not take much time tomorrow, I checked the rest of the code.

**Comment by Shane32** [comment]
What you say is logical; however, my implementation of the authorization validation rule uses the same error class.  I have not yet posted the PR for the changes to the authorization library here.  If the errors are kept separate then yes it would make sense to have this one inherit from `RequestError`.  However, I don't see a compelling reason to have separate error classes in this case, as they would be identical apart from inheritance.  Let's review again after the rest of my changes are merged.

**Comment by Shane32** [comment]
@sungam3r Do you think that transport-level authorization rules (those defined on the middleware, which occur before the document is parsed) should return a 405 error, while authorization errors during validation should a 400 error?

**Comment by sungam3r** [comment]
Spec does not say "before the document is **parsed**". It says "_immediately_ respond with error status code 405". What does "immediately" mean? I don't know but I suppose that it's absolutely fine to parse document first to determine what we can do and what can not or should / should not. So I think it would be good to return more concrete code 405 in case of special condition then generic 400. And it is not nessessary to hardcode those int values into middleware. See https://github.com/graphql-dotnet/server/pull/774#discussion_r877593765.
