### ISSUE TITLE
Split POST body-parsing code to separate method

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/server#795]
In my company, I have a rule of thumb that methods "cannot be more than two pages of code".  This encourages splitting up functionality into understandably-sized pieces, and I have tried to adhere to that principle here as well.  Here we have about 2.5-3 pages of code in the InvokeAsync method.  If anything, we could probably split up the code further -- for example splitting the code to read the POST body content to another method.  This has an added benefit of allowing derived classes to implement another content type, if desired.  But even as-is, I think the code is pretty easy to understand.

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/server/pull/774#discussion_r877657481_

**Comment by sungam3r** [comment]
One note from me here - the value of smaller files is that PR review is accelerated.
