### ISSUE TITLE
Pull IServiceScopeFactory from context.RequestServices

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/server#796]
I mean only that specifically this dependency is somewhat different from the rest in the sense that it is not mandatory and it may not be obtained at all. I understand that one can pull all dependencies from `HttpContext.RequestServices`. I do not call for this - _documentExecuter and _serializer should be taken as dependencies. I'm saying more about not to consider any API for working with scopes as dependency. It's internal infrastructure code.

_Originally posted by @sungam3r in https://github.com/graphql-dotnet/server/pull/774#discussion_r878553674_

**Comment by Shane32** [comment]
I was working on a PR for this just now -- but the WebSocket handler (which will be posted shortly) requires the service scope factory and cannot execute requests without it.  So it may not make sense to remove it.  In any case, it will be better to review the required changes after the WebSocket handling code is merged in rather than beforehand.

**Comment by sungam3r** [comment]
ok

**Comment by Shane32** [comment]
@sungam3r I reviewed this again.  `IServiceScopeFactory` is required when executing batch requests and for any WebSocket connections.  I'm not sure what change would be worth making here.  Do you want to review this again?  Let's discuss or close the issue.

**Comment by sungam3r** [comment]
Since `IServiceScopeFactory` is required for both Subscription servers I'm fine to keep this dependency as is for `GraphQLHttpMiddleware`.
