### ISSUE TITLE
Investigate a better way of using buffers to handle WebSocket messages

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#813]
Do you have any questions here?  Yes it is complicated to read.  Yes it would certainly be more optimized with the MS package you previously referenced.  But everything should work.

Note that I do not know how likely it is for a message to come through as a single packet (and so retain in the 16kb buffer).  It is possible that messages often come through as multiple packets, especially if TCP breaks apart packets over 1500 bytes.  This could be further optimized by reusing the 16kb buffer until it was full before switching to the stream.  

It's also possible that the message comes through as a packet and then the end-of-message packet comes through separately (just as we send messages).  This would currently hit the stream instead of staying within the 16kb buffer (without further optimization).

_Originally posted by @Shane32 in https://github.com/graphql-dotnet/server/pull/809#discussion_r885764367_

**Comment by Shane32** [comment]
I would like to note on this topic that I would expect all of the control messages (connection, keep-alive, stop, close, etc) would be contained within a single TCP packet, and as such would already be optimized in the code here.  Only GraphQL requests, which for the WebSocket protocol are typically to set up subscriptions, might be larger than a single TCP packet and cause a MemoryStream allocation.

All messages sent from the server are already optimized, as the serializer serializes directly to the WebSocket stream.  This might be control messages, but would also include periodic data events from subscription event streams.

As such, I would say that the priority of further optimization here is low.  It still would be nice to provide a small additional optimization to prevent MemoryStream allocations when the total request size is < 16kb, even if across multiple TCP packets.  This should cover many or perhaps most GraphQL requests.  But I would not suggest adding a 3rd party dependency for further optimization of inbound data packets.
