### ISSUE TITLE
Missing GraphQLHttpMiddlewareWithLogs get started following ReadMe

### ISSUE THREAD

**Issue by OxyzOne** [graphql-dotnet/server#830]
When I get started following ReadMe, encountered missing item: **GraphQLHttpMiddlewareWithLogs** using 'With Routing' option

> ```
>     app.UseEndpoints(endpoints =>
>     {
>         // map websocket middleware for ChatSchema at default path /graphql
>         endpoints.MapGraphQLWebSockets<ChatSchema>();
> 
>         // map HTTP middleware for ChatSchema at default path /graphql
>         endpoints.MapGraphQL<ChatSchema, GraphQLHttpMiddlewareWithLogs<ChatSchema>>();
> ```

Found out that the missing class is in sample projects which is not included in instruction step. So I need to copy the class from sample project.

I think **GraphQLHttpMiddlewareWithLogs** should be change to **GraphQLHttpMiddleware** in the ReadMe docs

**Comment by Shane32** [comment]
> I think **GraphQLHttpMiddlewareWithLogs** should be change to **GraphQLHttpMiddleware** in the ReadMe docs

Correct

**Comment by sungam3r** [comment]
I'll fix docs.

**Comment by sungam3r** [comment]
Will be merged from `develop` into `master` some time later.
