### ISSUE TITLE
Deprecate all removed server packages on Nuget.org

### ISSUE THREAD

**Issue by sungam3r** [graphql-dotnet/server#832]
https://devblogs.microsoft.com/nuget/deprecating-packages-on-nuget-org/

**Comment by Shane32** [comment]
I was thinking along similar lines also: perhaps for v7 we should publish empty packages for auth/core/subscriptions that reference GraphQL.Server.Transports.AspNetCore, and deprecate those empty packages with a string that says "This package is not necessary for Server v7 and can safely be removed" or similar.  It might make the transition much easier for people -- most of the time they get hung up on the packages it seems.

I do not think we should deprecate packages that are valid for a prior version.

**Comment by Shane32** [comment]
I have a concern here with deprecating the removed server packages.  Those packages are entirely valid packages when used with the correct version of GraphQL.NET and GraphQL.NET Server.  I suggest updating the old packages with a version restriction such that they cannot be used with incompatible versions of GraphQL.NET or GraphQL.NET Server.

I might suggest releasing empty nuget packages for v7.0.0 which reference the correct counterparts and deprecating those empty packages with a note that says they are unnecessary for v7.

**Comment by sungam3r** [comment]
>  Those packages are entirely valid packages when used with the correct version of GraphQL.NET and GraphQL.NET Server

Some time ago I learned that even MS deprecate _entirely valid_ packages. See https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection/5.0.0 and https://github.com/dotnet/announcements/issues/217

**Comment by Shane32** [comment]
Ok let’s follow their example

**Comment by Shane32** [comment]
> I suggest updating the old packages with a version restriction such that they cannot be used with incompatible versions of GraphQL.NET or GraphQL.NET Server.

This has generally been done.
