### ISSUE TITLE
Websocket error invalid state CloseSent

### ISSUE THREAD

**Issue by keeshus** [graphql-dotnet/server#834]
Hi group,

I get errors within my instance of GraphQL server (sometimes several times per second) of the following:

`The WebSocket is in an invalid state ('CloseSent') for this operation. Valid states are: 'Open, CloseReceived'`

Anyone encountered this issue before, and how did you fix this? I have seen issues on the tracker regarding an 'Aborted' state, but never a 'CloseSent' state.

Any help would be greatly appreciated! Thank you!

**Comment by Shane32** [comment]
All of the WebSocket code has been rewritten for the upcoming version 7.  You should not experience the problem with the new version.  Let me know if you want to try a beta version.

**Comment by keeshus** [comment]
Alright, thank you for your information. I will update to version 7 as soon as it becomes available. For now we will be ignoring these errors and hope they will be resolved in the new version.

Thank you for your fast reply!
