### ISSUE TITLE
Exception after upgrading to version 6.1.0, having to change from Field to FieldAsync in schema

### ISSUE THREAD

**Issue by MEmanuelsson** [graphql-dotnet/server#842]
I've followed the instructions in this discussion https://github.com/graphql-dotnet/server/issues/819 to upgrade our setup of GraphQL-dotnet/server and it pretty much works as expected. 

One thing however that didn't work as expected was the following. One query we have setup looks like this (simplified a bit for readability, removed some parameters from original for instance):

```
Field<SiteContentType>(
                "siteContent",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<StringGraphType>> { Name = HostParameterName, Description = "Site host name" }
                ),
                resolve: context =>
                {
                    if (context.RequestServices is null)
                    {
                        return null;
                    }
                    var host = context.GetArgument<string>(HostParameterName);
                    var contentService = context.RequestServices.GetRequiredService<IContentService>();
                    var result = contentService.GetSiteContent(host);
                    return result;
                });
```

If I call this query after the upgrade I get the following exception:

GraphQL.Execution.UnhandledError: Error trying to resolve field \u0027siteContent\u0027.\n ---\u003E System.InvalidOperationException: \u0027System.Runtime.CompilerServices.AsyncTaskMethodBuilder\u00601\u002BAsyncStateMachineBox\u00601[Queue.Models.Models.SiteContent.Models.SiteContent,GraphQL.API.Services.ContentService\u002B\u003CGetSiteContent\u003Ed__4]\u0027 value of type \u0027System.Runtime.CompilerServices.AsyncTaskMethodBuilder\u00601\u002BAsyncStateMachineBox\u00601[Queue.Models.Models.SiteContent.Models.SiteContent,GraphQL.API.Services.ContentService\u002B\u003CGetSiteContent\u003Ed__4]\u0027 is not allowed for \u0027SiteContent\u0027. Either change IsTypeOf method of \u0027SiteContent\u0027 to accept this value or return another value from your resolver.\n   at GraphQL.Execution.ExecutionStrategy.ValidateNodeResult(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 645\n   at GraphQL.Execution.ExecutionStrategy.CompleteNodeAsync(ExecutionContext context, ExecutionNode node) in /_/src/GraphQL/Execution/ExecutionStrategy.cs:line 528\n   --- End of inner exception stack trace ---

However if I change from `Field` to `FieldAsync` like this, everything works like before (as far as I can see at least):

 ```
FieldAsync<SiteContentType>(
                "siteContent",
                arguments: new QueryArguments(
                    new QueryArgument<NonNullGraphType<StringGraphType>> { Name = HostParameterName, Description = "Site host name" }
                ),
                resolve: async context =>
                {
                    if (context.RequestServices is null)
                    {
                        return null;
                    }
                    var host = context.GetArgument<string>(HostParameterName);
                    var contentService = context.RequestServices.GetRequiredService<IContentService>();
                    var result = await contentService.GetSiteContent(host);
                    return result;
                });
```

Is this a change in version 6 that is described somewhere that I've missed, or am I doing something wrong in my setup? I have no problem doing this change from `Field` to `FieldAsync` but just wanted to ask if this change is by design.

Best regards
Martin

**Comment by Shane32** [comment]
Yes

https://graphql-dotnet.github.io/docs/migrations/migration5#32-valuetask-execution-pipeline-support-changes

**Comment by sungam3r** [comment]
This is a very unpleasant runtime error and someone can only find it in production.
