### ISSUE TITLE
GraphQLMiddleware and content type charset

### ISSUE THREAD

**Issue by GeertvanHorrik** [graphql-dotnet/server#844]
The GraphQLMiddleware sets the content type explicitly to `application/json`

 https://github.com/graphql-dotnet/server/blob/6bba2cb6543627344a646d345f1af671fde94ad4/src/Transports.AspNetCore/GraphQLHttpMiddleware.cs#L280

Is there a reason why this is not to `application/json; charset=utf-8`?

From what I understand, for security reasons, it's best practice to always add a charset?

If it makes sense, I am happy to do a PR by adding a virtual property that is empty by default to not break anything. Overriding this whole method in the middleware is also possible but then future improvements will be missed in case something changes there.

**Comment by Shane32** [comment]
It's already been changed for version 7.  It will be `application/graphql+json; charset=utf-8` in the new version as recommended by the draft GraphQL spec.

See:
- #798
- https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md

**Comment by GeertvanHorrik** [comment]
Your answer is perfect, thanks for taking the time to respond. I tried searching for 'charset' in the issues and couldn't find any previous ones.

Looking forward to v7 :-)
