### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by Shane32** [graphql-dotnet/server#868]
I'd like to remove one badge so it all fits on one line -- just for aesthetic purposes perhaps but we do have a lot of badges now.

![image](https://user-images.githubusercontent.com/6377684/178994842-adfc6138-2bbb-45bd-829e-a67da55f6717.png)

I prefer to remove of one of the following:
- Release date (we already have the version number, which should be sufficient)
- Repo size (the repo size doesn't really matter; the NuGet size is what would matter)

I'm okay to leave it as-is, but I would prefer to remove one @sungam3r

**Comment by sungam3r** [comment]
Rename with shorter text is fine.
