### ISSUE TITLE
Authorization not working after upgrading to v6

### ISSUE THREAD

**Issue by mijgame** [graphql-dotnet/server#884]
Hi,

I'm currently a bit confused. Is the graphql-dotnet/authorization package still relevant? The documentation seems out of date.

I'm trying to upgrade the GraphQL setup for my application to v6, and I'm running into some issues with the authorization. 

I have a list of permissions that I'm inserting as policies. When a request is made, it should check the `permissions` claim in the JWT-token for the presence of the permission. Note that this setup worked perfectly before the upgrade.

I'm running into the following error when running a query:
```
GraphQL.Server.Authorization.AspNetCore.AuthorizationError: You are not authorized to run this query.\nRequired claim 'permissions' with any value of 'accounts:read' is not present.
```

I can guarantee this claim is present in the token. I have a suspicion that there is something going wrong with the UserContext. When stepping through the authentication process with the debugger, the `UserContext` appears to be `null`. My `UserContextBuilder` is called however. Can you see where this is going wrong? The relevant code:

```csharp
services.AddGraphQL(builder =>
        {
            builder
                .AddGraphQLAuthorization(options =>
                {
                    // Create a policy for all available permissions.
                    foreach (var permission in Permissions.All)
                    {
                        options.AddPolicy(permission,
                            p => p.RequireClaim("permissions", permission));
                    }
                })
                .CustomizeGraphQLAuth()
                .AddHttpMiddleware<ISchema>()
                .AddSchema<AeSchema>()
                .AddDocumentExecuter<SerialDocumentExecutor>()
                .AddGraphTypes()
                .AddErrorInfoProvider(options =>
                {
                    // TODO: disable in release
                    options.ExposeExceptionStackTrace = true;
                }) 
                .ConfigureExecutionOptions(options =>
                {
                    // TODO: disable in release
                    options.EnableMetrics = true;
                })
                .AddSystemTextJson()
                .AddDataLoader();
        });
```

`CustomizeGraphQLAuth` refers to the following:

```csharp
public static class GraphQLAuthExtensions
{
    public static IGraphQLBuilder CustomizeGraphQLAuth(this IGraphQLBuilder builder)
    {
        builder.AddUserContextBuilder(ImplementationFactory);

        return builder;
    }

    private static GraphQLUserContext ImplementationFactory(HttpContext context)
    {
        var hostEnvironment = (IWebHostEnvironment)context.RequestServices.GetService(typeof(IWebHostEnvironment))!;

        // GraphiQL has an exemption. Because we can't add authentication easily to the GraphiQL interface, and it is
        // purely for debug, we make the GraphQL authentication validator believe we have all permissions.
        if (hostEnvironment.IsDevelopment() &&
            context.Request.Headers.TryGetValue("Referer", out var referer) &&
            referer.Count > 0 &&
            referer[0].Contains("/ui/graphiql"))
        {
            return BuildUserContextWithAllPermissions();
        }


        return new GraphQLUserContext(context.User);
    }

    private static GraphQLUserContext BuildUserContextWithAllPermissions()
    {
        var claims = Permissions.All.Select(permission => new Claim("permissions", permission))
            .ToList();
        
        claims.Add(new Claim(GraphQLUserContext.StoreIdClaim, "1"));
        claims.Add(new Claim(ClaimTypes.NameIdentifier, "<redacted>"));

        var claimsIdentity = new ClaimsIdentity(claims);
        var principal = new ClaimsPrincipal(claimsIdentity);

        return new GraphQLUserContext(principal);
    }
}
```

I'm using the latest version of the `GraphQL.Server.All` NuGet package. Please let me know if you need any additional information.

Regards.

**Comment by Shane32** [comment]
I’d try to add a GraphQL field with no permission requirements and then add a breaakpoint and examine the principal within your user context. I would not be surprised if .NET is renaming your “permission” claim to a .NET constant. I know it does so for the “role” claim. You probably just need to have your RequireClaim line of code use the .NET constant instead.

**Comment by Shane32** [comment]
See #885 for a working sample of a GraphQL.NET Server v7 server supporting JWT Bearer authentication.  The sample does not focus on how users are authenticated prior to the JWT token being generated, but rather how ASP.NET Core and GraphQL.NET Server is to be properly configured to support JWT tokens.  Nevertheless, an extremely basic OAuth2-compatible endpoint is included demonstrating the client-credentials flow.  The sample project demonstrates proper authentication support via the HTTP Authorization header and, for WebSocket connections, within the payload of the websocket's initialization message.

v7 should be released any day now.

**Comment by mijgame** [comment]
Hi, thanks for your input. I created the dummy endpoint and inspected the user context, and the claims have not been renamed. I checked, and there is no .NET constant available for the "permissions" claim; people just create one themselves.

I'm confused however. In my dummy endpoint I can see all claims being present. But when I add a policy to the dummy endpoint, the policy check fails. Did something change in the way the rule works in v6? I checked out the example project, but I can't see any meaningful differences between that setup and mine.

**Comment by Shane32** [comment]
It certainly should work.  Here's a few things I noticed:

1. The authorization rule uses `IClaimsPrincipalAccessor` to pull the current `ClaimsPrinicpal`.  It does not use the user context builder.  So it may be that when testing locally, it will not show an authenticated user from the `/ui/graphql` endpoint even if the user context does show it.  Create a custom implementation of `IClaimsPrincipalAccessor` and register it as a singleton (of type `IClaimsPrincipalAccessor`) to change this.  See https://github.com/graphql-dotnet/server/blob/master/src/Authorization.AspNetCore/DefaultClaimsPrincipalAccessor.cs for the reference implementation.

2. There is no scheme set in `BuildUserContextWithAllPermissions`.  So `IsAuthenticated` will return `false`.  Change `var claimsIdentity = new ClaimsIdentity(claims);` to `var claimsIdentity = new ClaimsIdentity(claims, "Bearer");`.  This may not affect v6 much but will certainly be a problem in v7.

**Comment by mijgame** [comment]
A custom `IClaimsPrincipalAccessor` implementation solved the problem! Thank you. Just to be complete for any people reading this issue, I implemented the custom accessor as follows:
```csharp
public class ClaimsPrincipalAccessor : IClaimsPrincipalAccessor
{
    private readonly IUserContextBuilder _userContextBuilder;
    private readonly IHttpContextAccessor _contextAccessor;

    public ClaimsPrincipalAccessor(IUserContextBuilder userContextBuilder, IHttpContextAccessor contextAccessor)
    {
        _userContextBuilder = userContextBuilder;
        _contextAccessor = contextAccessor;
    }

    public ClaimsPrincipal GetClaimsPrincipal(ValidationContext context)
    {
        var userContext = (GraphQLUserContext) _userContextBuilder
            .BuildUserContext(_contextAccessor.HttpContext)
            .GetAwaiter()
            .GetResult();

        return userContext.User;
    }
}
```

Note that `GraphQLUserContext` is my own context. It inherits from `Dictionary<string, object>` and contains my `ClaimsPrincipal`.
