### ISSUE TITLE
Update Voyager middleware to always fetch latest version of Voyager

### ISSUE THREAD

**Issue by BenjaBobs** [graphql-dotnet/server#91]
They just merged this, so I'm thinking we should use the same script link.
https://github.com/APIs-guru/graphql-voyager/commit/7466fabc1f6284593328d1083865d4d4e97a7876

**Comment by pekkah** [comment]
Yep. We could.

**Comment by sungam3r** [comment]
@BenjaBobs I compared the versions of our scripts with the versions you specified. They are identical. This was fixed by #205
