### ISSUE TITLE
WebSockets stop responding if browser closes connection

### ISSUE THREAD

**Issue by joshkel** [graphql-dotnet/server#92]
We noticed that the WebSockets middleware would stop responding (and enter an endless loop of errors) if a client closed its connection.

It looks like the problem is [here](https://github.com/graphql-dotnet/server/blob/db0e373dcd8994bd51b65d5c581be6aa0510a7ed/src/WebSockets/WebSocketReaderPipeline.cs#L73). Unless I'm mistaken, the loop should abort if completed, canceled, or closed, so each `||` should be `&&`.

**Comment by pekkah** [comment]
Is this now fixed?

**Comment by joshkel** [comment]
As far as I can tell, yes.
