### ISSUE TITLE
Question about upgrading from 6xx to 7xx: VoyagerOptions

### ISSUE THREAD

**Issue by dan93-93** [graphql-dotnet/server#961]
Hi, just upgrading this package it seems that it no longer supports the below VoyagerOptions() without running in to the below errors:

cannot convert from 'GraphQL.Server.Ui.Voyager.VoyagerOptions' to 'string'
cannot convert from 'string' to 'GraphQL.Server.Ui.Voyager.VoyagerOptions?'
	 
Working fine in v6 but examples on other issues show you using a similar implementation and I can't see that release notes were updated for this options block:

```
            var isLocalEnv = _env.IsLocalTest() || _env.IsLocalDev();

            app.UseGraphQLVoyager(new VoyagerOptions()
            {
                GraphQLEndPoint = isLocalEnv ? "/" : "/myapp/graphql/" 
            }, "/voyager");
```

Apologies if this has been covered already

**Comment by dan93-93** [comment]
Okay, in the end targeting the parameters worked:

```
            var options = new VoyagerOptions()
            {
                GraphQLEndPoint = isLocalEnv ? "/" : "/nextgen/graphql/" // gateway path
            };
            app.UseGraphQLVoyager(options: options, path: "/voyager");
```

So the problem is the original code wasn't hitting the overload. Is that an intended implementation going forward?

**Comment by Shane32** [comment]
> I can't see that release notes were updated for this options block

The 7.0.0 release notes contains a link to the migration notes for v7.

https://github.com/graphql-dotnet/server/releases/tag/7.0.0

The bottom of the "description" section of the readme also contains the link to the migration notes.

https://github.com/graphql-dotnet/server#description

Please comment if you feel that the migration notes were difficult to find, and where you think the link should be placed.

**Comment by Shane32** [comment]
Just FYI, the order of parameters was swapped to be uniform with `UseGraphQL` and other similar ASP.NET extension methods.
