### ISSUE TITLE
[Docs] Updates?

### ISSUE THREAD

**Issue by benmccallum** [graphql-dotnet/server#98]
Just following the install guide and there's a few things that may be outdated or I need help with.

* Looks like it's being released on the nuget gallery now, do we need the myget feed?
* Looks like `dotnet add` command requires the package specifier now. `dotnet add package ...`
* Looks like the UI (GraphiQL and Playground) aren't included in the nuget package. I couldn't use them as the setup suggested. Will they become available in this package or even a new one?

**Comment by benmccallum** [comment]
Also I think the dotnet add command requires the package specifier now. `dotnet add package ...`. Couldn't do it without.

**Comment by benmccallum** [comment]
It doesn't look like the UI dlls (`UseGraphiQLServer` or `UseGraphQLPlayground` extensions) are available in the standard NuGet package. I just grabbed v3.1.0.0-alpha0016 from NuGet standard feed and couldn't use them as the configuration example shows. Is that likely to be available in the future, even as separate packages if necessary?

**Comment by pekkah** [comment]
Haven't updated them much. Should probably write bit more for next stable release.

**Comment by benmccallum** [comment]
Yea no worries, an update will address points 1 & 2. How about 3? Are the UIs going be in the main NuGet package so they can be used in development mode? Thanks!

**Comment by pekkah** [comment]
3. They're provided as separate nuget packages...

**Comment by benmccallum** [comment]
Sorry I didn't see the other packages. Put in a PR (https://github.com/graphql-dotnet/server/pull/101) so this can be closed out.
