### ISSUE TITLE
Is there a way to change the status code of the authorization extension from 400 to 401?

### ISSUE THREAD

**Issue by nichovski** [graphql-dotnet/server#986]
Hi guys,

It is very strange when my HTTP response codes are not corresponding to the error I want to return to the front end. How can I change that? 

I've tried overriding the GraphQLMiddleware, but it is triggered only when my query doesn't have errors. 

Thank you!

**Comment by Shane32** [comment]
Version 8 will return more appropriate status codes from the authorization validation rule in certain cases
